/* confirm-exit.c generated by valac 0.28.0, the Vala compiler
 * generated from confirm-exit.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>


#define TYPE_CONFIRM_EXIT (confirm_exit_get_type ())
#define CONFIRM_EXIT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CONFIRM_EXIT, ConfirmExit))
#define CONFIRM_EXIT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CONFIRM_EXIT, ConfirmExitClass))
#define IS_CONFIRM_EXIT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CONFIRM_EXIT))
#define IS_CONFIRM_EXIT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CONFIRM_EXIT))
#define CONFIRM_EXIT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CONFIRM_EXIT, ConfirmExitClass))

typedef struct _ConfirmExit ConfirmExit;
typedef struct _ConfirmExitClass ConfirmExitClass;
typedef struct _ConfirmExitPrivate ConfirmExitPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ConfirmExit {
	GtkDialog parent_instance;
	ConfirmExitPrivate * priv;
};

struct _ConfirmExitClass {
	GtkDialogClass parent_class;
};


static gpointer confirm_exit_parent_class = NULL;

GType confirm_exit_get_type (void) G_GNUC_CONST;
enum  {
	CONFIRM_EXIT_DUMMY_PROPERTY
};
ConfirmExit* confirm_exit_new (void);
ConfirmExit* confirm_exit_construct (GType object_type);
static void confirm_exit_create_widgets (ConfirmExit* self);


ConfirmExit* confirm_exit_construct (GType object_type) {
	ConfirmExit * self = NULL;
	const gchar* _tmp0_ = NULL;
	self = (ConfirmExit*) g_object_new (object_type, NULL);
	_tmp0_ = _ ("Confirm operation");
	gtk_window_set_title ((GtkWindow*) self, _tmp0_);
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 10);
	confirm_exit_create_widgets (self);
	return self;
}


ConfirmExit* confirm_exit_new (void) {
	return confirm_exit_construct (TYPE_CONFIRM_EXIT);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void confirm_exit_create_widgets (ConfirmExit* self) {
	GtkLabel* mensaje = NULL;
	const gchar* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	GtkBox* content = NULL;
	GtkBox* _tmp5_ = NULL;
	GtkBox* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = _ ("Do you wish to save changes before closing?");
	_tmp1_ = (GtkLabel*) gtk_label_new (_tmp0_);
	g_object_ref_sink (_tmp1_);
	mensaje = _tmp1_;
	_tmp2_ = _ ("Close without saving");
	gtk_dialog_add_button ((GtkDialog*) self, _tmp2_, (gint) GTK_RESPONSE_ACCEPT);
	_tmp3_ = _ ("Cancel");
	gtk_dialog_add_button ((GtkDialog*) self, _tmp3_, (gint) GTK_RESPONSE_CANCEL);
	_tmp4_ = _ ("Save");
	gtk_dialog_add_button ((GtkDialog*) self, _tmp4_, (gint) GTK_RESPONSE_APPLY);
	_tmp5_ = (GtkBox*) gtk_dialog_get_content_area ((GtkDialog*) self);
	_tmp6_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp5_, gtk_box_get_type ()) ? ((GtkBox*) _tmp5_) : NULL);
	content = _tmp6_;
	gtk_box_pack_start (content, (GtkWidget*) mensaje, TRUE, TRUE, (guint) 0);
	gtk_box_set_spacing (content, 10);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (content);
	_g_object_unref0 (mensaje);
}


static void confirm_exit_class_init (ConfirmExitClass * klass) {
	confirm_exit_parent_class = g_type_class_peek_parent (klass);
}


static void confirm_exit_instance_init (ConfirmExit * self) {
}


GType confirm_exit_get_type (void) {
	static volatile gsize confirm_exit_type_id__volatile = 0;
	if (g_once_init_enter (&confirm_exit_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ConfirmExitClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) confirm_exit_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ConfirmExit), 0, (GInstanceInitFunc) confirm_exit_instance_init, NULL };
		GType confirm_exit_type_id;
		confirm_exit_type_id = g_type_register_static (gtk_dialog_get_type (), "ConfirmExit", &g_define_type_info, 0);
		g_once_init_leave (&confirm_exit_type_id__volatile, confirm_exit_type_id);
	}
	return confirm_exit_type_id__volatile;
}



