/* programming-languages.c generated by valac 0.28.0, the Vala compiler
 * generated from programming-languages.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define TYPE_PROGRAMMING_LANGUAGES (programming_languages_get_type ())
#define PROGRAMMING_LANGUAGES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PROGRAMMING_LANGUAGES, ProgrammingLanguages))
#define PROGRAMMING_LANGUAGES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PROGRAMMING_LANGUAGES, ProgrammingLanguagesClass))
#define IS_PROGRAMMING_LANGUAGES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PROGRAMMING_LANGUAGES))
#define IS_PROGRAMMING_LANGUAGES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PROGRAMMING_LANGUAGES))
#define PROGRAMMING_LANGUAGES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PROGRAMMING_LANGUAGES, ProgrammingLanguagesClass))

typedef struct _ProgrammingLanguages ProgrammingLanguages;
typedef struct _ProgrammingLanguagesClass ProgrammingLanguagesClass;
typedef struct _ProgrammingLanguagesPrivate ProgrammingLanguagesPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_array_unref0(var) ((var == NULL) ? NULL : (var = (g_array_unref (var), NULL)))
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _ParamSpecProgrammingLanguages ParamSpecProgrammingLanguages;

struct _ProgrammingLanguages {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ProgrammingLanguagesPrivate * priv;
};

struct _ProgrammingLanguagesClass {
	GTypeClass parent_class;
	void (*finalize) (ProgrammingLanguages *self);
};

struct _ProgrammingLanguagesPrivate {
	GeeHashMap* lang_ids;
	GeeHashMap* lang_names;
	GeeHashMap* lang_id_names;
	GeeHashMap* lang_ext;
	GArray* buildables;
	GList* _languages;
};

struct _ParamSpecProgrammingLanguages {
	GParamSpec parent_instance;
};


static gpointer programming_languages_parent_class = NULL;

gpointer programming_languages_ref (gpointer instance);
void programming_languages_unref (gpointer instance);
GParamSpec* param_spec_programming_languages (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_programming_languages (GValue* value, gpointer v_object);
void value_take_programming_languages (GValue* value, gpointer v_object);
gpointer value_get_programming_languages (const GValue* value);
GType programming_languages_get_type (void) G_GNUC_CONST;
#define PROGRAMMING_LANGUAGES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PROGRAMMING_LANGUAGES, ProgrammingLanguagesPrivate))
enum  {
	PROGRAMMING_LANGUAGES_DUMMY_PROPERTY
};
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
ProgrammingLanguages* programming_languages_new (void);
ProgrammingLanguages* programming_languages_construct (GType object_type);
static void programming_languages_setup_languages (ProgrammingLanguages* self);
static gchar* programming_languages_get_file_extension (ProgrammingLanguages* self, const gchar* filename);
gchar* programming_languages_get_lang_id (ProgrammingLanguages* self, const gchar* filename);
gchar* programming_languages_get_lang_id_from_name (ProgrammingLanguages* self, const gchar* language);
gchar* programming_languages_get_lang_name (ProgrammingLanguages* self, const gchar* filename);
gchar* programming_languages_get_lang_ext (ProgrammingLanguages* self, const gchar* lang_name);
gboolean programming_languages_is_buildable (ProgrammingLanguages* self, const gchar* filename);
GList* programming_languages_get_languages (ProgrammingLanguages* self);
static void programming_languages_finalize (ProgrammingLanguages* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static void _g_free0_ (gpointer var) {
	var = (g_free (var), NULL);
}


static void _g_list_free__g_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
	g_list_free (self);
}


ProgrammingLanguages* programming_languages_construct (GType object_type) {
	ProgrammingLanguages* self = NULL;
	GeeHashMap* _tmp0_ = NULL;
	GeeHashMap* _tmp1_ = NULL;
	GeeHashMap* _tmp2_ = NULL;
	GeeHashMap* _tmp3_ = NULL;
	GArray* _tmp4_ = NULL;
	self = (ProgrammingLanguages*) g_type_create_instance (object_type);
	_tmp0_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->lang_ids);
	self->priv->lang_ids = _tmp0_;
	_tmp1_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->lang_names);
	self->priv->lang_names = _tmp1_;
	_tmp2_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->lang_id_names);
	self->priv->lang_id_names = _tmp2_;
	_tmp3_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->lang_ext);
	self->priv->lang_ext = _tmp3_;
	_tmp4_ = g_array_new (TRUE, TRUE, sizeof (gchar*));
	_g_array_unref0 (self->priv->buildables);
	self->priv->buildables = _tmp4_;
	__g_list_free__g_free0_0 (self->priv->_languages);
	self->priv->_languages = NULL;
	programming_languages_setup_languages (self);
	return self;
}


ProgrammingLanguages* programming_languages_new (void) {
	return programming_languages_construct (TYPE_PROGRAMMING_LANGUAGES);
}


static void programming_languages_setup_languages (ProgrammingLanguages* self) {
	GeeHashMap* _tmp0_ = NULL;
	GeeHashMap* _tmp1_ = NULL;
	GeeHashMap* _tmp2_ = NULL;
	GeeHashMap* _tmp3_ = NULL;
	GeeHashMap* _tmp4_ = NULL;
	GeeHashMap* _tmp5_ = NULL;
	GeeHashMap* _tmp6_ = NULL;
	GeeHashMap* _tmp7_ = NULL;
	GeeHashMap* _tmp8_ = NULL;
	GeeHashMap* _tmp9_ = NULL;
	GeeHashMap* _tmp10_ = NULL;
	GeeHashMap* _tmp11_ = NULL;
	GeeHashMap* _tmp12_ = NULL;
	GeeHashMap* _tmp13_ = NULL;
	GeeHashMap* _tmp14_ = NULL;
	GeeHashMap* _tmp15_ = NULL;
	GeeHashMap* _tmp16_ = NULL;
	GeeHashMap* _tmp17_ = NULL;
	GeeHashMap* _tmp18_ = NULL;
	GeeHashMap* _tmp19_ = NULL;
	GeeHashMap* _tmp20_ = NULL;
	GeeHashMap* _tmp21_ = NULL;
	GeeHashMap* _tmp22_ = NULL;
	GeeHashMap* _tmp23_ = NULL;
	GeeHashMap* _tmp24_ = NULL;
	GeeHashMap* _tmp25_ = NULL;
	GeeHashMap* _tmp26_ = NULL;
	GeeHashMap* _tmp27_ = NULL;
	GeeHashMap* _tmp28_ = NULL;
	GeeHashMap* _tmp29_ = NULL;
	GeeHashMap* _tmp30_ = NULL;
	GeeHashMap* _tmp31_ = NULL;
	GeeHashMap* _tmp32_ = NULL;
	GeeHashMap* _tmp33_ = NULL;
	GeeHashMap* _tmp34_ = NULL;
	GeeHashMap* _tmp35_ = NULL;
	GeeHashMap* _tmp36_ = NULL;
	GeeHashMap* _tmp37_ = NULL;
	GeeHashMap* _tmp38_ = NULL;
	GeeHashMap* _tmp39_ = NULL;
	GeeHashMap* _tmp40_ = NULL;
	GeeHashMap* _tmp41_ = NULL;
	GeeHashMap* _tmp42_ = NULL;
	GeeHashMap* _tmp43_ = NULL;
	GeeHashMap* _tmp44_ = NULL;
	GeeHashMap* _tmp45_ = NULL;
	GeeHashMap* _tmp46_ = NULL;
	GeeHashMap* _tmp47_ = NULL;
	GeeHashMap* _tmp48_ = NULL;
	GeeHashMap* _tmp49_ = NULL;
	GeeHashMap* _tmp50_ = NULL;
	GeeHashMap* _tmp51_ = NULL;
	GeeHashMap* _tmp52_ = NULL;
	GeeHashMap* _tmp53_ = NULL;
	GeeHashMap* _tmp54_ = NULL;
	GeeHashMap* _tmp55_ = NULL;
	GeeHashMap* _tmp56_ = NULL;
	GeeHashMap* _tmp57_ = NULL;
	GeeHashMap* _tmp58_ = NULL;
	GeeHashMap* _tmp59_ = NULL;
	GeeHashMap* _tmp60_ = NULL;
	GeeHashMap* _tmp61_ = NULL;
	GeeHashMap* _tmp62_ = NULL;
	GeeHashMap* _tmp63_ = NULL;
	GeeHashMap* _tmp64_ = NULL;
	GeeHashMap* _tmp65_ = NULL;
	GeeHashMap* _tmp66_ = NULL;
	GeeHashMap* _tmp67_ = NULL;
	GeeHashMap* _tmp68_ = NULL;
	GeeHashMap* _tmp69_ = NULL;
	GeeHashMap* _tmp70_ = NULL;
	GeeHashMap* _tmp71_ = NULL;
	GeeHashMap* _tmp72_ = NULL;
	GeeHashMap* _tmp73_ = NULL;
	GeeHashMap* _tmp74_ = NULL;
	GeeHashMap* _tmp75_ = NULL;
	GeeHashMap* _tmp76_ = NULL;
	GeeHashMap* _tmp77_ = NULL;
	GeeHashMap* _tmp78_ = NULL;
	GeeHashMap* _tmp79_ = NULL;
	GeeHashMap* _tmp80_ = NULL;
	GeeHashMap* _tmp81_ = NULL;
	GeeHashMap* _tmp82_ = NULL;
	GeeHashMap* _tmp83_ = NULL;
	GeeHashMap* _tmp84_ = NULL;
	GeeHashMap* _tmp85_ = NULL;
	GeeHashMap* _tmp86_ = NULL;
	GeeHashMap* _tmp87_ = NULL;
	GeeHashMap* _tmp88_ = NULL;
	GeeHashMap* _tmp89_ = NULL;
	GeeHashMap* _tmp90_ = NULL;
	GeeHashMap* _tmp91_ = NULL;
	GeeHashMap* _tmp92_ = NULL;
	GeeHashMap* _tmp93_ = NULL;
	GeeHashMap* _tmp94_ = NULL;
	GeeHashMap* _tmp95_ = NULL;
	GeeHashMap* _tmp96_ = NULL;
	GeeHashMap* _tmp97_ = NULL;
	GeeHashMap* _tmp98_ = NULL;
	GeeHashMap* _tmp99_ = NULL;
	GeeHashMap* _tmp100_ = NULL;
	GeeHashMap* _tmp101_ = NULL;
	GeeHashMap* _tmp102_ = NULL;
	GeeHashMap* _tmp103_ = NULL;
	GeeHashMap* _tmp104_ = NULL;
	GeeHashMap* _tmp105_ = NULL;
	GeeHashMap* _tmp106_ = NULL;
	GeeHashMap* _tmp107_ = NULL;
	GeeHashMap* _tmp108_ = NULL;
	GeeHashMap* _tmp109_ = NULL;
	GeeHashMap* _tmp110_ = NULL;
	GeeHashMap* _tmp111_ = NULL;
	GeeHashMap* _tmp112_ = NULL;
	GeeHashMap* _tmp113_ = NULL;
	GeeHashMap* _tmp114_ = NULL;
	GeeHashMap* _tmp115_ = NULL;
	GeeHashMap* _tmp116_ = NULL;
	GeeHashMap* _tmp117_ = NULL;
	GeeHashMap* _tmp118_ = NULL;
	GeeHashMap* _tmp119_ = NULL;
	GeeHashMap* _tmp120_ = NULL;
	GeeHashMap* _tmp121_ = NULL;
	GeeHashMap* _tmp122_ = NULL;
	GeeHashMap* _tmp123_ = NULL;
	GeeHashMap* _tmp124_ = NULL;
	GeeHashMap* _tmp125_ = NULL;
	GArray* _tmp126_ = NULL;
	gchar* _tmp127_ = NULL;
	GArray* _tmp128_ = NULL;
	gchar* _tmp129_ = NULL;
	GArray* _tmp130_ = NULL;
	gchar* _tmp131_ = NULL;
	GArray* _tmp132_ = NULL;
	gchar* _tmp133_ = NULL;
	GArray* _tmp134_ = NULL;
	gchar* _tmp135_ = NULL;
	GArray* _tmp136_ = NULL;
	gchar* _tmp137_ = NULL;
	GArray* _tmp138_ = NULL;
	gchar* _tmp139_ = NULL;
	GArray* _tmp140_ = NULL;
	gchar* _tmp141_ = NULL;
	GArray* _tmp142_ = NULL;
	gchar* _tmp143_ = NULL;
	GArray* _tmp144_ = NULL;
	gchar* _tmp145_ = NULL;
	GArray* _tmp146_ = NULL;
	gchar* _tmp147_ = NULL;
	GArray* _tmp148_ = NULL;
	gchar* _tmp149_ = NULL;
	gchar* _tmp150_ = NULL;
	gchar* _tmp151_ = NULL;
	gchar* _tmp152_ = NULL;
	gchar* _tmp153_ = NULL;
	gchar* _tmp154_ = NULL;
	gchar* _tmp155_ = NULL;
	gchar* _tmp156_ = NULL;
	gchar* _tmp157_ = NULL;
	gchar* _tmp158_ = NULL;
	gchar* _tmp159_ = NULL;
	gchar* _tmp160_ = NULL;
	gchar* _tmp161_ = NULL;
	gchar* _tmp162_ = NULL;
	gchar* _tmp163_ = NULL;
	gchar* _tmp164_ = NULL;
	gchar* _tmp165_ = NULL;
	gchar* _tmp166_ = NULL;
	gchar* _tmp167_ = NULL;
	gchar* _tmp168_ = NULL;
	gchar* _tmp169_ = NULL;
	gchar* _tmp170_ = NULL;
	gchar* _tmp171_ = NULL;
	gchar* _tmp172_ = NULL;
	gchar* _tmp173_ = NULL;
	gchar* _tmp174_ = NULL;
	gchar* _tmp175_ = NULL;
	gchar* _tmp176_ = NULL;
	gchar* _tmp177_ = NULL;
	gchar* _tmp178_ = NULL;
	gchar* _tmp179_ = NULL;
	gchar* _tmp180_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp0_, "c", "c");
	_tmp1_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp1_, "h", "cpp");
	_tmp2_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp2_, "cc", "cpp");
	_tmp3_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp3_, "cpp", "cpp");
	_tmp4_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp4_, "sh", "sh");
	_tmp5_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp5_, "pl", "perl");
	_tmp6_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp6_, "php", "php");
	_tmp7_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp7_, "xml", "xml");
	_tmp8_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp8_, "ui", "xml");
	_tmp9_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp9_, "tex", "latex");
	_tmp10_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp10_, "py", "python");
	_tmp11_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp11_, "java", "java");
	_tmp12_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp12_, "html", "html");
	_tmp13_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp13_, "cs", "c-sharp");
	_tmp14_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp14_, "bib", "bibtex");
	_tmp15_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp15_, "css", "css");
	_tmp16_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp16_, "desktop", "desktop");
	_tmp17_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp17_, "js", "js");
	_tmp18_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp18_, "json", "json");
	_tmp19_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp19_, "lex", "lex");
	_tmp20_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp20_, "l", "lex");
	_tmp21_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp21_, "Makefile", "makefile");
	_tmp22_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp22_, "md", "markdown");
	_tmp23_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp23_, "m", "matlab");
	_tmp24_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp24_, "rb", "ruby");
	_tmp25_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp25_, "sql", "sql");
	_tmp26_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp26_, "vala", "vala");
	_tmp27_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp27_, "vapi", "vala");
	_tmp28_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp28_, "vhd", "vhdl");
	_tmp29_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp29_, "xslt", "xslt");
	_tmp30_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp30_, "y", "yacc");
	_tmp31_ = self->priv->lang_ids;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp31_, "yaac", "yacc");
	_tmp32_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp32_, "c", "C");
	_tmp33_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp33_, "h", "C/C++ header file");
	_tmp34_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp34_, "cc", "C++");
	_tmp35_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp35_, "cpp", "C++");
	_tmp36_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp36_, "sh", "Shell script");
	_tmp37_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp37_, "pl", "Perl");
	_tmp38_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp38_, "php", "PHP");
	_tmp39_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp39_, "xml", "XML");
	_tmp40_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp40_, "tex", "LaTeX");
	_tmp41_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp41_, "py", "Python");
	_tmp42_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp42_, "java", "Java");
	_tmp43_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp43_, "html", "HTML");
	_tmp44_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp44_, "cs", "C#");
	_tmp45_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp45_, "bib", "Bibtex");
	_tmp46_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp46_, "css", "CSS");
	_tmp47_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp47_, "desktop", "Desktop launcher");
	_tmp48_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp48_, "js", "Javascript");
	_tmp49_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp49_, "json", "JSon");
	_tmp50_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp50_, "lex", "Lex");
	_tmp51_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp51_, "l", "Flex");
	_tmp52_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp52_, "Makefile", "Makefile");
	_tmp53_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp53_, "md", "Markdown");
	_tmp54_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp54_, "m", "MatLab");
	_tmp55_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp55_, "rb", "Ruby");
	_tmp56_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp56_, "sql", "SQL");
	_tmp57_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp57_, "vala", "Vala");
	_tmp58_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp58_, "vapi", "Vapi");
	_tmp59_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp59_, "vhd", "VHDL");
	_tmp60_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp60_, "xslt", "XSLT");
	_tmp61_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp61_, "y", "Bison");
	_tmp62_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp62_, "yaac", "YAAC");
	_tmp63_ = self->priv->lang_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp63_, "ui", "Glade UI");
	_tmp64_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp64_, "C", "c");
	_tmp65_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp65_, "C/C++ header file", "cpp");
	_tmp66_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp66_, "C++", "cpp");
	_tmp67_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp67_, "Shell script", "sh");
	_tmp68_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp68_, "Perl", "perl");
	_tmp69_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp69_, "PHP", "php");
	_tmp70_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp70_, "XML", "xml");
	_tmp71_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp71_, "Glade UI", "xml");
	_tmp72_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp72_, "LaTeX", "latex");
	_tmp73_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp73_, "Python", "python");
	_tmp74_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp74_, "Java", "java");
	_tmp75_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp75_, "HTML", "html");
	_tmp76_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp76_, "C#", "c-sharp");
	_tmp77_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp77_, "Bibtex", "bibtex");
	_tmp78_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp78_, "CSS", "css");
	_tmp79_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp79_, "Desktop launcher", "desktop");
	_tmp80_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp80_, "Javascript", "js");
	_tmp81_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp81_, "JSon", "json");
	_tmp82_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp82_, "Lex", "lex");
	_tmp83_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp83_, "Flex", "lex");
	_tmp84_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp84_, "Makefile", "makefile");
	_tmp85_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp85_, "Markdown", "markdown");
	_tmp86_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp86_, "MatLab", "matlab");
	_tmp87_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp87_, "Ruby", "ruby");
	_tmp88_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp88_, "SQL", "sql");
	_tmp89_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp89_, "Vala", "vala");
	_tmp90_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp90_, "Vapi", "vala");
	_tmp91_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp91_, "VHDL", "vhdl");
	_tmp92_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp92_, "XSLT", "xslt");
	_tmp93_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp93_, "Bison", "yacc");
	_tmp94_ = self->priv->lang_id_names;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp94_, "YAAC", "yacc");
	_tmp95_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp95_, "C", ".c");
	_tmp96_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp96_, "C/C++ header file", ".h");
	_tmp97_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp97_, "C++", ".cpp");
	_tmp98_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp98_, "Shell script", ".sh");
	_tmp99_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp99_, "Perl", ".pl");
	_tmp100_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp100_, "PHP", ".php");
	_tmp101_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp101_, "XML", ".xml");
	_tmp102_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp102_, "LaTeX", ".tex");
	_tmp103_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp103_, "Python", ".py");
	_tmp104_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp104_, "Java", ".java");
	_tmp105_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp105_, "HTML", ".html");
	_tmp106_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp106_, "C#", ".cs");
	_tmp107_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp107_, "Bibtex", ".bib");
	_tmp108_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp108_, "CSS", ".css");
	_tmp109_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp109_, "Desktop launcher", ".desktop");
	_tmp110_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp110_, "Javascript", ".js");
	_tmp111_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp111_, "JSon", ".json");
	_tmp112_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp112_, "Lex", ".lex");
	_tmp113_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp113_, "Flex", ".l");
	_tmp114_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp114_, "Makefile", ".Makefile");
	_tmp115_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp115_, "Markdown", ".md");
	_tmp116_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp116_, "MatLab", ".m");
	_tmp117_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp117_, "Ruby", ".rb");
	_tmp118_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp118_, "SQL", ".sql");
	_tmp119_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp119_, "Vala", ".vala");
	_tmp120_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp120_, "Vapi", ".vapi");
	_tmp121_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp121_, "VHDL", ".vhd");
	_tmp122_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp122_, "XSLT", ".xslt");
	_tmp123_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp123_, "Bison", ".y");
	_tmp124_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp124_, "YAAC", ".yaac");
	_tmp125_ = self->priv->lang_ext;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp125_, "Glade UI", ".ui");
	_tmp126_ = self->priv->buildables;
	_tmp127_ = g_strdup ("C");
	g_array_append_val (_tmp126_, _tmp127_);
	_tmp128_ = self->priv->buildables;
	_tmp129_ = g_strdup ("C++");
	g_array_append_val (_tmp128_, _tmp129_);
	_tmp130_ = self->priv->buildables;
	_tmp131_ = g_strdup ("LaTeX");
	g_array_append_val (_tmp130_, _tmp131_);
	_tmp132_ = self->priv->buildables;
	_tmp133_ = g_strdup ("Java");
	g_array_append_val (_tmp132_, _tmp133_);
	_tmp134_ = self->priv->buildables;
	_tmp135_ = g_strdup ("C#");
	g_array_append_val (_tmp134_, _tmp135_);
	_tmp136_ = self->priv->buildables;
	_tmp137_ = g_strdup ("Lex");
	g_array_append_val (_tmp136_, _tmp137_);
	_tmp138_ = self->priv->buildables;
	_tmp139_ = g_strdup ("Flex");
	g_array_append_val (_tmp138_, _tmp139_);
	_tmp140_ = self->priv->buildables;
	_tmp141_ = g_strdup ("Vala");
	g_array_append_val (_tmp140_, _tmp141_);
	_tmp142_ = self->priv->buildables;
	_tmp143_ = g_strdup ("Vapi");
	g_array_append_val (_tmp142_, _tmp143_);
	_tmp144_ = self->priv->buildables;
	_tmp145_ = g_strdup ("VHDL");
	g_array_append_val (_tmp144_, _tmp145_);
	_tmp146_ = self->priv->buildables;
	_tmp147_ = g_strdup ("Bison");
	g_array_append_val (_tmp146_, _tmp147_);
	_tmp148_ = self->priv->buildables;
	_tmp149_ = g_strdup ("YAAC");
	g_array_append_val (_tmp148_, _tmp149_);
	_tmp150_ = g_strdup ("Bibtex");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp150_);
	_tmp151_ = g_strdup ("Bison");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp151_);
	_tmp152_ = g_strdup ("C");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp152_);
	_tmp153_ = g_strdup ("C++");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp153_);
	_tmp154_ = g_strdup ("C#");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp154_);
	_tmp155_ = g_strdup ("C/C++ header file");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp155_);
	_tmp156_ = g_strdup ("CSS");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp156_);
	_tmp157_ = g_strdup ("Desktop launcher");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp157_);
	_tmp158_ = g_strdup ("Flex");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp158_);
	_tmp159_ = g_strdup ("Glade UI");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp159_);
	_tmp160_ = g_strdup ("HTML");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp160_);
	_tmp161_ = g_strdup ("Java");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp161_);
	_tmp162_ = g_strdup ("Javascript");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp162_);
	_tmp163_ = g_strdup ("JSon");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp163_);
	_tmp164_ = g_strdup ("LaTeX");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp164_);
	_tmp165_ = g_strdup ("Lex");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp165_);
	_tmp166_ = g_strdup ("Makefile");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp166_);
	_tmp167_ = g_strdup ("Markdown");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp167_);
	_tmp168_ = g_strdup ("MatLab");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp168_);
	_tmp169_ = g_strdup ("Perl");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp169_);
	_tmp170_ = g_strdup ("PHP");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp170_);
	_tmp171_ = g_strdup ("Python");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp171_);
	_tmp172_ = g_strdup ("Shell script");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp172_);
	_tmp173_ = g_strdup ("Ruby");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp173_);
	_tmp174_ = g_strdup ("SQL");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp174_);
	_tmp175_ = g_strdup ("Vala");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp175_);
	_tmp176_ = g_strdup ("Vapi");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp176_);
	_tmp177_ = g_strdup ("VHDL");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp177_);
	_tmp178_ = g_strdup ("XML");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp178_);
	_tmp179_ = g_strdup ("XSLT");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp179_);
	_tmp180_ = g_strdup ("YAAC");
	self->priv->_languages = g_list_append (self->priv->_languages, _tmp180_);
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = needle;
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
	result = _tmp1_ != NULL;
	return result;
}


static gchar* programming_languages_get_file_extension (ProgrammingLanguages* self, const gchar* filename) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gchar** components = NULL;
	const gchar* _tmp3_ = NULL;
	gchar** _tmp4_ = NULL;
	gchar** _tmp5_ = NULL;
	gint components_length1 = 0;
	gint _components_size_ = 0;
	gchar** _tmp6_ = NULL;
	gint _tmp6__length1 = 0;
	gchar** _tmp7_ = NULL;
	gint _tmp7__length1 = 0;
	const gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (filename != NULL, NULL);
	_tmp0_ = filename;
	_tmp1_ = string_contains (_tmp0_, "Makefile");
	if (_tmp1_) {
		gchar* _tmp2_ = NULL;
		_tmp2_ = g_strdup ("Makefile");
		result = _tmp2_;
		return result;
	}
	_tmp3_ = filename;
	_tmp5_ = _tmp4_ = g_strsplit (_tmp3_, ".", 0);
	components = _tmp5_;
	components_length1 = _vala_array_length (_tmp4_);
	_components_size_ = components_length1;
	_tmp6_ = components;
	_tmp6__length1 = components_length1;
	_tmp7_ = components;
	_tmp7__length1 = components_length1;
	_tmp8_ = _tmp6_[_tmp7__length1 - 1];
	_tmp9_ = g_strdup (_tmp8_);
	result = _tmp9_;
	components = (_vala_array_free (components, components_length1, (GDestroyNotify) g_free), NULL);
	return result;
}


gchar* programming_languages_get_lang_id (ProgrammingLanguages* self, const gchar* filename) {
	gchar* result = NULL;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (filename != NULL, NULL);
	_tmp0_ = self->priv->lang_ids;
	_tmp1_ = filename;
	_tmp2_ = programming_languages_get_file_extension (self, _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp3_);
	_tmp5_ = (gchar*) _tmp4_;
	_g_free0 (_tmp3_);
	result = _tmp5_;
	return result;
}


gchar* programming_languages_get_lang_id_from_name (ProgrammingLanguages* self, const gchar* language) {
	gchar* result = NULL;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (language != NULL, NULL);
	_tmp0_ = self->priv->lang_id_names;
	_tmp1_ = language;
	_tmp2_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp1_);
	result = (gchar*) _tmp2_;
	return result;
}


gchar* programming_languages_get_lang_name (ProgrammingLanguages* self, const gchar* filename) {
	gchar* result = NULL;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (filename != NULL, NULL);
	_tmp0_ = self->priv->lang_names;
	_tmp1_ = filename;
	_tmp2_ = programming_languages_get_file_extension (self, _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp3_);
	_tmp5_ = (gchar*) _tmp4_;
	_g_free0 (_tmp3_);
	result = _tmp5_;
	return result;
}


gchar* programming_languages_get_lang_ext (ProgrammingLanguages* self, const gchar* lang_name) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	GeeHashMap* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (lang_name != NULL, NULL);
	_tmp0_ = lang_name;
	if (g_strcmp0 (_tmp0_, "Plain text") == 0) {
		gchar* _tmp1_ = NULL;
		_tmp1_ = g_strdup ("");
		result = _tmp1_;
		return result;
	}
	_tmp2_ = self->priv->lang_ext;
	_tmp3_ = lang_name;
	_tmp4_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp2_, _tmp3_);
	result = (gchar*) _tmp4_;
	return result;
}


gboolean programming_languages_is_buildable (ProgrammingLanguages* self, const gchar* filename) {
	gboolean result = FALSE;
	gchar* l_name = NULL;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (filename != NULL, FALSE);
	_tmp0_ = self->priv->lang_names;
	_tmp1_ = filename;
	_tmp2_ = programming_languages_get_file_extension (self, _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp3_);
	_tmp5_ = (gchar*) _tmp4_;
	_g_free0 (_tmp3_);
	l_name = _tmp5_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp6_ = FALSE;
			_tmp6_ = TRUE;
			while (TRUE) {
				gint _tmp8_ = 0;
				GArray* _tmp9_ = NULL;
				guint _tmp10_ = 0U;
				const gchar* _tmp11_ = NULL;
				GArray* _tmp12_ = NULL;
				gpointer* _tmp13_ = NULL;
				gint _tmp13__length1 = 0;
				gint _tmp14_ = 0;
				const gchar* _tmp15_ = NULL;
				if (!_tmp6_) {
					gint _tmp7_ = 0;
					_tmp7_ = i;
					i = _tmp7_ + 1;
				}
				_tmp6_ = FALSE;
				_tmp8_ = i;
				_tmp9_ = self->priv->buildables;
				_tmp10_ = _tmp9_->len;
				if (!(((guint) _tmp8_) < _tmp10_)) {
					break;
				}
				_tmp11_ = l_name;
				_tmp12_ = self->priv->buildables;
				_tmp13_ = _tmp12_->data;
				_tmp13__length1 = (gint) _tmp12_->len;
				_tmp14_ = i;
				_tmp15_ = _tmp13_[_tmp14_];
				if (g_strcmp0 (_tmp11_, _tmp15_) == 0) {
					result = TRUE;
					_g_free0 (l_name);
					return result;
				}
			}
		}
	}
	result = FALSE;
	_g_free0 (l_name);
	return result;
}


GList* programming_languages_get_languages (ProgrammingLanguages* self) {
	GList* result;
	GList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_languages;
	result = _tmp0_;
	return result;
}


static void value_programming_languages_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_programming_languages_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		programming_languages_unref (value->data[0].v_pointer);
	}
}


static void value_programming_languages_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = programming_languages_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_programming_languages_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_programming_languages_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		ProgrammingLanguages* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = programming_languages_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_programming_languages_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	ProgrammingLanguages** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = programming_languages_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_programming_languages (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecProgrammingLanguages* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_PROGRAMMING_LANGUAGES), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_programming_languages (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PROGRAMMING_LANGUAGES), NULL);
	return value->data[0].v_pointer;
}


void value_set_programming_languages (GValue* value, gpointer v_object) {
	ProgrammingLanguages* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PROGRAMMING_LANGUAGES));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PROGRAMMING_LANGUAGES));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		programming_languages_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		programming_languages_unref (old);
	}
}


void value_take_programming_languages (GValue* value, gpointer v_object) {
	ProgrammingLanguages* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PROGRAMMING_LANGUAGES));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PROGRAMMING_LANGUAGES));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		programming_languages_unref (old);
	}
}


static void programming_languages_class_init (ProgrammingLanguagesClass * klass) {
	programming_languages_parent_class = g_type_class_peek_parent (klass);
	((ProgrammingLanguagesClass *) klass)->finalize = programming_languages_finalize;
	g_type_class_add_private (klass, sizeof (ProgrammingLanguagesPrivate));
}


static void programming_languages_instance_init (ProgrammingLanguages * self) {
	self->priv = PROGRAMMING_LANGUAGES_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void programming_languages_finalize (ProgrammingLanguages* obj) {
	ProgrammingLanguages * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PROGRAMMING_LANGUAGES, ProgrammingLanguages);
	g_signal_handlers_destroy (self);
	_g_object_unref0 (self->priv->lang_ids);
	_g_object_unref0 (self->priv->lang_names);
	_g_object_unref0 (self->priv->lang_id_names);
	_g_object_unref0 (self->priv->lang_ext);
	_g_array_unref0 (self->priv->buildables);
	__g_list_free__g_free0_0 (self->priv->_languages);
}


GType programming_languages_get_type (void) {
	static volatile gsize programming_languages_type_id__volatile = 0;
	if (g_once_init_enter (&programming_languages_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_programming_languages_init, value_programming_languages_free_value, value_programming_languages_copy_value, value_programming_languages_peek_pointer, "p", value_programming_languages_collect_value, "p", value_programming_languages_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ProgrammingLanguagesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) programming_languages_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ProgrammingLanguages), 0, (GInstanceInitFunc) programming_languages_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType programming_languages_type_id;
		programming_languages_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ProgrammingLanguages", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&programming_languages_type_id__volatile, programming_languages_type_id);
	}
	return programming_languages_type_id__volatile;
}


gpointer programming_languages_ref (gpointer instance) {
	ProgrammingLanguages* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void programming_languages_unref (gpointer instance) {
	ProgrammingLanguages* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		PROGRAMMING_LANGUAGES_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



