/* simple-source-view.c generated by valac 0.28.0, the Vala compiler
 * generated from simple-source-view.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtksourceview/gtksource.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <pango/pango.h>
#include <gdk/gdk.h>


#define TYPE_SIMPLE_SOURCE_VIEW (simple_source_view_get_type ())
#define SIMPLE_SOURCE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SIMPLE_SOURCE_VIEW, SimpleSourceView))
#define SIMPLE_SOURCE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SIMPLE_SOURCE_VIEW, SimpleSourceViewClass))
#define IS_SIMPLE_SOURCE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SIMPLE_SOURCE_VIEW))
#define IS_SIMPLE_SOURCE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SIMPLE_SOURCE_VIEW))
#define SIMPLE_SOURCE_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SIMPLE_SOURCE_VIEW, SimpleSourceViewClass))

typedef struct _SimpleSourceView SimpleSourceView;
typedef struct _SimpleSourceViewClass SimpleSourceViewClass;
typedef struct _SimpleSourceViewPrivate SimpleSourceViewPrivate;

#define TYPE_TEXT_EDITOR (text_editor_get_type ())
#define TEXT_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXT_EDITOR, TextEditor))
#define TEXT_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXT_EDITOR, TextEditorClass))
#define IS_TEXT_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXT_EDITOR))
#define IS_TEXT_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXT_EDITOR))
#define TEXT_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXT_EDITOR, TextEditorClass))

typedef struct _TextEditor TextEditor;
typedef struct _TextEditorClass TextEditorClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __vala_PangoFontDescription_free0(var) ((var == NULL) ? NULL : (var = (_vala_PangoFontDescription_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _SimpleSourceView {
	GtkSourceView parent_instance;
	SimpleSourceViewPrivate * priv;
};

struct _SimpleSourceViewClass {
	GtkSourceViewClass parent_class;
};

struct _SimpleSourceViewPrivate {
	TextEditor* editor;
};


static gpointer simple_source_view_parent_class = NULL;

GType simple_source_view_get_type (void) G_GNUC_CONST;
GType text_editor_get_type (void) G_GNUC_CONST;
#define SIMPLE_SOURCE_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SIMPLE_SOURCE_VIEW, SimpleSourceViewPrivate))
enum  {
	SIMPLE_SOURCE_VIEW_DUMMY_PROPERTY
};
#define SIMPLE_SOURCE_VIEW_TARGET_TYPE_URI_LIST 80
SimpleSourceView* simple_source_view_new (TextEditor* editor);
SimpleSourceView* simple_source_view_construct (GType object_type, TextEditor* editor);
const gchar* text_editor_get_color_scheme (TextEditor* self);
static void simple_source_view_connect_signals (SimpleSourceView* self);
static void simple_source_view_set_properties (SimpleSourceView* self);
SimpleSourceView* simple_source_view_new_with_text (TextEditor* editor, const gchar* display_text);
SimpleSourceView* simple_source_view_construct_with_text (GType object_type, TextEditor* editor, const gchar* display_text);
SimpleSourceView* simple_source_view_new_with_language (TextEditor* editor, const gchar* language, const gchar* display_text);
SimpleSourceView* simple_source_view_construct_with_language (GType object_type, TextEditor* editor, const gchar* language, const gchar* display_text);
gboolean text_editor_get_show_line_numbers (TextEditor* self);
gboolean text_editor_get_show_right_margin (TextEditor* self);
gint text_editor_get_right_margin_at (TextEditor* self);
gboolean text_editor_get_highlight_current_line (TextEditor* self);
gboolean text_editor_get_highlight_brackets (TextEditor* self);
gint text_editor_get_tab_width (TextEditor* self);
gboolean text_editor_get_insert_spaces (TextEditor* self);
gboolean text_editor_get_auto_indent (TextEditor* self);
const gchar* text_editor_get_editor_font (TextEditor* self);
static void _vala_PangoFontDescription_free (PangoFontDescription* self);
gboolean text_editor_get_show_grid_pattern (TextEditor* self);
static void simple_source_view_on_drag_data_received (SimpleSourceView* self, GtkWidget* widget, GdkDragContext* context, gint x, gint y, GtkSelectionData* selection_data, guint target_type, guint time);
static void _simple_source_view_on_drag_data_received_gtk_widget_drag_data_received (GtkWidget* _sender, GdkDragContext* context, gint x, gint y, GtkSelectionData* selection_data, guint info, guint time_, gpointer self);
void simple_source_view_change_language (SimpleSourceView* self, const gchar* language);
static void __lambda4_ (SimpleSourceView* self, GParamSpec* pspec);
static void ___lambda4__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda5_ (SimpleSourceView* self, GParamSpec* pspec);
static void ___lambda5__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda6_ (SimpleSourceView* self, GParamSpec* pspec);
static void ___lambda6__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda7_ (SimpleSourceView* self, GParamSpec* pspec);
static void ___lambda7__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda8_ (SimpleSourceView* self, GParamSpec* pspec);
static void ___lambda8__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda9_ (SimpleSourceView* self, GParamSpec* pspec);
static void ___lambda9__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda10_ (SimpleSourceView* self, GParamSpec* pspec);
static void ___lambda10__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda11_ (SimpleSourceView* self, GParamSpec* pspec);
static void ___lambda11__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda12_ (SimpleSourceView* self, GParamSpec* pspec);
static void ___lambda12__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda13_ (SimpleSourceView* self, GParamSpec* pspec);
gboolean text_editor_get_use_default_typo (TextEditor* self);
static void ___lambda13__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda14_ (SimpleSourceView* self, GParamSpec* pspec);
static void ___lambda14__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda15_ (SimpleSourceView* self, GParamSpec* pspec);
static void ___lambda15__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static gchar* simple_source_view_get_file_path_from_uri (SimpleSourceView* self, const gchar* uri);
static void simple_source_view_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);

static const GtkTargetEntry SIMPLE_SOURCE_VIEW_target_list[1] = {{"text/uri-list", (guint) 0, (guint) SIMPLE_SOURCE_VIEW_TARGET_TYPE_URI_LIST}};

static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


SimpleSourceView* simple_source_view_construct (GType object_type, TextEditor* editor) {
	SimpleSourceView * self = NULL;
	GtkSourceBuffer* buff = NULL;
	GtkSourceBuffer* _tmp0_ = NULL;
	GtkSourceStyleSchemeManager* scheme_manager = NULL;
	GtkSourceStyleSchemeManager* _tmp1_ = NULL;
	GtkSourceStyleSchemeManager* _tmp2_ = NULL;
	GtkSourceStyleScheme* source_scheme = NULL;
	TextEditor* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	GtkSourceStyleScheme* _tmp6_ = NULL;
	GtkSourceStyleScheme* _tmp7_ = NULL;
	TextEditor* _tmp8_ = NULL;
	TextEditor* _tmp9_ = NULL;
	g_return_val_if_fail (editor != NULL, NULL);
	_tmp0_ = gtk_source_buffer_new (NULL);
	buff = _tmp0_;
	_tmp1_ = gtk_source_style_scheme_manager_get_default ();
	_tmp2_ = _g_object_ref0 (_tmp1_);
	scheme_manager = _tmp2_;
	_tmp3_ = editor;
	_tmp4_ = text_editor_get_color_scheme (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = gtk_source_style_scheme_manager_get_scheme (scheme_manager, _tmp5_);
	_tmp7_ = _g_object_ref0 (_tmp6_);
	source_scheme = _tmp7_;
	gtk_source_buffer_set_style_scheme (buff, source_scheme);
	self = (SimpleSourceView*) g_object_new (object_type, "buffer", buff, NULL);
	_tmp8_ = editor;
	_tmp9_ = _g_object_ref0 (_tmp8_);
	_g_object_unref0 (self->priv->editor);
	self->priv->editor = _tmp9_;
	simple_source_view_connect_signals (self);
	simple_source_view_set_properties (self);
	gtk_text_buffer_set_modified ((GtkTextBuffer*) buff, FALSE);
	_g_object_unref0 (source_scheme);
	_g_object_unref0 (scheme_manager);
	_g_object_unref0 (buff);
	return self;
}


SimpleSourceView* simple_source_view_new (TextEditor* editor) {
	return simple_source_view_construct (TYPE_SIMPLE_SOURCE_VIEW, editor);
}


SimpleSourceView* simple_source_view_construct_with_text (GType object_type, TextEditor* editor, const gchar* display_text) {
	SimpleSourceView * self = NULL;
	GtkSourceBuffer* buff = NULL;
	GtkSourceBuffer* _tmp0_ = NULL;
	GtkSourceStyleSchemeManager* scheme_manager = NULL;
	GtkSourceStyleSchemeManager* _tmp1_ = NULL;
	GtkSourceStyleSchemeManager* _tmp2_ = NULL;
	GtkSourceStyleScheme* source_scheme = NULL;
	TextEditor* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	GtkSourceStyleScheme* _tmp6_ = NULL;
	GtkSourceStyleScheme* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	TextEditor* _tmp9_ = NULL;
	TextEditor* _tmp10_ = NULL;
	g_return_val_if_fail (editor != NULL, NULL);
	g_return_val_if_fail (display_text != NULL, NULL);
	_tmp0_ = gtk_source_buffer_new (NULL);
	buff = _tmp0_;
	_tmp1_ = gtk_source_style_scheme_manager_get_default ();
	_tmp2_ = _g_object_ref0 (_tmp1_);
	scheme_manager = _tmp2_;
	_tmp3_ = editor;
	_tmp4_ = text_editor_get_color_scheme (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = gtk_source_style_scheme_manager_get_scheme (scheme_manager, _tmp5_);
	_tmp7_ = _g_object_ref0 (_tmp6_);
	source_scheme = _tmp7_;
	gtk_source_buffer_set_style_scheme (buff, source_scheme);
	gtk_source_buffer_begin_not_undoable_action (buff);
	_tmp8_ = display_text;
	g_object_set ((GtkTextBuffer*) buff, "text", _tmp8_, NULL);
	gtk_source_buffer_end_not_undoable_action (buff);
	self = (SimpleSourceView*) g_object_new (object_type, "buffer", buff, NULL);
	_tmp9_ = editor;
	_tmp10_ = _g_object_ref0 (_tmp9_);
	_g_object_unref0 (self->priv->editor);
	self->priv->editor = _tmp10_;
	simple_source_view_connect_signals (self);
	simple_source_view_set_properties (self);
	gtk_text_buffer_set_modified ((GtkTextBuffer*) buff, FALSE);
	_g_object_unref0 (source_scheme);
	_g_object_unref0 (scheme_manager);
	_g_object_unref0 (buff);
	return self;
}


SimpleSourceView* simple_source_view_new_with_text (TextEditor* editor, const gchar* display_text) {
	return simple_source_view_construct_with_text (TYPE_SIMPLE_SOURCE_VIEW, editor, display_text);
}


SimpleSourceView* simple_source_view_construct_with_language (GType object_type, TextEditor* editor, const gchar* language, const gchar* display_text) {
	SimpleSourceView * self = NULL;
	GtkSourceLanguageManager* lang_manager = NULL;
	GtkSourceLanguageManager* _tmp0_ = NULL;
	GtkSourceLanguageManager* _tmp1_ = NULL;
	GtkSourceLanguage* source_lang = NULL;
	const gchar* _tmp2_ = NULL;
	GtkSourceLanguage* _tmp3_ = NULL;
	GtkSourceLanguage* _tmp4_ = NULL;
	GtkSourceBuffer* buff = NULL;
	GtkSourceBuffer* _tmp5_ = NULL;
	GtkSourceStyleSchemeManager* scheme_manager = NULL;
	GtkSourceStyleSchemeManager* _tmp6_ = NULL;
	GtkSourceStyleSchemeManager* _tmp7_ = NULL;
	GtkSourceStyleScheme* source_scheme = NULL;
	TextEditor* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	GtkSourceStyleScheme* _tmp11_ = NULL;
	GtkSourceStyleScheme* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	TextEditor* _tmp14_ = NULL;
	TextEditor* _tmp15_ = NULL;
	g_return_val_if_fail (editor != NULL, NULL);
	g_return_val_if_fail (language != NULL, NULL);
	g_return_val_if_fail (display_text != NULL, NULL);
	_tmp0_ = gtk_source_language_manager_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	lang_manager = _tmp1_;
	_tmp2_ = language;
	_tmp3_ = gtk_source_language_manager_get_language (lang_manager, _tmp2_);
	_tmp4_ = _g_object_ref0 (_tmp3_);
	source_lang = _tmp4_;
	_tmp5_ = gtk_source_buffer_new_with_language (source_lang);
	buff = _tmp5_;
	_tmp6_ = gtk_source_style_scheme_manager_get_default ();
	_tmp7_ = _g_object_ref0 (_tmp6_);
	scheme_manager = _tmp7_;
	_tmp8_ = editor;
	_tmp9_ = text_editor_get_color_scheme (_tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = gtk_source_style_scheme_manager_get_scheme (scheme_manager, _tmp10_);
	_tmp12_ = _g_object_ref0 (_tmp11_);
	source_scheme = _tmp12_;
	gtk_source_buffer_set_style_scheme (buff, source_scheme);
	gtk_source_buffer_set_highlight_syntax (buff, TRUE);
	gtk_source_buffer_begin_not_undoable_action (buff);
	_tmp13_ = display_text;
	g_object_set ((GtkTextBuffer*) buff, "text", _tmp13_, NULL);
	gtk_source_buffer_end_not_undoable_action (buff);
	self = (SimpleSourceView*) g_object_new (object_type, "buffer", buff, NULL);
	_tmp14_ = editor;
	_tmp15_ = _g_object_ref0 (_tmp14_);
	_g_object_unref0 (self->priv->editor);
	self->priv->editor = _tmp15_;
	simple_source_view_connect_signals (self);
	simple_source_view_set_properties (self);
	gtk_text_buffer_set_modified ((GtkTextBuffer*) buff, FALSE);
	_g_object_unref0 (source_scheme);
	_g_object_unref0 (scheme_manager);
	_g_object_unref0 (buff);
	_g_object_unref0 (source_lang);
	_g_object_unref0 (lang_manager);
	return self;
}


SimpleSourceView* simple_source_view_new_with_language (TextEditor* editor, const gchar* language, const gchar* display_text) {
	return simple_source_view_construct_with_language (TYPE_SIMPLE_SOURCE_VIEW, editor, language, display_text);
}


static void _vala_PangoFontDescription_free (PangoFontDescription* self) {
	g_boxed_free (pango_font_description_get_type (), self);
}


static void _simple_source_view_on_drag_data_received_gtk_widget_drag_data_received (GtkWidget* _sender, GdkDragContext* context, gint x, gint y, GtkSelectionData* selection_data, guint info, guint time_, gpointer self) {
	simple_source_view_on_drag_data_received ((SimpleSourceView*) self, _sender, context, x, y, selection_data, info, time_);
}


static void simple_source_view_set_properties (SimpleSourceView* self) {
	TextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	TextEditor* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp5_ = FALSE;
	TextEditor* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	TextEditor* _tmp9_ = NULL;
	gboolean _tmp10_ = FALSE;
	gboolean _tmp11_ = FALSE;
	GtkTextBuffer* _tmp12_ = NULL;
	GtkTextBuffer* _tmp13_ = NULL;
	TextEditor* _tmp14_ = NULL;
	gboolean _tmp15_ = FALSE;
	gboolean _tmp16_ = FALSE;
	TextEditor* _tmp17_ = NULL;
	gint _tmp18_ = 0;
	gint _tmp19_ = 0;
	TextEditor* _tmp20_ = NULL;
	gboolean _tmp21_ = FALSE;
	gboolean _tmp22_ = FALSE;
	TextEditor* _tmp23_ = NULL;
	gboolean _tmp24_ = FALSE;
	gboolean _tmp25_ = FALSE;
	TextEditor* _tmp26_ = NULL;
	const gchar* _tmp27_ = NULL;
	const gchar* _tmp28_ = NULL;
	PangoFontDescription* _tmp29_ = NULL;
	PangoFontDescription* _tmp30_ = NULL;
	TextEditor* _tmp31_ = NULL;
	gboolean _tmp32_ = FALSE;
	gboolean _tmp33_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = text_editor_get_show_line_numbers (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_show_line_numbers ((GtkSourceView*) self, _tmp2_);
	_tmp3_ = self->priv->editor;
	_tmp4_ = text_editor_get_show_right_margin (_tmp3_);
	_tmp5_ = _tmp4_;
	gtk_source_view_set_show_right_margin ((GtkSourceView*) self, _tmp5_);
	_tmp6_ = self->priv->editor;
	_tmp7_ = text_editor_get_right_margin_at (_tmp6_);
	_tmp8_ = _tmp7_;
	gtk_source_view_set_right_margin_position ((GtkSourceView*) self, (guint) _tmp8_);
	_tmp9_ = self->priv->editor;
	_tmp10_ = text_editor_get_highlight_current_line (_tmp9_);
	_tmp11_ = _tmp10_;
	gtk_source_view_set_highlight_current_line ((GtkSourceView*) self, _tmp11_);
	_tmp12_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp13_ = _tmp12_;
	_tmp14_ = self->priv->editor;
	_tmp15_ = text_editor_get_highlight_brackets (_tmp14_);
	_tmp16_ = _tmp15_;
	gtk_source_buffer_set_highlight_matching_brackets (G_TYPE_CHECK_INSTANCE_TYPE (_tmp13_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp13_) : NULL, _tmp16_);
	_tmp17_ = self->priv->editor;
	_tmp18_ = text_editor_get_tab_width (_tmp17_);
	_tmp19_ = _tmp18_;
	gtk_source_view_set_tab_width ((GtkSourceView*) self, (guint) _tmp19_);
	_tmp20_ = self->priv->editor;
	_tmp21_ = text_editor_get_insert_spaces (_tmp20_);
	_tmp22_ = _tmp21_;
	gtk_source_view_set_insert_spaces_instead_of_tabs ((GtkSourceView*) self, _tmp22_);
	_tmp23_ = self->priv->editor;
	_tmp24_ = text_editor_get_auto_indent (_tmp23_);
	_tmp25_ = _tmp24_;
	gtk_source_view_set_auto_indent ((GtkSourceView*) self, _tmp25_);
	_tmp26_ = self->priv->editor;
	_tmp27_ = text_editor_get_editor_font (_tmp26_);
	_tmp28_ = _tmp27_;
	_tmp29_ = pango_font_description_from_string (_tmp28_);
	_tmp30_ = _tmp29_;
	gtk_widget_override_font ((GtkWidget*) self, _tmp30_);
	__vala_PangoFontDescription_free0 (_tmp30_);
	_tmp31_ = self->priv->editor;
	_tmp32_ = text_editor_get_show_grid_pattern (_tmp31_);
	_tmp33_ = _tmp32_;
	if (_tmp33_) {
		gtk_source_view_set_background_pattern ((GtkSourceView*) self, GTK_SOURCE_BACKGROUND_PATTERN_TYPE_GRID);
	} else {
		gtk_source_view_set_background_pattern ((GtkSourceView*) self, GTK_SOURCE_BACKGROUND_PATTERN_TYPE_NONE);
	}
	gtk_source_view_set_smart_home_end ((GtkSourceView*) self, GTK_SOURCE_SMART_HOME_END_BEFORE);
	gtk_text_view_set_wrap_mode ((GtkTextView*) self, GTK_WRAP_NONE);
	gtk_drag_dest_set ((GtkWidget*) self, (GTK_DEST_DEFAULT_MOTION | GTK_DEST_DEFAULT_HIGHLIGHT) | GTK_DEST_DEFAULT_DROP, SIMPLE_SOURCE_VIEW_target_list, G_N_ELEMENTS (SIMPLE_SOURCE_VIEW_target_list), GDK_ACTION_COPY);
	g_signal_connect_object ((GtkWidget*) self, "drag-data-received", (GCallback) _simple_source_view_on_drag_data_received_gtk_widget_drag_data_received, self, 0);
}


void simple_source_view_change_language (SimpleSourceView* self, const gchar* language) {
	GtkSourceLanguageManager* lang_manager = NULL;
	GtkSourceLanguageManager* _tmp0_ = NULL;
	GtkSourceLanguageManager* _tmp1_ = NULL;
	GtkSourceLanguage* source_lang = NULL;
	const gchar* _tmp2_ = NULL;
	GtkSourceLanguage* _tmp3_ = NULL;
	GtkSourceLanguage* _tmp4_ = NULL;
	GtkSourceBuffer* buff = NULL;
	GtkSourceBuffer* _tmp5_ = NULL;
	GtkSourceStyleSchemeManager* scheme_manager = NULL;
	GtkSourceStyleSchemeManager* _tmp6_ = NULL;
	GtkSourceStyleSchemeManager* _tmp7_ = NULL;
	GtkSourceStyleScheme* source_scheme = NULL;
	TextEditor* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	GtkSourceStyleScheme* _tmp11_ = NULL;
	GtkSourceStyleScheme* _tmp12_ = NULL;
	TextEditor* _tmp13_ = NULL;
	gboolean _tmp14_ = FALSE;
	gboolean _tmp15_ = FALSE;
	GtkTextBuffer* _tmp16_ = NULL;
	GtkTextBuffer* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (language != NULL);
	_tmp0_ = gtk_source_language_manager_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	lang_manager = _tmp1_;
	_tmp2_ = language;
	_tmp3_ = gtk_source_language_manager_get_language (lang_manager, _tmp2_);
	_tmp4_ = _g_object_ref0 (_tmp3_);
	source_lang = _tmp4_;
	_tmp5_ = gtk_source_buffer_new_with_language (source_lang);
	buff = _tmp5_;
	_tmp6_ = gtk_source_style_scheme_manager_get_default ();
	_tmp7_ = _g_object_ref0 (_tmp6_);
	scheme_manager = _tmp7_;
	_tmp8_ = self->priv->editor;
	_tmp9_ = text_editor_get_color_scheme (_tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = gtk_source_style_scheme_manager_get_scheme (scheme_manager, _tmp10_);
	_tmp12_ = _g_object_ref0 (_tmp11_);
	source_scheme = _tmp12_;
	_tmp13_ = self->priv->editor;
	_tmp14_ = text_editor_get_highlight_brackets (_tmp13_);
	_tmp15_ = _tmp14_;
	gtk_source_buffer_set_highlight_matching_brackets (buff, _tmp15_);
	gtk_source_buffer_set_style_scheme (buff, source_scheme);
	gtk_source_buffer_set_highlight_syntax (buff, TRUE);
	gtk_source_buffer_begin_not_undoable_action (buff);
	_tmp16_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp17_ = _tmp16_;
	g_object_get (_tmp17_, "text", &_tmp18_, NULL);
	_tmp19_ = _tmp18_;
	_tmp20_ = _tmp19_;
	g_object_set ((GtkTextBuffer*) buff, "text", _tmp20_, NULL);
	_g_free0 (_tmp20_);
	gtk_source_buffer_end_not_undoable_action (buff);
	gtk_text_view_set_buffer ((GtkTextView*) self, (GtkTextBuffer*) buff);
	simple_source_view_set_properties (self);
	gtk_text_buffer_set_modified ((GtkTextBuffer*) buff, FALSE);
	_g_object_unref0 (source_scheme);
	_g_object_unref0 (scheme_manager);
	_g_object_unref0 (buff);
	_g_object_unref0 (source_lang);
	_g_object_unref0 (lang_manager);
}


static void __lambda4_ (SimpleSourceView* self, GParamSpec* pspec) {
	TextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = text_editor_get_show_line_numbers (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_show_line_numbers ((GtkSourceView*) self, _tmp2_);
}


static void ___lambda4__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda4_ ((SimpleSourceView*) self, pspec);
}


static void __lambda5_ (SimpleSourceView* self, GParamSpec* pspec) {
	TextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = text_editor_get_show_right_margin (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_show_right_margin ((GtkSourceView*) self, _tmp2_);
}


static void ___lambda5__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda5_ ((SimpleSourceView*) self, pspec);
}


static void __lambda6_ (SimpleSourceView* self, GParamSpec* pspec) {
	TextEditor* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = text_editor_get_right_margin_at (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_right_margin_position ((GtkSourceView*) self, (guint) _tmp2_);
}


static void ___lambda6__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda6_ ((SimpleSourceView*) self, pspec);
}


static void __lambda7_ (SimpleSourceView* self, GParamSpec* pspec) {
	TextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = text_editor_get_highlight_current_line (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_highlight_current_line ((GtkSourceView*) self, _tmp2_);
}


static void ___lambda7__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda7_ ((SimpleSourceView*) self, pspec);
}


static void __lambda8_ (SimpleSourceView* self, GParamSpec* pspec) {
	GtkTextBuffer* _tmp0_ = NULL;
	GtkTextBuffer* _tmp1_ = NULL;
	TextEditor* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = self->priv->editor;
	_tmp3_ = text_editor_get_highlight_brackets (_tmp2_);
	_tmp4_ = _tmp3_;
	gtk_source_buffer_set_highlight_matching_brackets (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp1_) : NULL, _tmp4_);
}


static void ___lambda8__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda8_ ((SimpleSourceView*) self, pspec);
}


static void __lambda9_ (SimpleSourceView* self, GParamSpec* pspec) {
	TextEditor* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = text_editor_get_tab_width (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_tab_width ((GtkSourceView*) self, (guint) _tmp2_);
}


static void ___lambda9__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda9_ ((SimpleSourceView*) self, pspec);
}


static void __lambda10_ (SimpleSourceView* self, GParamSpec* pspec) {
	TextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = text_editor_get_insert_spaces (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_insert_spaces_instead_of_tabs ((GtkSourceView*) self, _tmp2_);
}


static void ___lambda10__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda10_ ((SimpleSourceView*) self, pspec);
}


static void __lambda11_ (SimpleSourceView* self, GParamSpec* pspec) {
	TextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = text_editor_get_auto_indent (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_auto_indent ((GtkSourceView*) self, _tmp2_);
}


static void ___lambda11__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda11_ ((SimpleSourceView*) self, pspec);
}


static void __lambda12_ (SimpleSourceView* self, GParamSpec* pspec) {
	TextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = text_editor_get_show_grid_pattern (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		gtk_source_view_set_background_pattern ((GtkSourceView*) self, GTK_SOURCE_BACKGROUND_PATTERN_TYPE_GRID);
	} else {
		gtk_source_view_set_background_pattern ((GtkSourceView*) self, GTK_SOURCE_BACKGROUND_PATTERN_TYPE_NONE);
	}
}


static void ___lambda12__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda12_ ((SimpleSourceView*) self, pspec);
}


static void __lambda13_ (SimpleSourceView* self, GParamSpec* pspec) {
	TextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = text_editor_get_use_default_typo (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		PangoFontDescription* _tmp3_ = NULL;
		PangoFontDescription* _tmp4_ = NULL;
		_tmp3_ = pango_font_description_from_string ("Monospace 10");
		_tmp4_ = _tmp3_;
		gtk_widget_override_font ((GtkWidget*) self, _tmp4_);
		__vala_PangoFontDescription_free0 (_tmp4_);
	} else {
		TextEditor* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		PangoFontDescription* _tmp8_ = NULL;
		PangoFontDescription* _tmp9_ = NULL;
		_tmp5_ = self->priv->editor;
		_tmp6_ = text_editor_get_editor_font (_tmp5_);
		_tmp7_ = _tmp6_;
		_tmp8_ = pango_font_description_from_string (_tmp7_);
		_tmp9_ = _tmp8_;
		gtk_widget_override_font ((GtkWidget*) self, _tmp9_);
		__vala_PangoFontDescription_free0 (_tmp9_);
	}
}


static void ___lambda13__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda13_ ((SimpleSourceView*) self, pspec);
}


static void __lambda14_ (SimpleSourceView* self, GParamSpec* pspec) {
	TextEditor* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	PangoFontDescription* _tmp3_ = NULL;
	PangoFontDescription* _tmp4_ = NULL;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = text_editor_get_editor_font (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = pango_font_description_from_string (_tmp2_);
	_tmp4_ = _tmp3_;
	gtk_widget_override_font ((GtkWidget*) self, _tmp4_);
	__vala_PangoFontDescription_free0 (_tmp4_);
}


static void ___lambda14__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda14_ ((SimpleSourceView*) self, pspec);
}


static void __lambda15_ (SimpleSourceView* self, GParamSpec* pspec) {
	GtkSourceStyleSchemeManager* scheme_manager = NULL;
	GtkSourceStyleSchemeManager* _tmp0_ = NULL;
	GtkSourceStyleSchemeManager* _tmp1_ = NULL;
	GtkSourceStyleScheme* source_scheme = NULL;
	TextEditor* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	GtkSourceStyleScheme* _tmp5_ = NULL;
	GtkSourceStyleScheme* _tmp6_ = NULL;
	GtkTextBuffer* _tmp7_ = NULL;
	GtkTextBuffer* _tmp8_ = NULL;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = gtk_source_style_scheme_manager_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	scheme_manager = _tmp1_;
	_tmp2_ = self->priv->editor;
	_tmp3_ = text_editor_get_color_scheme (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = gtk_source_style_scheme_manager_get_scheme (scheme_manager, _tmp4_);
	_tmp6_ = _g_object_ref0 (_tmp5_);
	source_scheme = _tmp6_;
	_tmp7_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp8_ = _tmp7_;
	gtk_source_buffer_set_style_scheme (G_TYPE_CHECK_INSTANCE_TYPE (_tmp8_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp8_) : NULL, source_scheme);
	_g_object_unref0 (source_scheme);
	_g_object_unref0 (scheme_manager);
}


static void ___lambda15__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda15_ ((SimpleSourceView*) self, pspec);
}


static void simple_source_view_connect_signals (SimpleSourceView* self) {
	TextEditor* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	TextEditor* _tmp2_ = NULL;
	TextEditor* _tmp3_ = NULL;
	TextEditor* _tmp4_ = NULL;
	TextEditor* _tmp5_ = NULL;
	TextEditor* _tmp6_ = NULL;
	TextEditor* _tmp7_ = NULL;
	TextEditor* _tmp8_ = NULL;
	TextEditor* _tmp9_ = NULL;
	TextEditor* _tmp10_ = NULL;
	TextEditor* _tmp11_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp0_, "notify::show-line-numbers", (GCallback) ___lambda4__g_object_notify, self, 0);
	_tmp1_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp1_, "notify::show-right-margin", (GCallback) ___lambda5__g_object_notify, self, 0);
	_tmp2_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp2_, "notify::right-margin-at", (GCallback) ___lambda6__g_object_notify, self, 0);
	_tmp3_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp3_, "notify::highlight-current-line", (GCallback) ___lambda7__g_object_notify, self, 0);
	_tmp4_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp4_, "notify::highlight-brackets", (GCallback) ___lambda8__g_object_notify, self, 0);
	_tmp5_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp5_, "notify::tab-width", (GCallback) ___lambda9__g_object_notify, self, 0);
	_tmp6_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp6_, "notify::insert-spaces", (GCallback) ___lambda10__g_object_notify, self, 0);
	_tmp7_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp7_, "notify::auto-indent", (GCallback) ___lambda11__g_object_notify, self, 0);
	_tmp8_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp8_, "notify::show-grid-pattern", (GCallback) ___lambda12__g_object_notify, self, 0);
	_tmp9_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp9_, "notify::use-default-typo", (GCallback) ___lambda13__g_object_notify, self, 0);
	_tmp10_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp10_, "notify::editor-font", (GCallback) ___lambda14__g_object_notify, self, 0);
	_tmp11_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp11_, "notify::color-scheme", (GCallback) ___lambda15__g_object_notify, self, 0);
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}


static void simple_source_view_on_drag_data_received (SimpleSourceView* self, GtkWidget* widget, GdkDragContext* context, gint x, gint y, GtkSelectionData* selection_data, guint target_type, guint time) {
	guint _tmp0_ = 0U;
	g_return_if_fail (self != NULL);
	g_return_if_fail (widget != NULL);
	g_return_if_fail (context != NULL);
	g_return_if_fail (selection_data != NULL);
	_tmp0_ = target_type;
	if (_tmp0_ == ((guint) SIMPLE_SOURCE_VIEW_TARGET_TYPE_URI_LIST)) {
		gchar* uri_list = NULL;
		GtkSelectionData* _tmp1_ = NULL;
		guchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		gchar** uris = NULL;
		const gchar* _tmp4_ = NULL;
		gchar** _tmp5_ = NULL;
		gchar** _tmp6_ = NULL;
		gint uris_length1 = 0;
		gint _uris_size_ = 0;
		gchar** _tmp7_ = NULL;
		gint _tmp7__length1 = 0;
		_tmp1_ = selection_data;
		_tmp2_ = gtk_selection_data_get_data (_tmp1_);
		_tmp3_ = string_strip ((const gchar*) _tmp2_);
		uri_list = _tmp3_;
		_tmp4_ = uri_list;
		_tmp6_ = _tmp5_ = g_strsplit (_tmp4_, "\n", 0);
		uris = _tmp6_;
		uris_length1 = _vala_array_length (_tmp5_);
		_uris_size_ = uris_length1;
		_tmp7_ = uris;
		_tmp7__length1 = uris_length1;
		{
			gchar** uri_collection = NULL;
			gint uri_collection_length1 = 0;
			gint _uri_collection_size_ = 0;
			gint uri_it = 0;
			uri_collection = _tmp7_;
			uri_collection_length1 = _tmp7__length1;
			for (uri_it = 0; uri_it < _tmp7__length1; uri_it = uri_it + 1) {
				gchar* _tmp8_ = NULL;
				gchar* uri = NULL;
				_tmp8_ = g_strdup (uri_collection[uri_it]);
				uri = _tmp8_;
				{
					gchar* path = NULL;
					const gchar* _tmp9_ = NULL;
					gchar* _tmp10_ = NULL;
					const gchar* _tmp11_ = NULL;
					_tmp9_ = uri;
					_tmp10_ = simple_source_view_get_file_path_from_uri (self, _tmp9_);
					path = _tmp10_;
					_tmp11_ = path;
					g_signal_emit_by_name (self, "drag-n-drop", _tmp11_);
					_g_free0 (path);
					_g_free0 (uri);
				}
			}
		}
		uris = (_vala_array_free (uris, uris_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (uri_list);
	}
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


static gchar* simple_source_view_get_file_path_from_uri (SimpleSourceView* self, const gchar* uri) {
	gchar* result = NULL;
	gchar* path = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	const gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (uri != NULL, NULL);
	_tmp0_ = g_strdup ("");
	path = _tmp0_;
	_tmp1_ = uri;
	_tmp2_ = g_str_has_prefix (_tmp1_, "file://");
	if (_tmp2_) {
		const gchar* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		gchar* _tmp6_ = NULL;
		_tmp3_ = uri;
		_tmp4_ = strlen ("file://");
		_tmp5_ = _tmp4_;
		_tmp6_ = string_substring (_tmp3_, (glong) _tmp5_, (glong) (-1));
		_g_free0 (path);
		path = _tmp6_;
	} else {
		const gchar* _tmp7_ = NULL;
		gboolean _tmp8_ = FALSE;
		_tmp7_ = uri;
		_tmp8_ = g_str_has_prefix (_tmp7_, "file:");
		if (_tmp8_) {
			const gchar* _tmp9_ = NULL;
			gint _tmp10_ = 0;
			gint _tmp11_ = 0;
			gchar* _tmp12_ = NULL;
			_tmp9_ = uri;
			_tmp10_ = strlen ("file:");
			_tmp11_ = _tmp10_;
			_tmp12_ = string_substring (_tmp9_, (glong) _tmp11_, (glong) (-1));
			_g_free0 (path);
			path = _tmp12_;
		}
	}
	_tmp13_ = path;
	_tmp14_ = string_strip (_tmp13_);
	_g_free0 (path);
	path = _tmp14_;
	result = path;
	return result;
}


static void simple_source_view_class_init (SimpleSourceViewClass * klass) {
	simple_source_view_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SimpleSourceViewPrivate));
	G_OBJECT_CLASS (klass)->finalize = simple_source_view_finalize;
	g_signal_new ("drag_n_drop", TYPE_SIMPLE_SOURCE_VIEW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
}


static void simple_source_view_instance_init (SimpleSourceView * self) {
	self->priv = SIMPLE_SOURCE_VIEW_GET_PRIVATE (self);
}


static void simple_source_view_finalize (GObject* obj) {
	SimpleSourceView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SIMPLE_SOURCE_VIEW, SimpleSourceView);
	_g_object_unref0 (self->priv->editor);
	G_OBJECT_CLASS (simple_source_view_parent_class)->finalize (obj);
}


GType simple_source_view_get_type (void) {
	static volatile gsize simple_source_view_type_id__volatile = 0;
	if (g_once_init_enter (&simple_source_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SimpleSourceViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) simple_source_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SimpleSourceView), 0, (GInstanceInitFunc) simple_source_view_instance_init, NULL };
		GType simple_source_view_type_id;
		simple_source_view_type_id = g_type_register_static (gtk_source_view_get_type (), "SimpleSourceView", &g_define_type_info, 0);
		g_once_init_leave (&simple_source_view_type_id__volatile, simple_source_view_type_id);
	}
	return simple_source_view_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



