/* simple-header-bar.c generated by valac 0.28.0, the Vala compiler
 * generated from simple-header-bar.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>


#define TYPE_SIMPLE_HEADER_BAR (simple_header_bar_get_type ())
#define SIMPLE_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SIMPLE_HEADER_BAR, SimpleHeaderBar))
#define SIMPLE_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SIMPLE_HEADER_BAR, SimpleHeaderBarClass))
#define IS_SIMPLE_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SIMPLE_HEADER_BAR))
#define IS_SIMPLE_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SIMPLE_HEADER_BAR))
#define SIMPLE_HEADER_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SIMPLE_HEADER_BAR, SimpleHeaderBarClass))

typedef struct _SimpleHeaderBar SimpleHeaderBar;
typedef struct _SimpleHeaderBarClass SimpleHeaderBarClass;
typedef struct _SimpleHeaderBarPrivate SimpleHeaderBarPrivate;

#define TYPE_MAIN_WINDOW (main_window_get_type ())
#define MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_WINDOW, MainWindow))
#define MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_WINDOW, MainWindowClass))
#define IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_WINDOW))
#define IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_WINDOW))
#define MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_WINDOW, MainWindowClass))

typedef struct _MainWindow MainWindow;
typedef struct _MainWindowClass MainWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _SimpleHeaderBar {
	GtkHeaderBar parent_instance;
	SimpleHeaderBarPrivate * priv;
};

struct _SimpleHeaderBarClass {
	GtkHeaderBarClass parent_class;
};

struct _SimpleHeaderBarPrivate {
	MainWindow* parent_window;
	GtkMenuButton* menu_b;
	GtkButton* abrir;
	GtkButton* guardar;
	GtkButton* nuevo;
	GtkButton* build;
	gboolean _buildable;
};


static gpointer simple_header_bar_parent_class = NULL;

GType simple_header_bar_get_type (void) G_GNUC_CONST;
GType main_window_get_type (void) G_GNUC_CONST;
#define SIMPLE_HEADER_BAR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SIMPLE_HEADER_BAR, SimpleHeaderBarPrivate))
enum  {
	SIMPLE_HEADER_BAR_DUMMY_PROPERTY,
	SIMPLE_HEADER_BAR_BUILDABLE
};
SimpleHeaderBar* simple_header_bar_new (MainWindow* parent);
SimpleHeaderBar* simple_header_bar_construct (GType object_type, MainWindow* parent);
static void simple_header_bar_create_widgets (SimpleHeaderBar* self);
static void simple_header_bar_connect_signals (SimpleHeaderBar* self);
void simple_header_bar_set_buildable (SimpleHeaderBar* self, gboolean value);
void main_window_open_file_cb (MainWindow* self);
static void _main_window_open_file_cb_gtk_button_clicked (GtkButton* _sender, gpointer self);
void main_window_save_tab_to_file (MainWindow* self);
static void _main_window_save_tab_to_file_gtk_button_clicked (GtkButton* _sender, gpointer self);
void main_window_new_tab_cb (MainWindow* self);
static void _main_window_new_tab_cb_gtk_button_clicked (GtkButton* _sender, gpointer self);
void main_window_build_code (MainWindow* self);
static void _main_window_build_code_gtk_button_clicked (GtkButton* _sender, gpointer self);
gboolean simple_header_bar_get_buildable (SimpleHeaderBar* self);
static void simple_header_bar_finalize (GObject* obj);
static void _vala_simple_header_bar_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_simple_header_bar_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


SimpleHeaderBar* simple_header_bar_construct (GType object_type, MainWindow* parent) {
	SimpleHeaderBar * self = NULL;
	MainWindow* _tmp0_ = NULL;
	MainWindow* _tmp1_ = NULL;
	g_return_val_if_fail (parent != NULL, NULL);
	self = (SimpleHeaderBar*) g_object_new (object_type, NULL);
	_tmp0_ = parent;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->parent_window);
	self->priv->parent_window = _tmp1_;
	gtk_header_bar_set_show_close_button ((GtkHeaderBar*) self, TRUE);
	simple_header_bar_create_widgets (self);
	simple_header_bar_connect_signals (self);
	return self;
}


SimpleHeaderBar* simple_header_bar_new (MainWindow* parent) {
	return simple_header_bar_construct (TYPE_SIMPLE_HEADER_BAR, parent);
}


static void simple_header_bar_create_widgets (SimpleHeaderBar* self) {
	GtkBuilder* builder = NULL;
	GtkBuilder* _tmp0_ = NULL;
	GtkMenuButton* _tmp2_ = NULL;
	GtkMenuButton* _tmp3_ = NULL;
	GtkMenuButton* _tmp4_ = NULL;
	GObject* _tmp5_ = NULL;
	GtkMenuButton* _tmp6_ = NULL;
	GtkMenuButton* _tmp7_ = NULL;
	GtkMenuButton* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	GtkButton* _tmp10_ = NULL;
	GtkButton* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	GtkButton* _tmp15_ = NULL;
	const gchar* _tmp16_ = NULL;
	GtkButton* _tmp17_ = NULL;
	GtkButton* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	GtkButton* _tmp22_ = NULL;
	GtkButton* _tmp23_ = NULL;
	GtkButton* _tmp24_ = NULL;
	const gchar* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	GtkButton* _tmp28_ = NULL;
	GtkButton* _tmp29_ = NULL;
	GtkButton* _tmp30_ = NULL;
	const gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	gchar* _tmp33_ = NULL;
	GtkButton* _tmp34_ = NULL;
	GtkButton* _tmp35_ = NULL;
	GtkButton* _tmp36_ = NULL;
	GtkMenuButton* _tmp37_ = NULL;
	GtkButton* _tmp38_ = NULL;
	GtkButton* _tmp39_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_builder_new ();
	builder = _tmp0_;
	{
		gtk_builder_add_from_resource (builder, "/com/github/badwolfie/simple-text/menu.ui", &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch5_g_error;
		}
	}
	goto __finally5;
	__catch5_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp1_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp1_ = e->message;
		g_error ("simple-header-bar.vala:37: Error loading menu UI: %s", _tmp1_);
		_g_error_free0 (e);
	}
	__finally5:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (builder);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = (GtkMenuButton*) gtk_menu_button_new ();
	g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->priv->menu_b);
	self->priv->menu_b = _tmp2_;
	_tmp3_ = self->priv->menu_b;
	gtk_menu_button_set_direction (_tmp3_, GTK_ARROW_NONE);
	_tmp4_ = self->priv->menu_b;
	_tmp5_ = gtk_builder_get_object (builder, "window-menu");
	gtk_menu_button_set_menu_model (_tmp4_, G_TYPE_CHECK_INSTANCE_TYPE (_tmp5_, g_menu_model_get_type ()) ? ((GMenuModel*) _tmp5_) : NULL);
	_tmp6_ = self->priv->menu_b;
	gtk_button_set_relief ((GtkButton*) _tmp6_, GTK_RELIEF_NONE);
	_tmp7_ = self->priv->menu_b;
	gtk_menu_button_set_use_popover (_tmp7_, FALSE);
	_tmp8_ = self->priv->menu_b;
	gtk_widget_show_all ((GtkWidget*) _tmp8_);
	_tmp9_ = _ ("Open");
	_tmp10_ = (GtkButton*) gtk_button_new_with_label (_tmp9_);
	g_object_ref_sink (_tmp10_);
	_g_object_unref0 (self->priv->abrir);
	self->priv->abrir = _tmp10_;
	_tmp11_ = self->priv->abrir;
	_tmp12_ = _ ("Open file");
	_tmp13_ = g_strconcat (_tmp12_, " (Ctrl+O)", NULL);
	_tmp14_ = _tmp13_;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp11_, _tmp14_);
	_g_free0 (_tmp14_);
	_tmp15_ = self->priv->abrir;
	gtk_widget_show ((GtkWidget*) _tmp15_);
	_tmp16_ = _ ("Save");
	_tmp17_ = (GtkButton*) gtk_button_new_with_label (_tmp16_);
	g_object_ref_sink (_tmp17_);
	_g_object_unref0 (self->priv->guardar);
	self->priv->guardar = _tmp17_;
	_tmp18_ = self->priv->guardar;
	_tmp19_ = _ ("Save file");
	_tmp20_ = g_strconcat (_tmp19_, " (Ctrl+S)", NULL);
	_tmp21_ = _tmp20_;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp18_, _tmp21_);
	_g_free0 (_tmp21_);
	_tmp22_ = self->priv->guardar;
	gtk_widget_show ((GtkWidget*) _tmp22_);
	_tmp23_ = (GtkButton*) gtk_button_new_from_icon_name ("tab-new-symbolic", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp23_);
	_g_object_unref0 (self->priv->nuevo);
	self->priv->nuevo = _tmp23_;
	_tmp24_ = self->priv->nuevo;
	_tmp25_ = _ ("New file");
	_tmp26_ = g_strconcat (_tmp25_, " (Ctrl+N)", NULL);
	_tmp27_ = _tmp26_;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp24_, _tmp27_);
	_g_free0 (_tmp27_);
	_tmp28_ = self->priv->nuevo;
	gtk_widget_show ((GtkWidget*) _tmp28_);
	_tmp29_ = (GtkButton*) gtk_button_new_from_icon_name ("media-playback-start-symbolic", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp29_);
	_g_object_unref0 (self->priv->build);
	self->priv->build = _tmp29_;
	_tmp30_ = self->priv->build;
	_tmp31_ = _ ("Build using make");
	_tmp32_ = g_strconcat (_tmp31_, " (Ctrl+B)", NULL);
	_tmp33_ = _tmp32_;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp30_, _tmp33_);
	_g_free0 (_tmp33_);
	simple_header_bar_set_buildable (self, FALSE);
	_tmp34_ = self->priv->build;
	gtk_widget_show ((GtkWidget*) _tmp34_);
	_tmp35_ = self->priv->abrir;
	gtk_header_bar_pack_start ((GtkHeaderBar*) self, (GtkWidget*) _tmp35_);
	_tmp36_ = self->priv->nuevo;
	gtk_header_bar_pack_start ((GtkHeaderBar*) self, (GtkWidget*) _tmp36_);
	_tmp37_ = self->priv->menu_b;
	gtk_header_bar_pack_end ((GtkHeaderBar*) self, (GtkWidget*) _tmp37_);
	_tmp38_ = self->priv->build;
	gtk_header_bar_pack_end ((GtkHeaderBar*) self, (GtkWidget*) _tmp38_);
	_tmp39_ = self->priv->guardar;
	gtk_header_bar_pack_end ((GtkHeaderBar*) self, (GtkWidget*) _tmp39_);
	_g_object_unref0 (builder);
}


static void _main_window_open_file_cb_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	main_window_open_file_cb ((MainWindow*) self);
}


static void _main_window_save_tab_to_file_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	main_window_save_tab_to_file ((MainWindow*) self);
}


static void _main_window_new_tab_cb_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	main_window_new_tab_cb ((MainWindow*) self);
}


static void _main_window_build_code_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	main_window_build_code ((MainWindow*) self);
}


static void simple_header_bar_connect_signals (SimpleHeaderBar* self) {
	GtkButton* _tmp0_ = NULL;
	MainWindow* _tmp1_ = NULL;
	GtkButton* _tmp2_ = NULL;
	MainWindow* _tmp3_ = NULL;
	GtkButton* _tmp4_ = NULL;
	MainWindow* _tmp5_ = NULL;
	GtkButton* _tmp6_ = NULL;
	MainWindow* _tmp7_ = NULL;
	GtkAccelGroup* accels = NULL;
	GtkAccelGroup* _tmp8_ = NULL;
	MainWindow* _tmp9_ = NULL;
	GtkButton* _tmp10_ = NULL;
	GtkButton* _tmp11_ = NULL;
	GtkButton* _tmp12_ = NULL;
	GtkButton* _tmp13_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->abrir;
	_tmp1_ = self->priv->parent_window;
	g_signal_connect_object (_tmp0_, "clicked", (GCallback) _main_window_open_file_cb_gtk_button_clicked, _tmp1_, 0);
	_tmp2_ = self->priv->guardar;
	_tmp3_ = self->priv->parent_window;
	g_signal_connect_object (_tmp2_, "clicked", (GCallback) _main_window_save_tab_to_file_gtk_button_clicked, _tmp3_, 0);
	_tmp4_ = self->priv->nuevo;
	_tmp5_ = self->priv->parent_window;
	g_signal_connect_object (_tmp4_, "clicked", (GCallback) _main_window_new_tab_cb_gtk_button_clicked, _tmp5_, 0);
	_tmp6_ = self->priv->build;
	_tmp7_ = self->priv->parent_window;
	g_signal_connect_object (_tmp6_, "clicked", (GCallback) _main_window_build_code_gtk_button_clicked, _tmp7_, 0);
	_tmp8_ = gtk_accel_group_new ();
	accels = _tmp8_;
	_tmp9_ = self->priv->parent_window;
	gtk_window_add_accel_group ((GtkWindow*) _tmp9_, accels);
	_tmp10_ = self->priv->abrir;
	gtk_widget_add_accelerator ((GtkWidget*) _tmp10_, "activate", accels, (guint) GDK_KEY_O, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);
	_tmp11_ = self->priv->guardar;
	gtk_widget_add_accelerator ((GtkWidget*) _tmp11_, "activate", accels, (guint) GDK_KEY_S, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);
	_tmp12_ = self->priv->nuevo;
	gtk_widget_add_accelerator ((GtkWidget*) _tmp12_, "activate", accels, (guint) GDK_KEY_N, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);
	_tmp13_ = self->priv->build;
	gtk_widget_add_accelerator ((GtkWidget*) _tmp13_, "activate", accels, (guint) GDK_KEY_B, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);
	_g_object_unref0 (accels);
}


gboolean simple_header_bar_get_buildable (SimpleHeaderBar* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_buildable;
	result = _tmp0_;
	return result;
}


void simple_header_bar_set_buildable (SimpleHeaderBar* self, gboolean value) {
	GtkButton* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->build;
	if (_tmp0_ != NULL) {
		gboolean _tmp1_ = FALSE;
		GtkButton* _tmp2_ = NULL;
		gboolean _tmp3_ = FALSE;
		gboolean _tmp4_ = FALSE;
		_tmp1_ = value;
		self->priv->_buildable = _tmp1_;
		_tmp2_ = self->priv->build;
		_tmp3_ = simple_header_bar_get_buildable (self);
		_tmp4_ = _tmp3_;
		gtk_widget_set_sensitive ((GtkWidget*) _tmp2_, _tmp4_);
	}
	g_object_notify ((GObject *) self, "buildable");
}


static void simple_header_bar_class_init (SimpleHeaderBarClass * klass) {
	simple_header_bar_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SimpleHeaderBarPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_simple_header_bar_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_simple_header_bar_set_property;
	G_OBJECT_CLASS (klass)->finalize = simple_header_bar_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SIMPLE_HEADER_BAR_BUILDABLE, g_param_spec_boolean ("buildable", "buildable", "buildable", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void simple_header_bar_instance_init (SimpleHeaderBar * self) {
	self->priv = SIMPLE_HEADER_BAR_GET_PRIVATE (self);
}


static void simple_header_bar_finalize (GObject* obj) {
	SimpleHeaderBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SIMPLE_HEADER_BAR, SimpleHeaderBar);
	_g_object_unref0 (self->priv->parent_window);
	_g_object_unref0 (self->priv->menu_b);
	_g_object_unref0 (self->priv->abrir);
	_g_object_unref0 (self->priv->guardar);
	_g_object_unref0 (self->priv->nuevo);
	_g_object_unref0 (self->priv->build);
	G_OBJECT_CLASS (simple_header_bar_parent_class)->finalize (obj);
}


GType simple_header_bar_get_type (void) {
	static volatile gsize simple_header_bar_type_id__volatile = 0;
	if (g_once_init_enter (&simple_header_bar_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SimpleHeaderBarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) simple_header_bar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SimpleHeaderBar), 0, (GInstanceInitFunc) simple_header_bar_instance_init, NULL };
		GType simple_header_bar_type_id;
		simple_header_bar_type_id = g_type_register_static (gtk_header_bar_get_type (), "SimpleHeaderBar", &g_define_type_info, 0);
		g_once_init_leave (&simple_header_bar_type_id__volatile, simple_header_bar_type_id);
	}
	return simple_header_bar_type_id__volatile;
}


static void _vala_simple_header_bar_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SimpleHeaderBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_SIMPLE_HEADER_BAR, SimpleHeaderBar);
	switch (property_id) {
		case SIMPLE_HEADER_BAR_BUILDABLE:
		g_value_set_boolean (value, simple_header_bar_get_buildable (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_simple_header_bar_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SimpleHeaderBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_SIMPLE_HEADER_BAR, SimpleHeaderBar);
	switch (property_id) {
		case SIMPLE_HEADER_BAR_BUILDABLE:
		simple_header_bar_set_buildable (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



