/* simple-preferences.c generated by valac 0.28.0, the Vala compiler
 * generated from simple-preferences.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <glib/gi18n-lib.h>
#include <float.h>
#include <math.h>
#include <gtksourceview/gtksource.h>


#define TYPE_PREFERENCES_DIALOG (preferences_dialog_get_type ())
#define PREFERENCES_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PREFERENCES_DIALOG, PreferencesDialog))
#define PREFERENCES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PREFERENCES_DIALOG, PreferencesDialogClass))
#define IS_PREFERENCES_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PREFERENCES_DIALOG))
#define IS_PREFERENCES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PREFERENCES_DIALOG))
#define PREFERENCES_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PREFERENCES_DIALOG, PreferencesDialogClass))

typedef struct _PreferencesDialog PreferencesDialog;
typedef struct _PreferencesDialogClass PreferencesDialogClass;
typedef struct _PreferencesDialogPrivate PreferencesDialogPrivate;

#define TYPE_TEXT_EDITOR (text_editor_get_type ())
#define TEXT_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXT_EDITOR, TextEditor))
#define TEXT_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXT_EDITOR, TextEditorClass))
#define IS_TEXT_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXT_EDITOR))
#define IS_TEXT_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXT_EDITOR))
#define TEXT_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXT_EDITOR, TextEditorClass))

typedef struct _TextEditor TextEditor;
typedef struct _TextEditorClass TextEditorClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_MAIN_WINDOW (main_window_get_type ())
#define MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_WINDOW, MainWindow))
#define MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_WINDOW, MainWindowClass))
#define IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_WINDOW))
#define IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_WINDOW))
#define MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_WINDOW, MainWindowClass))

typedef struct _MainWindow MainWindow;
typedef struct _MainWindowClass MainWindowClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _PreferencesDialog {
	GtkDialog parent_instance;
	PreferencesDialogPrivate * priv;
};

struct _PreferencesDialogClass {
	GtkDialogClass parent_class;
};

struct _PreferencesDialogPrivate {
	TextEditor* _editor;
	GtkStackSwitcher* switcher;
	GtkStack* stack;
	GtkCheckButton* line_numbers_check;
	GtkCheckButton* right_margin_check;
	GtkSpinButton* right_margin_spin;
	GtkCheckButton* current_line_check;
	GtkCheckButton* brackets_check;
	GtkComboBox* tab_width_combo;
	GtkCheckButton* insert_spaces_check;
	GtkCheckButton* auto_indent_check;
	GtkCheckButton* grid_pattern_check;
	GtkCheckButton* default_typo_check;
	GtkFontButton* font_button;
	GtkListBox* scheme_chooser;
	GtkCheckButton* prefer_dark_check;
};


static gpointer preferences_dialog_parent_class = NULL;

GType preferences_dialog_get_type (void) G_GNUC_CONST;
GType text_editor_get_type (void) G_GNUC_CONST;
#define PREFERENCES_DIALOG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PREFERENCES_DIALOG, PreferencesDialogPrivate))
enum  {
	PREFERENCES_DIALOG_DUMMY_PROPERTY,
	PREFERENCES_DIALOG_EDITOR
};
GType main_window_get_type (void) G_GNUC_CONST;
PreferencesDialog* preferences_dialog_new (MainWindow* parent, TextEditor* ed);
PreferencesDialog* preferences_dialog_construct (GType object_type, MainWindow* parent, TextEditor* ed);
static void preferences_dialog_on_scheme_selected (PreferencesDialog* self, GtkListBoxRow* row);
static TextEditor* preferences_dialog_get_editor (PreferencesDialog* self);
void text_editor_set_color_scheme (TextEditor* self, const gchar* value);
static void preferences_dialog_set_combo_box_from_int (PreferencesDialog* self, GtkComboBox* combo, gint value);
static void preferences_dialog_on_tab_width_changed (PreferencesDialog* self, GtkComboBox* combo);
void text_editor_set_tab_width (TextEditor* self, gint value);
static void preferences_dialog_real_response (GtkDialog* base, gint id);
static gboolean preferences_dialog_real_delete_event (GtkWidget* base, GdkEventAny* event);
static void preferences_dialog_set_editor (PreferencesDialog* self, TextEditor* value);
static GObject * preferences_dialog_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void _preferences_dialog___lambda24_ (PreferencesDialog* self);
void text_editor_set_show_line_numbers (TextEditor* self, gboolean value);
static void __preferences_dialog___lambda24__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void _preferences_dialog___lambda25_ (PreferencesDialog* self);
void text_editor_set_show_right_margin (TextEditor* self, gboolean value);
static void __preferences_dialog___lambda25__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void _preferences_dialog___lambda26_ (PreferencesDialog* self);
void text_editor_set_right_margin_at (TextEditor* self, gint value);
static void __preferences_dialog___lambda26__gtk_spin_button_value_changed (GtkSpinButton* _sender, gpointer self);
static void _preferences_dialog___lambda27_ (PreferencesDialog* self);
void text_editor_set_highlight_current_line (TextEditor* self, gboolean value);
static void __preferences_dialog___lambda27__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void _preferences_dialog___lambda28_ (PreferencesDialog* self);
void text_editor_set_highlight_brackets (TextEditor* self, gboolean value);
static void __preferences_dialog___lambda28__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void _preferences_dialog___lambda29_ (PreferencesDialog* self);
void text_editor_set_show_grid_pattern (TextEditor* self, gboolean value);
static void __preferences_dialog___lambda29__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void _preferences_dialog_on_tab_width_changed_gtk_combo_box_changed (GtkComboBox* _sender, gpointer self);
static void _preferences_dialog___lambda30_ (PreferencesDialog* self);
void text_editor_set_insert_spaces (TextEditor* self, gboolean value);
static void __preferences_dialog___lambda30__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void _preferences_dialog___lambda31_ (PreferencesDialog* self);
void text_editor_set_auto_indent (TextEditor* self, gboolean value);
static void __preferences_dialog___lambda31__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void _preferences_dialog___lambda32_ (PreferencesDialog* self);
void text_editor_set_use_default_typo (TextEditor* self, gboolean value);
static void __preferences_dialog___lambda32__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void _preferences_dialog___lambda33_ (PreferencesDialog* self);
void text_editor_set_editor_font (TextEditor* self, const gchar* value);
static void __preferences_dialog___lambda33__gtk_font_button_font_set (GtkFontButton* _sender, gpointer self);
static void _preferences_dialog_on_scheme_selected_gtk_list_box_row_activated (GtkListBox* _sender, GtkListBoxRow* row, gpointer self);
static void _preferences_dialog___lambda34_ (PreferencesDialog* self);
void text_editor_set_prefer_dark (TextEditor* self, gboolean value);
static void __preferences_dialog___lambda34__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
gboolean text_editor_get_show_line_numbers (TextEditor* self);
static void _preferences_dialog___lambda35_ (PreferencesDialog* self, GParamSpec* pspec);
static void __preferences_dialog___lambda35__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
gboolean text_editor_get_show_right_margin (TextEditor* self);
static void _preferences_dialog___lambda36_ (PreferencesDialog* self, GParamSpec* pspec);
static void __preferences_dialog___lambda36__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
gint text_editor_get_right_margin_at (TextEditor* self);
static void _preferences_dialog___lambda37_ (PreferencesDialog* self, GParamSpec* pspec);
static void __preferences_dialog___lambda37__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
gboolean text_editor_get_highlight_current_line (TextEditor* self);
static void _preferences_dialog___lambda38_ (PreferencesDialog* self, GParamSpec* pspec);
static void __preferences_dialog___lambda38__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
gboolean text_editor_get_highlight_brackets (TextEditor* self);
static void _preferences_dialog___lambda39_ (PreferencesDialog* self, GParamSpec* pspec);
static void __preferences_dialog___lambda39__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
gint text_editor_get_tab_width (TextEditor* self);
static void _preferences_dialog___lambda40_ (PreferencesDialog* self, GParamSpec* pspec);
static void __preferences_dialog___lambda40__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
gboolean text_editor_get_insert_spaces (TextEditor* self);
static void _preferences_dialog___lambda41_ (PreferencesDialog* self, GParamSpec* pspec);
static void __preferences_dialog___lambda41__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
gboolean text_editor_get_auto_indent (TextEditor* self);
static void _preferences_dialog___lambda42_ (PreferencesDialog* self, GParamSpec* pspec);
static void __preferences_dialog___lambda42__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
gboolean text_editor_get_show_grid_pattern (TextEditor* self);
static void _preferences_dialog___lambda43_ (PreferencesDialog* self, GParamSpec* pspec);
static void __preferences_dialog___lambda43__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
gboolean text_editor_get_use_default_typo (TextEditor* self);
static void _preferences_dialog___lambda44_ (PreferencesDialog* self, GParamSpec* pspec);
static void __preferences_dialog___lambda44__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
const gchar* text_editor_get_editor_font (TextEditor* self);
static void _preferences_dialog___lambda45_ (PreferencesDialog* self, GParamSpec* pspec);
static void __preferences_dialog___lambda45__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
gboolean text_editor_get_prefer_dark (TextEditor* self);
static void _preferences_dialog___lambda46_ (PreferencesDialog* self, GParamSpec* pspec);
static void __preferences_dialog___lambda46__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void preferences_dialog_finalize (GObject* obj);
static void _vala_preferences_dialog_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_preferences_dialog_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static gint _vala_array_length (gpointer array);


PreferencesDialog* preferences_dialog_construct (GType object_type, MainWindow* parent, TextEditor* ed) {
	PreferencesDialog * self = NULL;
	TextEditor* _tmp0_ = NULL;
	MainWindow* _tmp1_ = NULL;
	g_return_val_if_fail (parent != NULL, NULL);
	g_return_val_if_fail (ed != NULL, NULL);
	_tmp0_ = ed;
	self = (PreferencesDialog*) g_object_new (object_type, "use-header-bar", (gint) TRUE, "editor", _tmp0_, NULL);
	_tmp1_ = parent;
	gtk_window_set_transient_for ((GtkWindow*) self, (GtkWindow*) _tmp1_);
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 10);
	return self;
}


PreferencesDialog* preferences_dialog_new (MainWindow* parent, TextEditor* ed) {
	return preferences_dialog_construct (TYPE_PREFERENCES_DIALOG, parent, ed);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void preferences_dialog_on_scheme_selected (PreferencesDialog* self, GtkListBoxRow* row) {
	GtkLabel* scheme = NULL;
	GtkListBoxRow* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	TextEditor* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (row != NULL);
	_tmp0_ = row;
	_tmp1_ = gtk_bin_get_child ((GtkBin*) _tmp0_);
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, gtk_label_get_type ()) ? ((GtkLabel*) _tmp1_) : NULL);
	scheme = _tmp2_;
	_tmp3_ = self->priv->_editor;
	_tmp4_ = gtk_label_get_label (scheme);
	_tmp5_ = _tmp4_;
	text_editor_set_color_scheme (_tmp3_, _tmp5_);
	_g_object_unref0 (scheme);
}


static void preferences_dialog_set_combo_box_from_int (PreferencesDialog* self, GtkComboBox* combo, gint value) {
	GtkTreeIter iter = {0};
	gboolean valid = FALSE;
	GtkComboBox* _tmp0_ = NULL;
	GtkTreeModel* _tmp1_ = NULL;
	GtkTreeModel* _tmp2_ = NULL;
	GtkTreeIter _tmp3_ = {0};
	gboolean _tmp4_ = FALSE;
	gboolean _tmp16_ = FALSE;
	GtkComboBox* _tmp22_ = NULL;
	GtkTreeIter _tmp23_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (combo != NULL);
	_tmp0_ = combo;
	_tmp1_ = gtk_combo_box_get_model (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp4_ = gtk_tree_model_get_iter_first (_tmp2_, &_tmp3_);
	iter = _tmp3_;
	valid = _tmp4_;
	while (TRUE) {
		gboolean _tmp5_ = FALSE;
		gint v = 0;
		GtkComboBox* _tmp6_ = NULL;
		GtkTreeModel* _tmp7_ = NULL;
		GtkTreeModel* _tmp8_ = NULL;
		GtkTreeIter _tmp9_ = {0};
		gint _tmp10_ = 0;
		gint _tmp11_ = 0;
		GtkComboBox* _tmp12_ = NULL;
		GtkTreeModel* _tmp13_ = NULL;
		GtkTreeModel* _tmp14_ = NULL;
		gboolean _tmp15_ = FALSE;
		_tmp5_ = valid;
		if (!_tmp5_) {
			break;
		}
		_tmp6_ = combo;
		_tmp7_ = gtk_combo_box_get_model (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = iter;
		gtk_tree_model_get (_tmp8_, &_tmp9_, 0, &v, -1, -1);
		_tmp10_ = v;
		_tmp11_ = value;
		if (_tmp10_ == _tmp11_) {
			break;
		}
		_tmp12_ = combo;
		_tmp13_ = gtk_combo_box_get_model (_tmp12_);
		_tmp14_ = _tmp13_;
		_tmp15_ = gtk_tree_model_iter_next (_tmp14_, &iter);
		valid = _tmp15_;
	}
	_tmp16_ = valid;
	if (!_tmp16_) {
		GtkComboBox* _tmp17_ = NULL;
		GtkTreeModel* _tmp18_ = NULL;
		GtkTreeModel* _tmp19_ = NULL;
		GtkTreeIter _tmp20_ = {0};
		gboolean _tmp21_ = FALSE;
		_tmp17_ = combo;
		_tmp18_ = gtk_combo_box_get_model (_tmp17_);
		_tmp19_ = _tmp18_;
		_tmp21_ = gtk_tree_model_get_iter_first (_tmp19_, &_tmp20_);
		iter = _tmp20_;
		valid = _tmp21_;
	}
	_tmp22_ = combo;
	_tmp23_ = iter;
	gtk_combo_box_set_active_iter (_tmp22_, &_tmp23_);
}


static void preferences_dialog_on_tab_width_changed (PreferencesDialog* self, GtkComboBox* combo) {
	GtkTreeIter iter = {0};
	GtkComboBox* _tmp0_ = NULL;
	GtkTreeIter _tmp1_ = {0};
	gint value = 0;
	GtkComboBox* _tmp2_ = NULL;
	GtkTreeModel* _tmp3_ = NULL;
	GtkTreeModel* _tmp4_ = NULL;
	GtkTreeIter _tmp5_ = {0};
	TextEditor* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (combo != NULL);
	_tmp0_ = combo;
	gtk_combo_box_get_active_iter (_tmp0_, &_tmp1_);
	iter = _tmp1_;
	_tmp2_ = combo;
	_tmp3_ = gtk_combo_box_get_model (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = iter;
	gtk_tree_model_get (_tmp4_, &_tmp5_, 0, &value, -1, -1);
	_tmp6_ = self->priv->_editor;
	text_editor_set_tab_width (_tmp6_, value);
}


static void preferences_dialog_real_response (GtkDialog* base, gint id) {
	PreferencesDialog * self;
	self = (PreferencesDialog*) base;
	gtk_widget_hide ((GtkWidget*) self);
}


static gboolean preferences_dialog_real_delete_event (GtkWidget* base, GdkEventAny* event) {
	PreferencesDialog * self;
	gboolean result = FALSE;
	self = (PreferencesDialog*) base;
	g_return_val_if_fail (event != NULL, FALSE);
	gtk_widget_hide ((GtkWidget*) self);
	result = TRUE;
	return result;
}


static TextEditor* preferences_dialog_get_editor (PreferencesDialog* self) {
	TextEditor* result;
	TextEditor* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_editor;
	result = _tmp0_;
	return result;
}


static void preferences_dialog_set_editor (PreferencesDialog* self, TextEditor* value) {
	TextEditor* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_editor);
	self->priv->_editor = _tmp1_;
	g_object_notify ((GObject *) self, "editor");
}


static void _preferences_dialog___lambda24_ (PreferencesDialog* self) {
	TextEditor* _tmp0_ = NULL;
	GtkCheckButton* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	_tmp0_ = self->priv->_editor;
	_tmp1_ = self->priv->line_numbers_check;
	_tmp2_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp1_);
	_tmp3_ = _tmp2_;
	text_editor_set_show_line_numbers (_tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda24__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	_preferences_dialog___lambda24_ ((PreferencesDialog*) self);
}


static void _preferences_dialog___lambda25_ (PreferencesDialog* self) {
	GtkSpinButton* _tmp0_ = NULL;
	GtkCheckButton* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	TextEditor* _tmp4_ = NULL;
	GtkCheckButton* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	gboolean _tmp7_ = FALSE;
	_tmp0_ = self->priv->right_margin_spin;
	_tmp1_ = self->priv->right_margin_check;
	_tmp2_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp1_);
	_tmp3_ = _tmp2_;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp0_, _tmp3_);
	_tmp4_ = self->priv->_editor;
	_tmp5_ = self->priv->right_margin_check;
	_tmp6_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp5_);
	_tmp7_ = _tmp6_;
	text_editor_set_show_right_margin (_tmp4_, _tmp7_);
}


static void __preferences_dialog___lambda25__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	_preferences_dialog___lambda25_ ((PreferencesDialog*) self);
}


static void _preferences_dialog___lambda26_ (PreferencesDialog* self) {
	TextEditor* _tmp0_ = NULL;
	GtkSpinButton* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	_tmp0_ = self->priv->_editor;
	_tmp1_ = self->priv->right_margin_spin;
	_tmp2_ = gtk_spin_button_get_value_as_int (_tmp1_);
	text_editor_set_right_margin_at (_tmp0_, _tmp2_);
}


static void __preferences_dialog___lambda26__gtk_spin_button_value_changed (GtkSpinButton* _sender, gpointer self) {
	_preferences_dialog___lambda26_ ((PreferencesDialog*) self);
}


static void _preferences_dialog___lambda27_ (PreferencesDialog* self) {
	TextEditor* _tmp0_ = NULL;
	GtkCheckButton* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	_tmp0_ = self->priv->_editor;
	_tmp1_ = self->priv->current_line_check;
	_tmp2_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp1_);
	_tmp3_ = _tmp2_;
	text_editor_set_highlight_current_line (_tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda27__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	_preferences_dialog___lambda27_ ((PreferencesDialog*) self);
}


static void _preferences_dialog___lambda28_ (PreferencesDialog* self) {
	TextEditor* _tmp0_ = NULL;
	GtkCheckButton* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	_tmp0_ = self->priv->_editor;
	_tmp1_ = self->priv->brackets_check;
	_tmp2_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp1_);
	_tmp3_ = _tmp2_;
	text_editor_set_highlight_brackets (_tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda28__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	_preferences_dialog___lambda28_ ((PreferencesDialog*) self);
}


static void _preferences_dialog___lambda29_ (PreferencesDialog* self) {
	TextEditor* _tmp0_ = NULL;
	GtkCheckButton* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	_tmp0_ = self->priv->_editor;
	_tmp1_ = self->priv->grid_pattern_check;
	_tmp2_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp1_);
	_tmp3_ = _tmp2_;
	text_editor_set_show_grid_pattern (_tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda29__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	_preferences_dialog___lambda29_ ((PreferencesDialog*) self);
}


static void _preferences_dialog_on_tab_width_changed_gtk_combo_box_changed (GtkComboBox* _sender, gpointer self) {
	preferences_dialog_on_tab_width_changed ((PreferencesDialog*) self, _sender);
}


static void _preferences_dialog___lambda30_ (PreferencesDialog* self) {
	TextEditor* _tmp0_ = NULL;
	GtkCheckButton* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	_tmp0_ = self->priv->_editor;
	_tmp1_ = self->priv->insert_spaces_check;
	_tmp2_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp1_);
	_tmp3_ = _tmp2_;
	text_editor_set_insert_spaces (_tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda30__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	_preferences_dialog___lambda30_ ((PreferencesDialog*) self);
}


static void _preferences_dialog___lambda31_ (PreferencesDialog* self) {
	TextEditor* _tmp0_ = NULL;
	GtkCheckButton* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	_tmp0_ = self->priv->_editor;
	_tmp1_ = self->priv->auto_indent_check;
	_tmp2_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp1_);
	_tmp3_ = _tmp2_;
	text_editor_set_auto_indent (_tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda31__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	_preferences_dialog___lambda31_ ((PreferencesDialog*) self);
}


static void _preferences_dialog___lambda32_ (PreferencesDialog* self) {
	GtkFontButton* _tmp0_ = NULL;
	GtkCheckButton* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	TextEditor* _tmp4_ = NULL;
	GtkCheckButton* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	gboolean _tmp7_ = FALSE;
	_tmp0_ = self->priv->font_button;
	_tmp1_ = self->priv->default_typo_check;
	_tmp2_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp1_);
	_tmp3_ = _tmp2_;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp0_, !_tmp3_);
	_tmp4_ = self->priv->_editor;
	_tmp5_ = self->priv->default_typo_check;
	_tmp6_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp5_);
	_tmp7_ = _tmp6_;
	text_editor_set_use_default_typo (_tmp4_, _tmp7_);
}


static void __preferences_dialog___lambda32__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	_preferences_dialog___lambda32_ ((PreferencesDialog*) self);
}


static void _preferences_dialog___lambda33_ (PreferencesDialog* self) {
	TextEditor* _tmp0_ = NULL;
	GtkFontButton* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	_tmp0_ = self->priv->_editor;
	_tmp1_ = self->priv->font_button;
	_tmp2_ = gtk_font_button_get_font_name (_tmp1_);
	_tmp3_ = _tmp2_;
	text_editor_set_editor_font (_tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda33__gtk_font_button_font_set (GtkFontButton* _sender, gpointer self) {
	_preferences_dialog___lambda33_ ((PreferencesDialog*) self);
}


static void _preferences_dialog_on_scheme_selected_gtk_list_box_row_activated (GtkListBox* _sender, GtkListBoxRow* row, gpointer self) {
	preferences_dialog_on_scheme_selected ((PreferencesDialog*) self, row);
}


static void _preferences_dialog___lambda34_ (PreferencesDialog* self) {
	TextEditor* _tmp0_ = NULL;
	GtkCheckButton* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	_tmp0_ = self->priv->_editor;
	_tmp1_ = self->priv->prefer_dark_check;
	_tmp2_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp1_);
	_tmp3_ = _tmp2_;
	text_editor_set_prefer_dark (_tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda34__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	_preferences_dialog___lambda34_ ((PreferencesDialog*) self);
}


static void _preferences_dialog___lambda35_ (PreferencesDialog* self, GParamSpec* pspec) {
	GtkCheckButton* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->line_numbers_check;
	_tmp1_ = self->priv->_editor;
	_tmp2_ = text_editor_get_show_line_numbers (_tmp1_);
	_tmp3_ = _tmp2_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda35__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	_preferences_dialog___lambda35_ ((PreferencesDialog*) self, pspec);
}


static void _preferences_dialog___lambda36_ (PreferencesDialog* self, GParamSpec* pspec) {
	GtkCheckButton* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->right_margin_check;
	_tmp1_ = self->priv->_editor;
	_tmp2_ = text_editor_get_show_right_margin (_tmp1_);
	_tmp3_ = _tmp2_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda36__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	_preferences_dialog___lambda36_ ((PreferencesDialog*) self, pspec);
}


static void _preferences_dialog___lambda37_ (PreferencesDialog* self, GParamSpec* pspec) {
	GtkSpinButton* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->right_margin_spin;
	_tmp1_ = self->priv->_editor;
	_tmp2_ = text_editor_get_right_margin_at (_tmp1_);
	_tmp3_ = _tmp2_;
	gtk_spin_button_set_value (_tmp0_, (gdouble) _tmp3_);
}


static void __preferences_dialog___lambda37__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	_preferences_dialog___lambda37_ ((PreferencesDialog*) self, pspec);
}


static void _preferences_dialog___lambda38_ (PreferencesDialog* self, GParamSpec* pspec) {
	GtkCheckButton* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->current_line_check;
	_tmp1_ = self->priv->_editor;
	_tmp2_ = text_editor_get_highlight_current_line (_tmp1_);
	_tmp3_ = _tmp2_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda38__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	_preferences_dialog___lambda38_ ((PreferencesDialog*) self, pspec);
}


static void _preferences_dialog___lambda39_ (PreferencesDialog* self, GParamSpec* pspec) {
	GtkCheckButton* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->brackets_check;
	_tmp1_ = self->priv->_editor;
	_tmp2_ = text_editor_get_highlight_brackets (_tmp1_);
	_tmp3_ = _tmp2_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda39__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	_preferences_dialog___lambda39_ ((PreferencesDialog*) self, pspec);
}


static void _preferences_dialog___lambda40_ (PreferencesDialog* self, GParamSpec* pspec) {
	GtkComboBox* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->tab_width_combo;
	_tmp1_ = self->priv->_editor;
	_tmp2_ = text_editor_get_tab_width (_tmp1_);
	_tmp3_ = _tmp2_;
	preferences_dialog_set_combo_box_from_int (self, _tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda40__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	_preferences_dialog___lambda40_ ((PreferencesDialog*) self, pspec);
}


static void _preferences_dialog___lambda41_ (PreferencesDialog* self, GParamSpec* pspec) {
	GtkCheckButton* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->insert_spaces_check;
	_tmp1_ = self->priv->_editor;
	_tmp2_ = text_editor_get_insert_spaces (_tmp1_);
	_tmp3_ = _tmp2_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda41__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	_preferences_dialog___lambda41_ ((PreferencesDialog*) self, pspec);
}


static void _preferences_dialog___lambda42_ (PreferencesDialog* self, GParamSpec* pspec) {
	GtkCheckButton* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->auto_indent_check;
	_tmp1_ = self->priv->_editor;
	_tmp2_ = text_editor_get_auto_indent (_tmp1_);
	_tmp3_ = _tmp2_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda42__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	_preferences_dialog___lambda42_ ((PreferencesDialog*) self, pspec);
}


static void _preferences_dialog___lambda43_ (PreferencesDialog* self, GParamSpec* pspec) {
	GtkCheckButton* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->grid_pattern_check;
	_tmp1_ = self->priv->_editor;
	_tmp2_ = text_editor_get_show_grid_pattern (_tmp1_);
	_tmp3_ = _tmp2_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda43__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	_preferences_dialog___lambda43_ ((PreferencesDialog*) self, pspec);
}


static void _preferences_dialog___lambda44_ (PreferencesDialog* self, GParamSpec* pspec) {
	GtkCheckButton* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->default_typo_check;
	_tmp1_ = self->priv->_editor;
	_tmp2_ = text_editor_get_use_default_typo (_tmp1_);
	_tmp3_ = _tmp2_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda44__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	_preferences_dialog___lambda44_ ((PreferencesDialog*) self, pspec);
}


static void _preferences_dialog___lambda45_ (PreferencesDialog* self, GParamSpec* pspec) {
	GtkFontButton* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->font_button;
	_tmp1_ = self->priv->_editor;
	_tmp2_ = text_editor_get_editor_font (_tmp1_);
	_tmp3_ = _tmp2_;
	gtk_font_button_set_font_name (_tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda45__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	_preferences_dialog___lambda45_ ((PreferencesDialog*) self, pspec);
}


static void _preferences_dialog___lambda46_ (PreferencesDialog* self, GParamSpec* pspec) {
	GtkCheckButton* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->prefer_dark_check;
	_tmp1_ = self->priv->_editor;
	_tmp2_ = text_editor_get_prefer_dark (_tmp1_);
	_tmp3_ = _tmp2_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp0_, _tmp3_);
}


static void __preferences_dialog___lambda46__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	_preferences_dialog___lambda46_ ((PreferencesDialog*) self, pspec);
}


static GObject * preferences_dialog_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	PreferencesDialog * self;
	GtkListBox* box_view = NULL;
	GtkListBox* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	GtkListBox* box_editor = NULL;
	GtkListBox* _tmp2_ = NULL;
	GtkListBox* _tmp3_ = NULL;
	GtkListBox* box_typo = NULL;
	GtkListBox* _tmp4_ = NULL;
	GtkListBox* _tmp5_ = NULL;
	GtkStack* _tmp6_ = NULL;
	GtkStack* _tmp7_ = NULL;
	GtkStack* _tmp8_ = NULL;
	GtkStackSwitcher* _tmp9_ = NULL;
	GtkStackSwitcher* _tmp10_ = NULL;
	GtkStack* _tmp11_ = NULL;
	GtkHeaderBar* header_bar = NULL;
	GtkWidget* _tmp12_ = NULL;
	GtkHeaderBar* _tmp13_ = NULL;
	GtkHeaderBar* _tmp14_ = NULL;
	GtkStackSwitcher* _tmp15_ = NULL;
	GtkBox* _tmp16_ = NULL;
	GtkStack* _tmp17_ = NULL;
	GtkBox* _tmp18_ = NULL;
	GtkStack* _tmp19_ = NULL;
	GtkListBox* _tmp20_ = NULL;
	const gchar* _tmp21_ = NULL;
	GtkStack* _tmp22_ = NULL;
	GtkListBox* _tmp23_ = NULL;
	const gchar* _tmp24_ = NULL;
	GtkStack* _tmp25_ = NULL;
	GtkListBox* _tmp26_ = NULL;
	const gchar* _tmp27_ = NULL;
	const gchar* _tmp28_ = NULL;
	GtkCheckButton* _tmp29_ = NULL;
	GtkCheckButton* _tmp30_ = NULL;
	const gchar* _tmp31_ = NULL;
	GtkCheckButton* _tmp32_ = NULL;
	GtkCheckButton* _tmp33_ = NULL;
	GtkSpinButton* _tmp34_ = NULL;
	GtkSpinButton* _tmp35_ = NULL;
	GtkCheckButton* _tmp36_ = NULL;
	gboolean _tmp37_ = FALSE;
	gboolean _tmp38_ = FALSE;
	GtkSpinButton* _tmp39_ = NULL;
	GtkBox* hbox_margin = NULL;
	GtkBox* _tmp40_ = NULL;
	GtkBox* _tmp41_ = NULL;
	GtkCheckButton* _tmp42_ = NULL;
	GtkBox* _tmp43_ = NULL;
	GtkSpinButton* _tmp44_ = NULL;
	GtkLabel* aux_label_1 = NULL;
	GtkLabel* _tmp45_ = NULL;
	GtkLabel* _tmp46_ = NULL;
	GtkLabel* highlight_label = NULL;
	const gchar* _tmp47_ = NULL;
	gchar* _tmp48_ = NULL;
	gchar* _tmp49_ = NULL;
	gchar* _tmp50_ = NULL;
	gchar* _tmp51_ = NULL;
	GtkLabel* _tmp52_ = NULL;
	GtkLabel* _tmp53_ = NULL;
	GtkLabel* _tmp54_ = NULL;
	GtkLabel* _tmp55_ = NULL;
	const gchar* _tmp56_ = NULL;
	GtkCheckButton* _tmp57_ = NULL;
	GtkCheckButton* _tmp58_ = NULL;
	const gchar* _tmp59_ = NULL;
	GtkCheckButton* _tmp60_ = NULL;
	GtkCheckButton* _tmp61_ = NULL;
	const gchar* _tmp62_ = NULL;
	GtkCheckButton* _tmp63_ = NULL;
	GtkCheckButton* _tmp64_ = NULL;
	GtkListBox* _tmp65_ = NULL;
	GtkCheckButton* _tmp66_ = NULL;
	GtkListBox* _tmp67_ = NULL;
	GtkBox* _tmp68_ = NULL;
	GtkListBox* _tmp69_ = NULL;
	GtkCheckButton* _tmp70_ = NULL;
	GtkListBox* _tmp71_ = NULL;
	GtkLabel* _tmp72_ = NULL;
	GtkListBox* _tmp73_ = NULL;
	GtkLabel* _tmp74_ = NULL;
	GtkListBox* _tmp75_ = NULL;
	GtkCheckButton* _tmp76_ = NULL;
	GtkListBox* _tmp77_ = NULL;
	GtkCheckButton* _tmp78_ = NULL;
	GtkLabel* indent_label = NULL;
	const gchar* _tmp79_ = NULL;
	gchar* _tmp80_ = NULL;
	gchar* _tmp81_ = NULL;
	gchar* _tmp82_ = NULL;
	gchar* _tmp83_ = NULL;
	GtkLabel* _tmp84_ = NULL;
	GtkLabel* _tmp85_ = NULL;
	GtkLabel* _tmp86_ = NULL;
	GtkLabel* _tmp87_ = NULL;
	GtkLabel* tab_width_label = NULL;
	const gchar* _tmp88_ = NULL;
	GtkLabel* _tmp89_ = NULL;
	GtkLabel* _tmp90_ = NULL;
	GtkComboBox* _tmp91_ = NULL;
	GtkLabel* _tmp92_ = NULL;
	GtkComboBox* _tmp93_ = NULL;
	GtkTreeIter iter = {0};
	GtkListStore* model = NULL;
	GtkListStore* _tmp94_ = NULL;
	GtkComboBox* _tmp95_ = NULL;
	GtkListStore* _tmp96_ = NULL;
	GtkListStore* _tmp97_ = NULL;
	GtkTreeIter _tmp98_ = {0};
	GtkListStore* _tmp99_ = NULL;
	GtkTreeIter _tmp100_ = {0};
	GtkListStore* _tmp101_ = NULL;
	GtkTreeIter _tmp102_ = {0};
	GtkListStore* _tmp103_ = NULL;
	GtkTreeIter _tmp104_ = {0};
	GtkListStore* _tmp105_ = NULL;
	GtkTreeIter _tmp106_ = {0};
	GtkListStore* _tmp107_ = NULL;
	GtkTreeIter _tmp108_ = {0};
	GtkListStore* _tmp109_ = NULL;
	GtkTreeIter _tmp110_ = {0};
	GtkListStore* _tmp111_ = NULL;
	GtkTreeIter _tmp112_ = {0};
	GtkCellRendererText* renderer = NULL;
	GtkCellRendererText* _tmp113_ = NULL;
	GtkComboBox* _tmp114_ = NULL;
	GtkCellRendererText* _tmp115_ = NULL;
	GtkComboBox* _tmp116_ = NULL;
	GtkCellRendererText* _tmp117_ = NULL;
	GtkComboBox* _tmp118_ = NULL;
	GtkBox* hbox_tab_width = NULL;
	GtkBox* _tmp119_ = NULL;
	GtkBox* _tmp120_ = NULL;
	GtkLabel* _tmp121_ = NULL;
	GtkBox* _tmp122_ = NULL;
	GtkComboBox* _tmp123_ = NULL;
	const gchar* _tmp124_ = NULL;
	GtkCheckButton* _tmp125_ = NULL;
	GtkCheckButton* _tmp126_ = NULL;
	const gchar* _tmp127_ = NULL;
	GtkCheckButton* _tmp128_ = NULL;
	GtkCheckButton* _tmp129_ = NULL;
	GtkListBox* _tmp130_ = NULL;
	GtkLabel* _tmp131_ = NULL;
	GtkListBox* _tmp132_ = NULL;
	GtkBox* _tmp133_ = NULL;
	GtkListBox* _tmp134_ = NULL;
	GtkCheckButton* _tmp135_ = NULL;
	GtkListBox* _tmp136_ = NULL;
	GtkCheckButton* _tmp137_ = NULL;
	GtkLabel* typo_label = NULL;
	const gchar* _tmp138_ = NULL;
	gchar* _tmp139_ = NULL;
	gchar* _tmp140_ = NULL;
	gchar* _tmp141_ = NULL;
	gchar* _tmp142_ = NULL;
	GtkLabel* _tmp143_ = NULL;
	GtkLabel* _tmp144_ = NULL;
	GtkLabel* _tmp145_ = NULL;
	GtkLabel* _tmp146_ = NULL;
	const gchar* _tmp147_ = NULL;
	gchar* _tmp148_ = NULL;
	gchar* _tmp149_ = NULL;
	GtkCheckButton* _tmp150_ = NULL;
	GtkCheckButton* _tmp151_ = NULL;
	GtkFontButton* _tmp152_ = NULL;
	GtkFontButton* _tmp153_ = NULL;
	GtkCheckButton* _tmp154_ = NULL;
	gboolean _tmp155_ = FALSE;
	gboolean _tmp156_ = FALSE;
	GtkFontButton* _tmp157_ = NULL;
	GtkFontButton* _tmp158_ = NULL;
	GtkLabel* aux_label_3 = NULL;
	GtkLabel* _tmp159_ = NULL;
	GtkLabel* _tmp160_ = NULL;
	GtkLabel* color_scheme_label = NULL;
	const gchar* _tmp161_ = NULL;
	gchar* _tmp162_ = NULL;
	gchar* _tmp163_ = NULL;
	gchar* _tmp164_ = NULL;
	gchar* _tmp165_ = NULL;
	GtkLabel* _tmp166_ = NULL;
	GtkLabel* _tmp167_ = NULL;
	GtkLabel* _tmp168_ = NULL;
	GtkLabel* _tmp169_ = NULL;
	GtkSourceStyleSchemeManager* scheme_manager = NULL;
	GtkSourceStyleSchemeManager* _tmp170_ = NULL;
	GtkSourceStyleSchemeManager* _tmp171_ = NULL;
	GtkSourceStyleSchemeManager* _tmp172_ = NULL;
	GtkListBox* _tmp173_ = NULL;
	GtkListBox* _tmp174_ = NULL;
	GtkListBox* _tmp175_ = NULL;
	GtkListBox* _tmp176_ = NULL;
	GtkSourceStyleSchemeManager* _tmp177_ = NULL;
	gchar** _tmp178_ = NULL;
	gint _tmp178__length1 = 0;
	gchar** _tmp179_ = NULL;
	gint _tmp179__length1 = 0;
	GtkScrolledWindow* scroll = NULL;
	GtkScrolledWindow* _tmp185_ = NULL;
	GtkScrolledWindow* _tmp186_ = NULL;
	GtkScrolledWindow* _tmp187_ = NULL;
	GtkScrolledWindow* _tmp188_ = NULL;
	GtkListBox* _tmp189_ = NULL;
	GtkFrame* frame = NULL;
	GtkFrame* _tmp190_ = NULL;
	GtkFrame* _tmp191_ = NULL;
	GtkScrolledWindow* _tmp192_ = NULL;
	const gchar* _tmp193_ = NULL;
	GtkCheckButton* _tmp194_ = NULL;
	GtkCheckButton* _tmp195_ = NULL;
	GtkListBox* _tmp196_ = NULL;
	GtkLabel* _tmp197_ = NULL;
	GtkListBox* _tmp198_ = NULL;
	GtkCheckButton* _tmp199_ = NULL;
	GtkListBox* _tmp200_ = NULL;
	GtkFontButton* _tmp201_ = NULL;
	GtkListBox* _tmp202_ = NULL;
	GtkLabel* _tmp203_ = NULL;
	GtkListBox* _tmp204_ = NULL;
	GtkLabel* _tmp205_ = NULL;
	GtkListBox* _tmp206_ = NULL;
	GtkFrame* _tmp207_ = NULL;
	GtkListBox* _tmp208_ = NULL;
	GtkCheckButton* _tmp209_ = NULL;
	GtkCheckButton* _tmp210_ = NULL;
	TextEditor* _tmp211_ = NULL;
	gboolean _tmp212_ = FALSE;
	gboolean _tmp213_ = FALSE;
	TextEditor* _tmp214_ = NULL;
	GtkCheckButton* _tmp215_ = NULL;
	TextEditor* _tmp216_ = NULL;
	gboolean _tmp217_ = FALSE;
	gboolean _tmp218_ = FALSE;
	TextEditor* _tmp219_ = NULL;
	GtkSpinButton* _tmp220_ = NULL;
	TextEditor* _tmp221_ = NULL;
	gint _tmp222_ = 0;
	gint _tmp223_ = 0;
	TextEditor* _tmp224_ = NULL;
	GtkCheckButton* _tmp225_ = NULL;
	TextEditor* _tmp226_ = NULL;
	gboolean _tmp227_ = FALSE;
	gboolean _tmp228_ = FALSE;
	TextEditor* _tmp229_ = NULL;
	GtkCheckButton* _tmp230_ = NULL;
	TextEditor* _tmp231_ = NULL;
	gboolean _tmp232_ = FALSE;
	gboolean _tmp233_ = FALSE;
	TextEditor* _tmp234_ = NULL;
	GtkComboBox* _tmp235_ = NULL;
	TextEditor* _tmp236_ = NULL;
	gint _tmp237_ = 0;
	gint _tmp238_ = 0;
	TextEditor* _tmp239_ = NULL;
	GtkCheckButton* _tmp240_ = NULL;
	TextEditor* _tmp241_ = NULL;
	gboolean _tmp242_ = FALSE;
	gboolean _tmp243_ = FALSE;
	TextEditor* _tmp244_ = NULL;
	GtkCheckButton* _tmp245_ = NULL;
	TextEditor* _tmp246_ = NULL;
	gboolean _tmp247_ = FALSE;
	gboolean _tmp248_ = FALSE;
	TextEditor* _tmp249_ = NULL;
	GtkCheckButton* _tmp250_ = NULL;
	TextEditor* _tmp251_ = NULL;
	gboolean _tmp252_ = FALSE;
	gboolean _tmp253_ = FALSE;
	TextEditor* _tmp254_ = NULL;
	GtkCheckButton* _tmp255_ = NULL;
	TextEditor* _tmp256_ = NULL;
	gboolean _tmp257_ = FALSE;
	gboolean _tmp258_ = FALSE;
	TextEditor* _tmp259_ = NULL;
	GtkFontButton* _tmp260_ = NULL;
	TextEditor* _tmp261_ = NULL;
	const gchar* _tmp262_ = NULL;
	const gchar* _tmp263_ = NULL;
	TextEditor* _tmp264_ = NULL;
	GtkCheckButton* _tmp265_ = NULL;
	TextEditor* _tmp266_ = NULL;
	gboolean _tmp267_ = FALSE;
	gboolean _tmp268_ = FALSE;
	TextEditor* _tmp269_ = NULL;
	parent_class = G_OBJECT_CLASS (preferences_dialog_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PREFERENCES_DIALOG, PreferencesDialog);
	_tmp0_ = (GtkListBox*) gtk_list_box_new ();
	g_object_ref_sink (_tmp0_);
	box_view = _tmp0_;
	_tmp1_ = box_view;
	gtk_list_box_set_selection_mode (_tmp1_, GTK_SELECTION_NONE);
	_tmp2_ = (GtkListBox*) gtk_list_box_new ();
	g_object_ref_sink (_tmp2_);
	box_editor = _tmp2_;
	_tmp3_ = box_editor;
	gtk_list_box_set_selection_mode (_tmp3_, GTK_SELECTION_NONE);
	_tmp4_ = (GtkListBox*) gtk_list_box_new ();
	g_object_ref_sink (_tmp4_);
	box_typo = _tmp4_;
	_tmp5_ = box_typo;
	gtk_list_box_set_selection_mode (_tmp5_, GTK_SELECTION_NONE);
	_tmp6_ = (GtkStack*) gtk_stack_new ();
	g_object_ref_sink (_tmp6_);
	_g_object_unref0 (self->priv->stack);
	self->priv->stack = _tmp6_;
	_tmp7_ = self->priv->stack;
	gtk_stack_set_transition_type (_tmp7_, GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT);
	_tmp8_ = self->priv->stack;
	gtk_stack_set_transition_duration (_tmp8_, (guint) 300);
	_tmp9_ = (GtkStackSwitcher*) gtk_stack_switcher_new ();
	g_object_ref_sink (_tmp9_);
	_g_object_unref0 (self->priv->switcher);
	self->priv->switcher = _tmp9_;
	_tmp10_ = self->priv->switcher;
	_tmp11_ = self->priv->stack;
	gtk_stack_switcher_set_stack (_tmp10_, _tmp11_);
	_tmp12_ = gtk_dialog_get_header_bar ((GtkDialog*) self);
	_tmp13_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp12_, gtk_header_bar_get_type ()) ? ((GtkHeaderBar*) _tmp12_) : NULL);
	header_bar = _tmp13_;
	_tmp14_ = header_bar;
	_tmp15_ = self->priv->switcher;
	gtk_header_bar_set_custom_title (_tmp14_, (GtkWidget*) _tmp15_);
	_tmp16_ = (GtkBox*) gtk_dialog_get_content_area ((GtkDialog*) self);
	_tmp17_ = self->priv->stack;
	gtk_box_pack_start (_tmp16_, (GtkWidget*) _tmp17_, TRUE, TRUE, (guint) 0);
	_tmp18_ = (GtkBox*) gtk_dialog_get_content_area ((GtkDialog*) self);
	gtk_box_set_spacing (_tmp18_, 10);
	_tmp19_ = self->priv->stack;
	_tmp20_ = box_view;
	_tmp21_ = _ ("View");
	gtk_stack_add_titled (_tmp19_, (GtkWidget*) _tmp20_, "view", _tmp21_);
	_tmp22_ = self->priv->stack;
	_tmp23_ = box_editor;
	_tmp24_ = _ ("Editor");
	gtk_stack_add_titled (_tmp22_, (GtkWidget*) _tmp23_, "editor", _tmp24_);
	_tmp25_ = self->priv->stack;
	_tmp26_ = box_typo;
	_tmp27_ = _ ("Typography and colors");
	gtk_stack_add_titled (_tmp25_, (GtkWidget*) _tmp26_, "typo", _tmp27_);
	_tmp28_ = _ ("Show line numbers");
	_tmp29_ = (GtkCheckButton*) gtk_check_button_new_with_label (_tmp28_);
	g_object_ref_sink (_tmp29_);
	_g_object_unref0 (self->priv->line_numbers_check);
	self->priv->line_numbers_check = _tmp29_;
	_tmp30_ = self->priv->line_numbers_check;
	g_signal_connect_object ((GtkToggleButton*) _tmp30_, "toggled", (GCallback) __preferences_dialog___lambda24__gtk_toggle_button_toggled, self, 0);
	_tmp31_ = _ ("Show right margin on column:");
	_tmp32_ = (GtkCheckButton*) gtk_check_button_new_with_label (_tmp31_);
	g_object_ref_sink (_tmp32_);
	_g_object_unref0 (self->priv->right_margin_check);
	self->priv->right_margin_check = _tmp32_;
	_tmp33_ = self->priv->right_margin_check;
	g_signal_connect_object ((GtkToggleButton*) _tmp33_, "toggled", (GCallback) __preferences_dialog___lambda25__gtk_toggle_button_toggled, self, 0);
	_tmp34_ = (GtkSpinButton*) gtk_spin_button_new_with_range ((gdouble) 80, (gdouble) 120, (gdouble) 20);
	g_object_ref_sink (_tmp34_);
	_g_object_unref0 (self->priv->right_margin_spin);
	self->priv->right_margin_spin = _tmp34_;
	_tmp35_ = self->priv->right_margin_spin;
	_tmp36_ = self->priv->right_margin_check;
	_tmp37_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp36_);
	_tmp38_ = _tmp37_;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp35_, _tmp38_);
	_tmp39_ = self->priv->right_margin_spin;
	g_signal_connect_object (_tmp39_, "value-changed", (GCallback) __preferences_dialog___lambda26__gtk_spin_button_value_changed, self, 0);
	_tmp40_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp40_);
	hbox_margin = _tmp40_;
	_tmp41_ = hbox_margin;
	_tmp42_ = self->priv->right_margin_check;
	gtk_box_pack_start (_tmp41_, (GtkWidget*) _tmp42_, TRUE, TRUE, (guint) 0);
	_tmp43_ = hbox_margin;
	_tmp44_ = self->priv->right_margin_spin;
	gtk_box_pack_start (_tmp43_, (GtkWidget*) _tmp44_, TRUE, TRUE, (guint) 0);
	_tmp45_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp45_);
	aux_label_1 = _tmp45_;
	_tmp46_ = aux_label_1;
	gtk_widget_set_halign ((GtkWidget*) _tmp46_, GTK_ALIGN_START);
	_tmp47_ = _ ("Highlighting");
	_tmp48_ = g_strconcat ("<b>", _tmp47_, NULL);
	_tmp49_ = _tmp48_;
	_tmp50_ = g_strconcat (_tmp49_, "</b>", NULL);
	_tmp51_ = _tmp50_;
	_tmp52_ = (GtkLabel*) gtk_label_new (_tmp51_);
	g_object_ref_sink (_tmp52_);
	_tmp53_ = _tmp52_;
	_g_free0 (_tmp51_);
	_g_free0 (_tmp49_);
	highlight_label = _tmp53_;
	_tmp54_ = highlight_label;
	gtk_label_set_use_markup (_tmp54_, TRUE);
	_tmp55_ = highlight_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp55_, GTK_ALIGN_START);
	_tmp56_ = _ ("Highlight current line");
	_tmp57_ = (GtkCheckButton*) gtk_check_button_new_with_label (_tmp56_);
	g_object_ref_sink (_tmp57_);
	_g_object_unref0 (self->priv->current_line_check);
	self->priv->current_line_check = _tmp57_;
	_tmp58_ = self->priv->current_line_check;
	g_signal_connect_object ((GtkToggleButton*) _tmp58_, "toggled", (GCallback) __preferences_dialog___lambda27__gtk_toggle_button_toggled, self, 0);
	_tmp59_ = _ ("Highlight matching brackets");
	_tmp60_ = (GtkCheckButton*) gtk_check_button_new_with_label (_tmp59_);
	g_object_ref_sink (_tmp60_);
	_g_object_unref0 (self->priv->brackets_check);
	self->priv->brackets_check = _tmp60_;
	_tmp61_ = self->priv->brackets_check;
	g_signal_connect_object ((GtkToggleButton*) _tmp61_, "toggled", (GCallback) __preferences_dialog___lambda28__gtk_toggle_button_toggled, self, 0);
	_tmp62_ = _ ("Show grid pattern");
	_tmp63_ = (GtkCheckButton*) gtk_check_button_new_with_label (_tmp62_);
	g_object_ref_sink (_tmp63_);
	_g_object_unref0 (self->priv->grid_pattern_check);
	self->priv->grid_pattern_check = _tmp63_;
	_tmp64_ = self->priv->grid_pattern_check;
	g_signal_connect_object ((GtkToggleButton*) _tmp64_, "toggled", (GCallback) __preferences_dialog___lambda29__gtk_toggle_button_toggled, self, 0);
	_tmp65_ = box_view;
	_tmp66_ = self->priv->line_numbers_check;
	gtk_container_add ((GtkContainer*) _tmp65_, (GtkWidget*) _tmp66_);
	_tmp67_ = box_view;
	_tmp68_ = hbox_margin;
	gtk_container_add ((GtkContainer*) _tmp67_, (GtkWidget*) _tmp68_);
	_tmp69_ = box_view;
	_tmp70_ = self->priv->grid_pattern_check;
	gtk_container_add ((GtkContainer*) _tmp69_, (GtkWidget*) _tmp70_);
	_tmp71_ = box_view;
	_tmp72_ = aux_label_1;
	gtk_container_add ((GtkContainer*) _tmp71_, (GtkWidget*) _tmp72_);
	_tmp73_ = box_view;
	_tmp74_ = highlight_label;
	gtk_container_add ((GtkContainer*) _tmp73_, (GtkWidget*) _tmp74_);
	_tmp75_ = box_view;
	_tmp76_ = self->priv->current_line_check;
	gtk_container_add ((GtkContainer*) _tmp75_, (GtkWidget*) _tmp76_);
	_tmp77_ = box_view;
	_tmp78_ = self->priv->brackets_check;
	gtk_container_add ((GtkContainer*) _tmp77_, (GtkWidget*) _tmp78_);
	_tmp79_ = _ ("Indentation");
	_tmp80_ = g_strconcat ("<b>", _tmp79_, NULL);
	_tmp81_ = _tmp80_;
	_tmp82_ = g_strconcat (_tmp81_, "</b>", NULL);
	_tmp83_ = _tmp82_;
	_tmp84_ = (GtkLabel*) gtk_label_new (_tmp83_);
	g_object_ref_sink (_tmp84_);
	_tmp85_ = _tmp84_;
	_g_free0 (_tmp83_);
	_g_free0 (_tmp81_);
	indent_label = _tmp85_;
	_tmp86_ = indent_label;
	gtk_label_set_use_markup (_tmp86_, TRUE);
	_tmp87_ = indent_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp87_, GTK_ALIGN_START);
	_tmp88_ = _ ("Tab width:");
	_tmp89_ = (GtkLabel*) gtk_label_new (_tmp88_);
	g_object_ref_sink (_tmp89_);
	tab_width_label = _tmp89_;
	_tmp90_ = tab_width_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp90_, GTK_ALIGN_START);
	_tmp91_ = (GtkComboBox*) gtk_combo_box_new ();
	g_object_ref_sink (_tmp91_);
	_g_object_unref0 (self->priv->tab_width_combo);
	self->priv->tab_width_combo = _tmp91_;
	_tmp92_ = tab_width_label;
	_tmp93_ = self->priv->tab_width_combo;
	gtk_label_set_mnemonic_widget (_tmp92_, (GtkWidget*) _tmp93_);
	_tmp94_ = gtk_list_store_new (1, G_TYPE_INT, -1);
	model = _tmp94_;
	_tmp95_ = self->priv->tab_width_combo;
	_tmp96_ = model;
	gtk_combo_box_set_model (_tmp95_, (GtkTreeModel*) _tmp96_);
	_tmp97_ = model;
	gtk_list_store_append (_tmp97_, &_tmp98_);
	iter = _tmp98_;
	_tmp99_ = model;
	_tmp100_ = iter;
	gtk_list_store_set (_tmp99_, &_tmp100_, 0, 2, -1, -1);
	_tmp101_ = model;
	gtk_list_store_append (_tmp101_, &_tmp102_);
	iter = _tmp102_;
	_tmp103_ = model;
	_tmp104_ = iter;
	gtk_list_store_set (_tmp103_, &_tmp104_, 0, 3, -1, -1);
	_tmp105_ = model;
	gtk_list_store_append (_tmp105_, &_tmp106_);
	iter = _tmp106_;
	_tmp107_ = model;
	_tmp108_ = iter;
	gtk_list_store_set (_tmp107_, &_tmp108_, 0, 4, -1, -1);
	_tmp109_ = model;
	gtk_list_store_append (_tmp109_, &_tmp110_);
	iter = _tmp110_;
	_tmp111_ = model;
	_tmp112_ = iter;
	gtk_list_store_set (_tmp111_, &_tmp112_, 0, 8, -1, -1);
	_tmp113_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp113_);
	renderer = _tmp113_;
	_tmp114_ = self->priv->tab_width_combo;
	_tmp115_ = renderer;
	gtk_cell_layout_pack_start ((GtkCellLayout*) _tmp114_, (GtkCellRenderer*) _tmp115_, TRUE);
	_tmp116_ = self->priv->tab_width_combo;
	_tmp117_ = renderer;
	gtk_cell_layout_add_attribute ((GtkCellLayout*) _tmp116_, (GtkCellRenderer*) _tmp117_, "text", 0);
	_tmp118_ = self->priv->tab_width_combo;
	g_signal_connect_object (_tmp118_, "changed", (GCallback) _preferences_dialog_on_tab_width_changed_gtk_combo_box_changed, self, 0);
	_tmp119_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp119_);
	hbox_tab_width = _tmp119_;
	_tmp120_ = hbox_tab_width;
	_tmp121_ = tab_width_label;
	gtk_box_pack_start (_tmp120_, (GtkWidget*) _tmp121_, TRUE, TRUE, (guint) 0);
	_tmp122_ = hbox_tab_width;
	_tmp123_ = self->priv->tab_width_combo;
	gtk_box_pack_start (_tmp122_, (GtkWidget*) _tmp123_, TRUE, TRUE, (guint) 0);
	_tmp124_ = _ ("Indent using spaces");
	_tmp125_ = (GtkCheckButton*) gtk_check_button_new_with_label (_tmp124_);
	g_object_ref_sink (_tmp125_);
	_g_object_unref0 (self->priv->insert_spaces_check);
	self->priv->insert_spaces_check = _tmp125_;
	_tmp126_ = self->priv->insert_spaces_check;
	g_signal_connect_object ((GtkToggleButton*) _tmp126_, "toggled", (GCallback) __preferences_dialog___lambda30__gtk_toggle_button_toggled, self, 0);
	_tmp127_ = _ ("Activate auto indent");
	_tmp128_ = (GtkCheckButton*) gtk_check_button_new_with_label (_tmp127_);
	g_object_ref_sink (_tmp128_);
	_g_object_unref0 (self->priv->auto_indent_check);
	self->priv->auto_indent_check = _tmp128_;
	_tmp129_ = self->priv->auto_indent_check;
	g_signal_connect_object ((GtkToggleButton*) _tmp129_, "toggled", (GCallback) __preferences_dialog___lambda31__gtk_toggle_button_toggled, self, 0);
	_tmp130_ = box_editor;
	_tmp131_ = indent_label;
	gtk_container_add ((GtkContainer*) _tmp130_, (GtkWidget*) _tmp131_);
	_tmp132_ = box_editor;
	_tmp133_ = hbox_tab_width;
	gtk_container_add ((GtkContainer*) _tmp132_, (GtkWidget*) _tmp133_);
	_tmp134_ = box_editor;
	_tmp135_ = self->priv->insert_spaces_check;
	gtk_container_add ((GtkContainer*) _tmp134_, (GtkWidget*) _tmp135_);
	_tmp136_ = box_editor;
	_tmp137_ = self->priv->auto_indent_check;
	gtk_container_add ((GtkContainer*) _tmp136_, (GtkWidget*) _tmp137_);
	_tmp138_ = _ ("Typography");
	_tmp139_ = g_strconcat ("<b>", _tmp138_, NULL);
	_tmp140_ = _tmp139_;
	_tmp141_ = g_strconcat (_tmp140_, "</b>", NULL);
	_tmp142_ = _tmp141_;
	_tmp143_ = (GtkLabel*) gtk_label_new (_tmp142_);
	g_object_ref_sink (_tmp143_);
	_tmp144_ = _tmp143_;
	_g_free0 (_tmp142_);
	_g_free0 (_tmp140_);
	typo_label = _tmp144_;
	_tmp145_ = typo_label;
	gtk_label_set_use_markup (_tmp145_, TRUE);
	_tmp146_ = typo_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp146_, GTK_ALIGN_START);
	_tmp147_ = _ ("Use default typography");
	_tmp148_ = g_strconcat (_tmp147_, " (Monospace 10)", NULL);
	_tmp149_ = _tmp148_;
	_tmp150_ = (GtkCheckButton*) gtk_check_button_new_with_label (_tmp149_);
	g_object_ref_sink (_tmp150_);
	_g_object_unref0 (self->priv->default_typo_check);
	self->priv->default_typo_check = _tmp150_;
	_g_free0 (_tmp149_);
	_tmp151_ = self->priv->default_typo_check;
	g_signal_connect_object ((GtkToggleButton*) _tmp151_, "toggled", (GCallback) __preferences_dialog___lambda32__gtk_toggle_button_toggled, self, 0);
	_tmp152_ = (GtkFontButton*) gtk_font_button_new ();
	g_object_ref_sink (_tmp152_);
	_g_object_unref0 (self->priv->font_button);
	self->priv->font_button = _tmp152_;
	_tmp153_ = self->priv->font_button;
	_tmp154_ = self->priv->default_typo_check;
	_tmp155_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp154_);
	_tmp156_ = _tmp155_;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp153_, !_tmp156_);
	_tmp157_ = self->priv->font_button;
	gtk_font_button_set_use_font (_tmp157_, TRUE);
	_tmp158_ = self->priv->font_button;
	g_signal_connect_object (_tmp158_, "font-set", (GCallback) __preferences_dialog___lambda33__gtk_font_button_font_set, self, 0);
	_tmp159_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp159_);
	aux_label_3 = _tmp159_;
	_tmp160_ = aux_label_3;
	gtk_widget_set_halign ((GtkWidget*) _tmp160_, GTK_ALIGN_START);
	_tmp161_ = _ ("Color Scheme");
	_tmp162_ = g_strconcat ("<b>", _tmp161_, NULL);
	_tmp163_ = _tmp162_;
	_tmp164_ = g_strconcat (_tmp163_, "</b>", NULL);
	_tmp165_ = _tmp164_;
	_tmp166_ = (GtkLabel*) gtk_label_new (_tmp165_);
	g_object_ref_sink (_tmp166_);
	_tmp167_ = _tmp166_;
	_g_free0 (_tmp165_);
	_g_free0 (_tmp163_);
	color_scheme_label = _tmp167_;
	_tmp168_ = color_scheme_label;
	gtk_label_set_use_markup (_tmp168_, TRUE);
	_tmp169_ = color_scheme_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp169_, GTK_ALIGN_START);
	_tmp170_ = gtk_source_style_scheme_manager_get_default ();
	_tmp171_ = _g_object_ref0 (_tmp170_);
	scheme_manager = _tmp171_;
	_tmp172_ = scheme_manager;
	gtk_source_style_scheme_manager_append_search_path (_tmp172_, "/opt/simple-text/style_schemes");
	_tmp173_ = (GtkListBox*) gtk_list_box_new ();
	g_object_ref_sink (_tmp173_);
	_g_object_unref0 (self->priv->scheme_chooser);
	self->priv->scheme_chooser = _tmp173_;
	_tmp174_ = self->priv->scheme_chooser;
	gtk_list_box_set_selection_mode (_tmp174_, GTK_SELECTION_SINGLE);
	_tmp175_ = self->priv->scheme_chooser;
	gtk_list_box_set_activate_on_single_click (_tmp175_, TRUE);
	_tmp176_ = self->priv->scheme_chooser;
	g_signal_connect_object (_tmp176_, "row-activated", (GCallback) _preferences_dialog_on_scheme_selected_gtk_list_box_row_activated, self, 0);
	_tmp177_ = scheme_manager;
	_tmp178_ = gtk_source_style_scheme_manager_get_scheme_ids (_tmp177_);
	_tmp178__length1 = _vala_array_length (_tmp178_);
	_tmp179_ = _tmp178_;
	_tmp179__length1 = _tmp178__length1;
	{
		gchar** scheme_collection = NULL;
		gint scheme_collection_length1 = 0;
		gint _scheme_collection_size_ = 0;
		gint scheme_it = 0;
		scheme_collection = _tmp179_;
		scheme_collection_length1 = _tmp179__length1;
		for (scheme_it = 0; scheme_it < _tmp179__length1; scheme_it = scheme_it + 1) {
			gchar* _tmp180_ = NULL;
			gchar* scheme = NULL;
			_tmp180_ = g_strdup (scheme_collection[scheme_it]);
			scheme = _tmp180_;
			{
				GtkLabel* label = NULL;
				const gchar* _tmp181_ = NULL;
				GtkLabel* _tmp182_ = NULL;
				GtkListBox* _tmp183_ = NULL;
				GtkLabel* _tmp184_ = NULL;
				_tmp181_ = scheme;
				_tmp182_ = (GtkLabel*) gtk_label_new (_tmp181_);
				g_object_ref_sink (_tmp182_);
				label = _tmp182_;
				_tmp183_ = self->priv->scheme_chooser;
				_tmp184_ = label;
				gtk_container_add ((GtkContainer*) _tmp183_, (GtkWidget*) _tmp184_);
				_g_object_unref0 (label);
				_g_free0 (scheme);
			}
		}
	}
	_tmp185_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp185_);
	scroll = _tmp185_;
	_tmp186_ = scroll;
	gtk_scrolled_window_set_policy (_tmp186_, GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
	_tmp187_ = scroll;
	g_object_set ((GtkWidget*) _tmp187_, "height-request", 100, NULL);
	_tmp188_ = scroll;
	_tmp189_ = self->priv->scheme_chooser;
	gtk_container_add ((GtkContainer*) _tmp188_, (GtkWidget*) _tmp189_);
	_tmp190_ = (GtkFrame*) gtk_frame_new (NULL);
	g_object_ref_sink (_tmp190_);
	frame = _tmp190_;
	_tmp191_ = frame;
	_tmp192_ = scroll;
	gtk_container_add ((GtkContainer*) _tmp191_, (GtkWidget*) _tmp192_);
	_tmp193_ = _ ("Use dark theme variant");
	_tmp194_ = (GtkCheckButton*) gtk_check_button_new_with_label (_tmp193_);
	g_object_ref_sink (_tmp194_);
	_g_object_unref0 (self->priv->prefer_dark_check);
	self->priv->prefer_dark_check = _tmp194_;
	_tmp195_ = self->priv->prefer_dark_check;
	g_signal_connect_object ((GtkToggleButton*) _tmp195_, "toggled", (GCallback) __preferences_dialog___lambda34__gtk_toggle_button_toggled, self, 0);
	_tmp196_ = box_typo;
	_tmp197_ = typo_label;
	gtk_container_add ((GtkContainer*) _tmp196_, (GtkWidget*) _tmp197_);
	_tmp198_ = box_typo;
	_tmp199_ = self->priv->default_typo_check;
	gtk_container_add ((GtkContainer*) _tmp198_, (GtkWidget*) _tmp199_);
	_tmp200_ = box_typo;
	_tmp201_ = self->priv->font_button;
	gtk_container_add ((GtkContainer*) _tmp200_, (GtkWidget*) _tmp201_);
	_tmp202_ = box_typo;
	_tmp203_ = aux_label_3;
	gtk_container_add ((GtkContainer*) _tmp202_, (GtkWidget*) _tmp203_);
	_tmp204_ = box_typo;
	_tmp205_ = color_scheme_label;
	gtk_container_add ((GtkContainer*) _tmp204_, (GtkWidget*) _tmp205_);
	_tmp206_ = box_typo;
	_tmp207_ = frame;
	gtk_container_add ((GtkContainer*) _tmp206_, (GtkWidget*) _tmp207_);
	_tmp208_ = box_typo;
	_tmp209_ = self->priv->prefer_dark_check;
	gtk_container_add ((GtkContainer*) _tmp208_, (GtkWidget*) _tmp209_);
	gtk_widget_show_all ((GtkWidget*) self);
	_tmp210_ = self->priv->line_numbers_check;
	_tmp211_ = self->priv->_editor;
	_tmp212_ = text_editor_get_show_line_numbers (_tmp211_);
	_tmp213_ = _tmp212_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp210_, _tmp213_);
	_tmp214_ = self->priv->_editor;
	g_signal_connect_object ((GObject*) _tmp214_, "notify::show-line-numbers", (GCallback) __preferences_dialog___lambda35__g_object_notify, self, 0);
	_tmp215_ = self->priv->right_margin_check;
	_tmp216_ = self->priv->_editor;
	_tmp217_ = text_editor_get_show_right_margin (_tmp216_);
	_tmp218_ = _tmp217_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp215_, _tmp218_);
	_tmp219_ = self->priv->_editor;
	g_signal_connect_object ((GObject*) _tmp219_, "notify::show-right-margin", (GCallback) __preferences_dialog___lambda36__g_object_notify, self, 0);
	_tmp220_ = self->priv->right_margin_spin;
	_tmp221_ = self->priv->_editor;
	_tmp222_ = text_editor_get_right_margin_at (_tmp221_);
	_tmp223_ = _tmp222_;
	gtk_spin_button_set_value (_tmp220_, (gdouble) _tmp223_);
	_tmp224_ = self->priv->_editor;
	g_signal_connect_object ((GObject*) _tmp224_, "notify::right-margin-at", (GCallback) __preferences_dialog___lambda37__g_object_notify, self, 0);
	_tmp225_ = self->priv->current_line_check;
	_tmp226_ = self->priv->_editor;
	_tmp227_ = text_editor_get_highlight_current_line (_tmp226_);
	_tmp228_ = _tmp227_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp225_, _tmp228_);
	_tmp229_ = self->priv->_editor;
	g_signal_connect_object ((GObject*) _tmp229_, "notify::highlight-current-line", (GCallback) __preferences_dialog___lambda38__g_object_notify, self, 0);
	_tmp230_ = self->priv->brackets_check;
	_tmp231_ = self->priv->_editor;
	_tmp232_ = text_editor_get_highlight_brackets (_tmp231_);
	_tmp233_ = _tmp232_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp230_, _tmp233_);
	_tmp234_ = self->priv->_editor;
	g_signal_connect_object ((GObject*) _tmp234_, "notify::highlight-brackets", (GCallback) __preferences_dialog___lambda39__g_object_notify, self, 0);
	_tmp235_ = self->priv->tab_width_combo;
	_tmp236_ = self->priv->_editor;
	_tmp237_ = text_editor_get_tab_width (_tmp236_);
	_tmp238_ = _tmp237_;
	preferences_dialog_set_combo_box_from_int (self, _tmp235_, _tmp238_);
	_tmp239_ = self->priv->_editor;
	g_signal_connect_object ((GObject*) _tmp239_, "notify::tab-width", (GCallback) __preferences_dialog___lambda40__g_object_notify, self, 0);
	_tmp240_ = self->priv->insert_spaces_check;
	_tmp241_ = self->priv->_editor;
	_tmp242_ = text_editor_get_insert_spaces (_tmp241_);
	_tmp243_ = _tmp242_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp240_, _tmp243_);
	_tmp244_ = self->priv->_editor;
	g_signal_connect_object ((GObject*) _tmp244_, "notify::insert-spaces", (GCallback) __preferences_dialog___lambda41__g_object_notify, self, 0);
	_tmp245_ = self->priv->auto_indent_check;
	_tmp246_ = self->priv->_editor;
	_tmp247_ = text_editor_get_auto_indent (_tmp246_);
	_tmp248_ = _tmp247_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp245_, _tmp248_);
	_tmp249_ = self->priv->_editor;
	g_signal_connect_object ((GObject*) _tmp249_, "notify::auto-indent", (GCallback) __preferences_dialog___lambda42__g_object_notify, self, 0);
	_tmp250_ = self->priv->grid_pattern_check;
	_tmp251_ = self->priv->_editor;
	_tmp252_ = text_editor_get_show_grid_pattern (_tmp251_);
	_tmp253_ = _tmp252_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp250_, _tmp253_);
	_tmp254_ = self->priv->_editor;
	g_signal_connect_object ((GObject*) _tmp254_, "notify::show-grid-pattern", (GCallback) __preferences_dialog___lambda43__g_object_notify, self, 0);
	_tmp255_ = self->priv->default_typo_check;
	_tmp256_ = self->priv->_editor;
	_tmp257_ = text_editor_get_use_default_typo (_tmp256_);
	_tmp258_ = _tmp257_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp255_, _tmp258_);
	_tmp259_ = self->priv->_editor;
	g_signal_connect_object ((GObject*) _tmp259_, "notify::use-default-typo", (GCallback) __preferences_dialog___lambda44__g_object_notify, self, 0);
	_tmp260_ = self->priv->font_button;
	_tmp261_ = self->priv->_editor;
	_tmp262_ = text_editor_get_editor_font (_tmp261_);
	_tmp263_ = _tmp262_;
	gtk_font_button_set_font_name (_tmp260_, _tmp263_);
	_tmp264_ = self->priv->_editor;
	g_signal_connect_object ((GObject*) _tmp264_, "notify::editor-font", (GCallback) __preferences_dialog___lambda45__g_object_notify, self, 0);
	_tmp265_ = self->priv->prefer_dark_check;
	_tmp266_ = self->priv->_editor;
	_tmp267_ = text_editor_get_prefer_dark (_tmp266_);
	_tmp268_ = _tmp267_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp265_, _tmp268_);
	_tmp269_ = self->priv->_editor;
	g_signal_connect_object ((GObject*) _tmp269_, "notify::prefer-dark", (GCallback) __preferences_dialog___lambda46__g_object_notify, self, 0);
	_g_object_unref0 (frame);
	_g_object_unref0 (scroll);
	_g_object_unref0 (scheme_manager);
	_g_object_unref0 (color_scheme_label);
	_g_object_unref0 (aux_label_3);
	_g_object_unref0 (typo_label);
	_g_object_unref0 (hbox_tab_width);
	_g_object_unref0 (renderer);
	_g_object_unref0 (model);
	_g_object_unref0 (tab_width_label);
	_g_object_unref0 (indent_label);
	_g_object_unref0 (highlight_label);
	_g_object_unref0 (aux_label_1);
	_g_object_unref0 (hbox_margin);
	_g_object_unref0 (header_bar);
	_g_object_unref0 (box_typo);
	_g_object_unref0 (box_editor);
	_g_object_unref0 (box_view);
	return obj;
}


static void preferences_dialog_class_init (PreferencesDialogClass * klass) {
	preferences_dialog_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PreferencesDialogPrivate));
	((GtkDialogClass *) klass)->response = preferences_dialog_real_response;
	((GtkWidgetClass *) klass)->delete_event = preferences_dialog_real_delete_event;
	G_OBJECT_CLASS (klass)->get_property = _vala_preferences_dialog_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_preferences_dialog_set_property;
	G_OBJECT_CLASS (klass)->constructor = preferences_dialog_constructor;
	G_OBJECT_CLASS (klass)->finalize = preferences_dialog_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), PREFERENCES_DIALOG_EDITOR, g_param_spec_object ("editor", "editor", "editor", TYPE_TEXT_EDITOR, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
}


static void preferences_dialog_instance_init (PreferencesDialog * self) {
	self->priv = PREFERENCES_DIALOG_GET_PRIVATE (self);
}


static void preferences_dialog_finalize (GObject* obj) {
	PreferencesDialog * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PREFERENCES_DIALOG, PreferencesDialog);
	_g_object_unref0 (self->priv->_editor);
	_g_object_unref0 (self->priv->switcher);
	_g_object_unref0 (self->priv->stack);
	_g_object_unref0 (self->priv->line_numbers_check);
	_g_object_unref0 (self->priv->right_margin_check);
	_g_object_unref0 (self->priv->right_margin_spin);
	_g_object_unref0 (self->priv->current_line_check);
	_g_object_unref0 (self->priv->brackets_check);
	_g_object_unref0 (self->priv->tab_width_combo);
	_g_object_unref0 (self->priv->insert_spaces_check);
	_g_object_unref0 (self->priv->auto_indent_check);
	_g_object_unref0 (self->priv->grid_pattern_check);
	_g_object_unref0 (self->priv->default_typo_check);
	_g_object_unref0 (self->priv->font_button);
	_g_object_unref0 (self->priv->scheme_chooser);
	_g_object_unref0 (self->priv->prefer_dark_check);
	G_OBJECT_CLASS (preferences_dialog_parent_class)->finalize (obj);
}


GType preferences_dialog_get_type (void) {
	static volatile gsize preferences_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&preferences_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PreferencesDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) preferences_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PreferencesDialog), 0, (GInstanceInitFunc) preferences_dialog_instance_init, NULL };
		GType preferences_dialog_type_id;
		preferences_dialog_type_id = g_type_register_static (gtk_dialog_get_type (), "PreferencesDialog", &g_define_type_info, 0);
		g_once_init_leave (&preferences_dialog_type_id__volatile, preferences_dialog_type_id);
	}
	return preferences_dialog_type_id__volatile;
}


static void _vala_preferences_dialog_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	PreferencesDialog * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_PREFERENCES_DIALOG, PreferencesDialog);
	switch (property_id) {
		case PREFERENCES_DIALOG_EDITOR:
		g_value_set_object (value, preferences_dialog_get_editor (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_preferences_dialog_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	PreferencesDialog * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_PREFERENCES_DIALOG, PreferencesDialog);
	switch (property_id) {
		case PREFERENCES_DIALOG_EDITOR:
		preferences_dialog_set_editor (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



