/* simple-text.c generated by valac 0.28.0, the Vala compiler
 * generated from simple-text.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <locale.h>
#include <config.h>


#define TYPE_SIMPLE_TEXT (simple_text_get_type ())
#define SIMPLE_TEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SIMPLE_TEXT, SimpleText))
#define SIMPLE_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SIMPLE_TEXT, SimpleTextClass))
#define IS_SIMPLE_TEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SIMPLE_TEXT))
#define IS_SIMPLE_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SIMPLE_TEXT))
#define SIMPLE_TEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SIMPLE_TEXT, SimpleTextClass))

typedef struct _SimpleText SimpleText;
typedef struct _SimpleTextClass SimpleTextClass;
typedef struct _SimpleTextPrivate SimpleTextPrivate;

#define TYPE_PREFERENCES_DIALOG (preferences_dialog_get_type ())
#define PREFERENCES_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PREFERENCES_DIALOG, PreferencesDialog))
#define PREFERENCES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PREFERENCES_DIALOG, PreferencesDialogClass))
#define IS_PREFERENCES_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PREFERENCES_DIALOG))
#define IS_PREFERENCES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PREFERENCES_DIALOG))
#define PREFERENCES_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PREFERENCES_DIALOG, PreferencesDialogClass))

typedef struct _PreferencesDialog PreferencesDialog;
typedef struct _PreferencesDialogClass PreferencesDialogClass;

#define TYPE_MAIN_WINDOW (main_window_get_type ())
#define MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_WINDOW, MainWindow))
#define MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_WINDOW, MainWindowClass))
#define IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_WINDOW))
#define IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_WINDOW))
#define MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_WINDOW, MainWindowClass))

typedef struct _MainWindow MainWindow;
typedef struct _MainWindowClass MainWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define TYPE_TEXT_EDITOR (text_editor_get_type ())
#define TEXT_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXT_EDITOR, TextEditor))
#define TEXT_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXT_EDITOR, TextEditorClass))
#define IS_TEXT_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXT_EDITOR))
#define IS_TEXT_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXT_EDITOR))
#define TEXT_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXT_EDITOR, TextEditorClass))

typedef struct _TextEditor TextEditor;
typedef struct _TextEditorClass TextEditorClass;

struct _SimpleText {
	GtkApplication parent_instance;
	SimpleTextPrivate * priv;
};

struct _SimpleTextClass {
	GtkApplicationClass parent_class;
};

struct _SimpleTextPrivate {
	GSettings* settings;
	PreferencesDialog* preferences_dialog;
	MainWindow* window;
};


static gpointer simple_text_parent_class = NULL;

GType simple_text_get_type (void) G_GNUC_CONST;
GType preferences_dialog_get_type (void) G_GNUC_CONST;
GType main_window_get_type (void) G_GNUC_CONST;
#define SIMPLE_TEXT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SIMPLE_TEXT, SimpleTextPrivate))
enum  {
	SIMPLE_TEXT_DUMMY_PROPERTY
};
static void simple_text_show_prefs_cb (SimpleText* self);
static void _simple_text_show_prefs_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self);
static void simple_text_about_cb (SimpleText* self);
static void _simple_text_about_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self);
static void simple_text_quit_cb (SimpleText* self);
static void _simple_text_quit_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self);
SimpleText* simple_text_new (void);
SimpleText* simple_text_construct (GType object_type);
static void simple_text_real_startup (GApplication* base);
GType text_editor_get_type (void) G_GNUC_CONST;
TextEditor* text_editor_new (void);
TextEditor* text_editor_construct (GType object_type);
void text_editor_set_show_line_numbers (TextEditor* self, gboolean value);
void text_editor_set_show_right_margin (TextEditor* self, gboolean value);
void text_editor_set_right_margin_at (TextEditor* self, gint value);
void text_editor_set_use_text_wrap (TextEditor* self, gboolean value);
void text_editor_set_highlight_current_line (TextEditor* self, gboolean value);
void text_editor_set_highlight_brackets (TextEditor* self, gboolean value);
void text_editor_set_show_grid_pattern (TextEditor* self, gboolean value);
void text_editor_set_tab_width (TextEditor* self, gint value);
void text_editor_set_insert_spaces (TextEditor* self, gboolean value);
void text_editor_set_auto_indent (TextEditor* self, gboolean value);
void text_editor_set_use_default_typo (TextEditor* self, gboolean value);
void text_editor_set_editor_font (TextEditor* self, const gchar* value);
void text_editor_set_color_scheme (TextEditor* self, const gchar* value);
void text_editor_set_prefer_dark (TextEditor* self, gboolean value);
MainWindow* main_window_new (GtkApplication* app, TextEditor* editor);
MainWindow* main_window_construct (GType object_type, GtkApplication* app, TextEditor* editor);
static void simple_text_real_activate (GApplication* base);
void main_window_set_arg_files (MainWindow* self, GFile** value, int value_length1);
static void simple_text_real_open (GApplication* base, GFile** files, int files_length1, const gchar* hint);
static void simple_text_real_shutdown (GApplication* base);
TextEditor* main_window_get_editor (MainWindow* self);
gboolean text_editor_get_show_line_numbers (TextEditor* self);
gboolean text_editor_get_show_right_margin (TextEditor* self);
gint text_editor_get_right_margin_at (TextEditor* self);
gboolean text_editor_get_use_text_wrap (TextEditor* self);
gboolean text_editor_get_highlight_current_line (TextEditor* self);
gboolean text_editor_get_highlight_brackets (TextEditor* self);
gboolean text_editor_get_show_grid_pattern (TextEditor* self);
gint text_editor_get_tab_width (TextEditor* self);
gboolean text_editor_get_insert_spaces (TextEditor* self);
gboolean text_editor_get_auto_indent (TextEditor* self);
gboolean text_editor_get_use_default_typo (TextEditor* self);
const gchar* text_editor_get_editor_font (TextEditor* self);
const gchar* text_editor_get_color_scheme (TextEditor* self);
gboolean text_editor_get_prefer_dark (TextEditor* self);
PreferencesDialog* preferences_dialog_new (MainWindow* parent, TextEditor* ed);
PreferencesDialog* preferences_dialog_construct (GType object_type, MainWindow* parent, TextEditor* ed);
gint simple_text_main (gchar** args, int args_length1);
static void simple_text_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);

static const GActionEntry SIMPLE_TEXT_app_entries[3] = {{"prefs", _simple_text_show_prefs_cb_gsimple_action_activate_callback, NULL, NULL, NULL}, {"about", _simple_text_about_cb_gsimple_action_activate_callback, NULL, NULL, NULL}, {"quit", _simple_text_quit_cb_gsimple_action_activate_callback, NULL, NULL, NULL}};

static void _simple_text_show_prefs_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self) {
	simple_text_show_prefs_cb ((SimpleText*) self);
}


static void _simple_text_about_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self) {
	simple_text_about_cb ((SimpleText*) self);
}


static void _simple_text_quit_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self) {
	simple_text_quit_cb ((SimpleText*) self);
}


SimpleText* simple_text_construct (GType object_type) {
	SimpleText * self = NULL;
	self = (SimpleText*) g_object_new (object_type, "application-id", "badwolfie.simple-text.app", "flags", G_APPLICATION_HANDLES_OPEN, NULL);
	return self;
}


SimpleText* simple_text_new (void) {
	return simple_text_construct (TYPE_SIMPLE_TEXT);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void simple_text_real_startup (GApplication* base) {
	SimpleText * self;
	GFile* conf_dir = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	GFile* _tmp3_ = NULL;
	GFile* _tmp4_ = NULL;
	GFile* saved_workspace = NULL;
	const gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	GFile* _tmp8_ = NULL;
	GFile* _tmp9_ = NULL;
	TextEditor* editor = NULL;
	TextEditor* _tmp19_ = NULL;
	GSettings* _tmp20_ = NULL;
	GSettings* _tmp21_ = NULL;
	gboolean _tmp22_ = FALSE;
	GSettings* _tmp23_ = NULL;
	gboolean _tmp24_ = FALSE;
	GSettings* _tmp25_ = NULL;
	gint _tmp26_ = 0;
	GSettings* _tmp27_ = NULL;
	gboolean _tmp28_ = FALSE;
	GSettings* _tmp29_ = NULL;
	gboolean _tmp30_ = FALSE;
	GSettings* _tmp31_ = NULL;
	gboolean _tmp32_ = FALSE;
	GSettings* _tmp33_ = NULL;
	gboolean _tmp34_ = FALSE;
	GSettings* _tmp35_ = NULL;
	gint _tmp36_ = 0;
	GSettings* _tmp37_ = NULL;
	gboolean _tmp38_ = FALSE;
	GSettings* _tmp39_ = NULL;
	gboolean _tmp40_ = FALSE;
	GSettings* _tmp41_ = NULL;
	gboolean _tmp42_ = FALSE;
	GSettings* _tmp43_ = NULL;
	gchar* _tmp44_ = NULL;
	gchar* _tmp45_ = NULL;
	GSettings* _tmp46_ = NULL;
	gchar* _tmp47_ = NULL;
	gchar* _tmp48_ = NULL;
	GSettings* _tmp49_ = NULL;
	gboolean _tmp50_ = FALSE;
	MainWindow* _tmp51_ = NULL;
	GtkBuilder* builder = NULL;
	GtkBuilder* _tmp52_ = NULL;
	GMenuModel* menu = NULL;
	GObject* _tmp54_ = NULL;
	GMenuModel* _tmp55_ = NULL;
	static const gchar* accels_re_open[] = {"<control><shift>T", NULL};
	static const gchar* accels_save_as[] = {"<control><shift>S", NULL};
	static const gchar* accels_set_syntax[] = {"<control><shift>P", NULL};
	static const gchar* accels_show_terminal[] = {"<control><shift>C", NULL};
	static const gchar* accels_next_tab[] = {"<control>Tab", NULL};
	static const gchar* accels_prev_tab[] = {"<control><shift>Tab", NULL};
	static const gchar* accels_close[] = {"<control>W", NULL};
	static const gchar* accels_search[] = {"<control>F", NULL};
	static const gchar* accels_quit[] = {"<control>Q", NULL};
	GError * _inner_error_ = NULL;
	self = (SimpleText*) base;
	G_APPLICATION_CLASS (simple_text_parent_class)->startup ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
	_tmp0_ = g_get_home_dir ();
	_tmp1_ = g_strconcat (_tmp0_, "/.simple-text", NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_file_new_for_path (_tmp2_);
	_tmp4_ = _tmp3_;
	_g_free0 (_tmp2_);
	conf_dir = _tmp4_;
	_tmp5_ = g_get_home_dir ();
	_tmp6_ = g_strconcat (_tmp5_, "/.simple-text/saved-workspace", NULL);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_file_new_for_path (_tmp7_);
	_tmp9_ = _tmp8_;
	_g_free0 (_tmp7_);
	saved_workspace = _tmp9_;
	{
		GFile* _tmp10_ = NULL;
		gboolean _tmp11_ = FALSE;
		GFile* _tmp13_ = NULL;
		gboolean _tmp14_ = FALSE;
		_tmp10_ = conf_dir;
		_tmp11_ = g_file_query_exists (_tmp10_, NULL);
		if (!_tmp11_) {
			GFile* _tmp12_ = NULL;
			_tmp12_ = conf_dir;
			g_file_make_directory (_tmp12_, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch7_g_error;
			}
		}
		_tmp13_ = saved_workspace;
		_tmp14_ = g_file_query_exists (_tmp13_, NULL);
		if (!_tmp14_) {
			GFile* _tmp15_ = NULL;
			GFileOutputStream* _tmp16_ = NULL;
			GFileOutputStream* _tmp17_ = NULL;
			_tmp15_ = saved_workspace;
			_tmp16_ = g_file_create (_tmp15_, G_FILE_CREATE_PRIVATE, NULL, &_inner_error_);
			_tmp17_ = _tmp16_;
			_g_object_unref0 (_tmp17_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch7_g_error;
			}
		}
	}
	goto __finally7;
	__catch7_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp18_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp18_ = e->message;
		g_error ("simple-text.vala:35: Error loading menu UI: %s", _tmp18_);
		_g_error_free0 (e);
	}
	__finally7:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (saved_workspace);
		_g_object_unref0 (conf_dir);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp19_ = text_editor_new ();
	editor = _tmp19_;
	_tmp20_ = g_settings_new ("com.github.badwolfie.simple-text");
	_g_object_unref0 (self->priv->settings);
	self->priv->settings = _tmp20_;
	_tmp21_ = self->priv->settings;
	_tmp22_ = g_settings_get_boolean (_tmp21_, "show-line-numbers");
	text_editor_set_show_line_numbers (editor, _tmp22_);
	_tmp23_ = self->priv->settings;
	_tmp24_ = g_settings_get_boolean (_tmp23_, "show-right-margin");
	text_editor_set_show_right_margin (editor, _tmp24_);
	_tmp25_ = self->priv->settings;
	_tmp26_ = g_settings_get_int (_tmp25_, "right-margin-at");
	text_editor_set_right_margin_at (editor, _tmp26_);
	_tmp27_ = self->priv->settings;
	_tmp28_ = g_settings_get_boolean (_tmp27_, "use-text-wrap");
	text_editor_set_use_text_wrap (editor, _tmp28_);
	_tmp29_ = self->priv->settings;
	_tmp30_ = g_settings_get_boolean (_tmp29_, "highlight-current-line");
	text_editor_set_highlight_current_line (editor, _tmp30_);
	_tmp31_ = self->priv->settings;
	_tmp32_ = g_settings_get_boolean (_tmp31_, "highlight-brackets");
	text_editor_set_highlight_brackets (editor, _tmp32_);
	_tmp33_ = self->priv->settings;
	_tmp34_ = g_settings_get_boolean (_tmp33_, "show-grid-pattern");
	text_editor_set_show_grid_pattern (editor, _tmp34_);
	_tmp35_ = self->priv->settings;
	_tmp36_ = g_settings_get_int (_tmp35_, "tab-width");
	text_editor_set_tab_width (editor, _tmp36_);
	_tmp37_ = self->priv->settings;
	_tmp38_ = g_settings_get_boolean (_tmp37_, "insert-spaces");
	text_editor_set_insert_spaces (editor, _tmp38_);
	_tmp39_ = self->priv->settings;
	_tmp40_ = g_settings_get_boolean (_tmp39_, "auto-indent");
	text_editor_set_auto_indent (editor, _tmp40_);
	_tmp41_ = self->priv->settings;
	_tmp42_ = g_settings_get_boolean (_tmp41_, "use-default-typo");
	text_editor_set_use_default_typo (editor, _tmp42_);
	_tmp43_ = self->priv->settings;
	_tmp44_ = g_settings_get_string (_tmp43_, "editor-font");
	_tmp45_ = _tmp44_;
	text_editor_set_editor_font (editor, _tmp45_);
	_g_free0 (_tmp45_);
	_tmp46_ = self->priv->settings;
	_tmp47_ = g_settings_get_string (_tmp46_, "color-scheme");
	_tmp48_ = _tmp47_;
	text_editor_set_color_scheme (editor, _tmp48_);
	_g_free0 (_tmp48_);
	_tmp49_ = self->priv->settings;
	_tmp50_ = g_settings_get_boolean (_tmp49_, "prefer-dark");
	text_editor_set_prefer_dark (editor, _tmp50_);
	g_action_map_add_action_entries ((GActionMap*) self, SIMPLE_TEXT_app_entries, G_N_ELEMENTS (SIMPLE_TEXT_app_entries), self);
	_tmp51_ = main_window_new ((GtkApplication*) self, editor);
	g_object_ref_sink (_tmp51_);
	_g_object_unref0 (self->priv->window);
	self->priv->window = _tmp51_;
	_tmp52_ = gtk_builder_new ();
	builder = _tmp52_;
	{
		gtk_builder_add_from_resource (builder, "/com/github/badwolfie/simple-text/menu.ui", &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch8_g_error;
		}
	}
	goto __finally8;
	__catch8_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp53_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp53_ = e->message;
		g_error ("simple-text.vala:65: Error loading menu UI: %s", _tmp53_);
		_g_error_free0 (e);
	}
	__finally8:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (builder);
		_g_object_unref0 (editor);
		_g_object_unref0 (saved_workspace);
		_g_object_unref0 (conf_dir);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp54_ = gtk_builder_get_object (builder, "appmenu");
	_tmp55_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp54_, g_menu_model_get_type ()) ? ((GMenuModel*) _tmp54_) : NULL);
	menu = _tmp55_;
	gtk_application_set_app_menu ((GtkApplication*) self, menu);
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.re_open", accels_re_open);
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.save_as", accels_save_as);
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.set_syntax", accels_set_syntax);
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.toggle_terminal", accels_show_terminal);
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.next_tab", accels_next_tab);
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.prev_tab", accels_prev_tab);
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.close_tab", accels_close);
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.search_mode", accels_search);
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.quit_window", accels_quit);
	system ("clear");
	_g_object_unref0 (menu);
	_g_object_unref0 (builder);
	_g_object_unref0 (editor);
	_g_object_unref0 (saved_workspace);
	_g_object_unref0 (conf_dir);
}


static void simple_text_real_activate (GApplication* base) {
	SimpleText * self;
	MainWindow* _tmp0_ = NULL;
	MainWindow* _tmp1_ = NULL;
	self = (SimpleText*) base;
	G_APPLICATION_CLASS (simple_text_parent_class)->activate ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
	_tmp0_ = self->priv->window;
	main_window_set_arg_files (_tmp0_, NULL, 0);
	_tmp1_ = self->priv->window;
	gtk_window_present ((GtkWindow*) _tmp1_);
}


static void simple_text_real_open (GApplication* base, GFile** files, int files_length1, const gchar* hint) {
	SimpleText * self;
	GFile** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	const gchar* _tmp1_ = NULL;
	MainWindow* _tmp2_ = NULL;
	GFile** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	MainWindow* _tmp4_ = NULL;
	self = (SimpleText*) base;
	g_return_if_fail (hint != NULL);
	_tmp0_ = files;
	_tmp0__length1 = files_length1;
	_tmp1_ = hint;
	G_APPLICATION_CLASS (simple_text_parent_class)->open ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication), _tmp0_, _tmp0__length1, _tmp1_);
	_tmp2_ = self->priv->window;
	_tmp3_ = files;
	_tmp3__length1 = files_length1;
	main_window_set_arg_files (_tmp2_, _tmp3_, _tmp3__length1);
	_tmp4_ = self->priv->window;
	gtk_window_present ((GtkWindow*) _tmp4_);
}


static void simple_text_real_shutdown (GApplication* base) {
	SimpleText * self;
	TextEditor* editor = NULL;
	MainWindow* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	TextEditor* _tmp2_ = NULL;
	TextEditor* _tmp3_ = NULL;
	GSettings* _tmp4_ = NULL;
	TextEditor* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	gboolean _tmp7_ = FALSE;
	GSettings* _tmp8_ = NULL;
	TextEditor* _tmp9_ = NULL;
	gboolean _tmp10_ = FALSE;
	gboolean _tmp11_ = FALSE;
	GSettings* _tmp12_ = NULL;
	TextEditor* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	gint _tmp15_ = 0;
	GSettings* _tmp16_ = NULL;
	TextEditor* _tmp17_ = NULL;
	gboolean _tmp18_ = FALSE;
	gboolean _tmp19_ = FALSE;
	GSettings* _tmp20_ = NULL;
	TextEditor* _tmp21_ = NULL;
	gboolean _tmp22_ = FALSE;
	gboolean _tmp23_ = FALSE;
	GSettings* _tmp24_ = NULL;
	TextEditor* _tmp25_ = NULL;
	gboolean _tmp26_ = FALSE;
	gboolean _tmp27_ = FALSE;
	GSettings* _tmp28_ = NULL;
	TextEditor* _tmp29_ = NULL;
	gboolean _tmp30_ = FALSE;
	gboolean _tmp31_ = FALSE;
	GSettings* _tmp32_ = NULL;
	TextEditor* _tmp33_ = NULL;
	gint _tmp34_ = 0;
	gint _tmp35_ = 0;
	GSettings* _tmp36_ = NULL;
	TextEditor* _tmp37_ = NULL;
	gboolean _tmp38_ = FALSE;
	gboolean _tmp39_ = FALSE;
	GSettings* _tmp40_ = NULL;
	TextEditor* _tmp41_ = NULL;
	gboolean _tmp42_ = FALSE;
	gboolean _tmp43_ = FALSE;
	GSettings* _tmp44_ = NULL;
	TextEditor* _tmp45_ = NULL;
	gboolean _tmp46_ = FALSE;
	gboolean _tmp47_ = FALSE;
	TextEditor* _tmp48_ = NULL;
	gboolean _tmp49_ = FALSE;
	gboolean _tmp50_ = FALSE;
	GSettings* _tmp56_ = NULL;
	TextEditor* _tmp57_ = NULL;
	const gchar* _tmp58_ = NULL;
	const gchar* _tmp59_ = NULL;
	GSettings* _tmp60_ = NULL;
	TextEditor* _tmp61_ = NULL;
	gboolean _tmp62_ = FALSE;
	gboolean _tmp63_ = FALSE;
	self = (SimpleText*) base;
	G_APPLICATION_CLASS (simple_text_parent_class)->shutdown ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
	_tmp0_ = self->priv->window;
	_tmp1_ = main_window_get_editor (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	editor = _tmp3_;
	_tmp4_ = self->priv->settings;
	_tmp5_ = editor;
	_tmp6_ = text_editor_get_show_line_numbers (_tmp5_);
	_tmp7_ = _tmp6_;
	g_settings_set_boolean (_tmp4_, "show-line-numbers", _tmp7_);
	_tmp8_ = self->priv->settings;
	_tmp9_ = editor;
	_tmp10_ = text_editor_get_show_right_margin (_tmp9_);
	_tmp11_ = _tmp10_;
	g_settings_set_boolean (_tmp8_, "show-right-margin", _tmp11_);
	_tmp12_ = self->priv->settings;
	_tmp13_ = editor;
	_tmp14_ = text_editor_get_right_margin_at (_tmp13_);
	_tmp15_ = _tmp14_;
	g_settings_set_int (_tmp12_, "right-margin-at", _tmp15_);
	_tmp16_ = self->priv->settings;
	_tmp17_ = editor;
	_tmp18_ = text_editor_get_use_text_wrap (_tmp17_);
	_tmp19_ = _tmp18_;
	g_settings_set_boolean (_tmp16_, "use-text-wrap", _tmp19_);
	_tmp20_ = self->priv->settings;
	_tmp21_ = editor;
	_tmp22_ = text_editor_get_highlight_current_line (_tmp21_);
	_tmp23_ = _tmp22_;
	g_settings_set_boolean (_tmp20_, "highlight-current-line", _tmp23_);
	_tmp24_ = self->priv->settings;
	_tmp25_ = editor;
	_tmp26_ = text_editor_get_highlight_brackets (_tmp25_);
	_tmp27_ = _tmp26_;
	g_settings_set_boolean (_tmp24_, "highlight-brackets", _tmp27_);
	_tmp28_ = self->priv->settings;
	_tmp29_ = editor;
	_tmp30_ = text_editor_get_show_grid_pattern (_tmp29_);
	_tmp31_ = _tmp30_;
	g_settings_set_boolean (_tmp28_, "show-grid-pattern", _tmp31_);
	_tmp32_ = self->priv->settings;
	_tmp33_ = editor;
	_tmp34_ = text_editor_get_tab_width (_tmp33_);
	_tmp35_ = _tmp34_;
	g_settings_set_int (_tmp32_, "tab-width", _tmp35_);
	_tmp36_ = self->priv->settings;
	_tmp37_ = editor;
	_tmp38_ = text_editor_get_insert_spaces (_tmp37_);
	_tmp39_ = _tmp38_;
	g_settings_set_boolean (_tmp36_, "insert-spaces", _tmp39_);
	_tmp40_ = self->priv->settings;
	_tmp41_ = editor;
	_tmp42_ = text_editor_get_auto_indent (_tmp41_);
	_tmp43_ = _tmp42_;
	g_settings_set_boolean (_tmp40_, "auto-indent", _tmp43_);
	_tmp44_ = self->priv->settings;
	_tmp45_ = editor;
	_tmp46_ = text_editor_get_use_default_typo (_tmp45_);
	_tmp47_ = _tmp46_;
	g_settings_set_boolean (_tmp44_, "use-default-typo", _tmp47_);
	_tmp48_ = editor;
	_tmp49_ = text_editor_get_use_default_typo (_tmp48_);
	_tmp50_ = _tmp49_;
	if (_tmp50_) {
		GSettings* _tmp51_ = NULL;
		_tmp51_ = self->priv->settings;
		g_settings_reset (_tmp51_, "editor-font");
	} else {
		GSettings* _tmp52_ = NULL;
		TextEditor* _tmp53_ = NULL;
		const gchar* _tmp54_ = NULL;
		const gchar* _tmp55_ = NULL;
		_tmp52_ = self->priv->settings;
		_tmp53_ = editor;
		_tmp54_ = text_editor_get_editor_font (_tmp53_);
		_tmp55_ = _tmp54_;
		g_settings_set_string (_tmp52_, "editor-font", _tmp55_);
	}
	_tmp56_ = self->priv->settings;
	_tmp57_ = editor;
	_tmp58_ = text_editor_get_color_scheme (_tmp57_);
	_tmp59_ = _tmp58_;
	g_settings_set_string (_tmp56_, "color-scheme", _tmp59_);
	_tmp60_ = self->priv->settings;
	_tmp61_ = editor;
	_tmp62_ = text_editor_get_prefer_dark (_tmp61_);
	_tmp63_ = _tmp62_;
	g_settings_set_boolean (_tmp60_, "prefer-dark", _tmp63_);
	_g_object_unref0 (editor);
}


static void simple_text_show_prefs_cb (SimpleText* self) {
	PreferencesDialog* _tmp0_ = NULL;
	PreferencesDialog* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->preferences_dialog;
	if (_tmp0_ == NULL) {
		MainWindow* _tmp1_ = NULL;
		MainWindow* _tmp2_ = NULL;
		TextEditor* _tmp3_ = NULL;
		TextEditor* _tmp4_ = NULL;
		PreferencesDialog* _tmp5_ = NULL;
		_tmp1_ = self->priv->window;
		_tmp2_ = self->priv->window;
		_tmp3_ = main_window_get_editor (_tmp2_);
		_tmp4_ = _tmp3_;
		_tmp5_ = preferences_dialog_new (_tmp1_, _tmp4_);
		g_object_ref_sink (_tmp5_);
		_g_object_unref0 (self->priv->preferences_dialog);
		self->priv->preferences_dialog = _tmp5_;
	}
	_tmp6_ = self->priv->preferences_dialog;
	gtk_window_present ((GtkWindow*) _tmp6_);
}


static void simple_text_about_cb (SimpleText* self) {
	gchar** authors = NULL;
	gchar* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint authors_length1 = 0;
	gint _authors_size_ = 0;
	gchar** documenters = NULL;
	gchar* _tmp2_ = NULL;
	gchar** _tmp3_ = NULL;
	gint documenters_length1 = 0;
	gint _documenters_size_ = 0;
	static const gchar* contributors[] = {"Carlos López <clopezr_1205@openmailbox.org>"};
	gchar* translator_credits = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* license = NULL;
	gchar* _tmp6_ = NULL;
	GtkAboutDialog* about_dialog = NULL;
	GtkAboutDialog* _tmp7_ = NULL;
	MainWindow* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	const gchar* _tmp14_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("Ian Hernández <ihernandezs@openmailbox.org>");
	_tmp1_ = g_new0 (gchar*, 1 + 1);
	_tmp1_[0] = _tmp0_;
	authors = _tmp1_;
	authors_length1 = 1;
	_authors_size_ = authors_length1;
	_tmp2_ = g_strdup ("Ian Hernández");
	_tmp3_ = g_new0 (gchar*, 1 + 1);
	_tmp3_[0] = _tmp2_;
	documenters = _tmp3_;
	documenters_length1 = 1;
	_documenters_size_ = documenters_length1;
	_tmp4_ = _ ("translator-credits");
	_tmp5_ = g_strdup (_tmp4_);
	translator_credits = _tmp5_;
	_tmp6_ = g_strdup ("Simple Text is free software: you can redistribute it and/or modify\n" \
"it under the terms of the GNU General Public License as published by\n" \
"the Free Software Foundation, either version 2 of the License, or\n" \
"(at your option) any later version.\n" \
"\n" \
"Simple Text is distributed in the hope that it will be useful,\n" \
"but WITHOUT ANY WARRANTY; without even the implied warranty of\n" \
"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\n" \
"GNU General Public License for more details.\n" \
"\n" \
"You should have received a copy of the GNU General Public License\n" \
"along with Simple Text. If not, see <http://www.gnu.org/licenses/>.");
	license = _tmp6_;
	_tmp7_ = (GtkAboutDialog*) gtk_about_dialog_new ();
	g_object_ref_sink (_tmp7_);
	about_dialog = _tmp7_;
	_tmp8_ = self->priv->window;
	gtk_window_set_transient_for ((GtkWindow*) about_dialog, (GtkWindow*) _tmp8_);
	gtk_about_dialog_set_program_name (about_dialog, "Simple Text");
	_tmp9_ = _ ("About");
	_tmp10_ = g_strconcat (_tmp9_, " Simple Text", NULL);
	_tmp11_ = _tmp10_;
	gtk_window_set_title ((GtkWindow*) about_dialog, _tmp11_);
	_g_free0 (_tmp11_);
	gtk_about_dialog_set_copyright (about_dialog, "Copyright \xc2\xa9 2015 Ian Hernández");
	_tmp12_ = _ ("A not so simple text and code editor written in Vala");
	gtk_about_dialog_set_comments (about_dialog, _tmp12_);
	gtk_about_dialog_set_website (about_dialog, "https://github.com/BadWolfie/simple-text");
	_tmp13_ = _ ("Web page");
	gtk_about_dialog_set_website_label (about_dialog, _tmp13_);
	gtk_about_dialog_set_license (about_dialog, license);
	gtk_about_dialog_set_logo_icon_name (about_dialog, "text-editor");
	gtk_about_dialog_set_documenters (about_dialog, documenters);
	gtk_about_dialog_set_authors (about_dialog, authors);
	gtk_about_dialog_set_translator_credits (about_dialog, translator_credits);
	gtk_about_dialog_set_version (about_dialog, "0.9.8");
	_tmp14_ = _ ("Contributors");
	gtk_about_dialog_add_credit_section (about_dialog, _tmp14_, contributors);
	gtk_dialog_run ((GtkDialog*) about_dialog);
	gtk_widget_destroy ((GtkWidget*) about_dialog);
	_g_object_unref0 (about_dialog);
	_g_free0 (license);
	_g_free0 (translator_credits);
	documenters = (_vala_array_free (documenters, documenters_length1, (GDestroyNotify) g_free), NULL);
	authors = (_vala_array_free (authors, authors_length1, (GDestroyNotify) g_free), NULL);
}


static void simple_text_quit_cb (SimpleText* self) {
	MainWindow* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->window;
	gtk_widget_destroy ((GtkWidget*) _tmp0_);
}


gint simple_text_main (gchar** args, int args_length1) {
	gint result = 0;
	SimpleText* app = NULL;
	SimpleText* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
	setlocale (LC_ALL, "");
	bindtextdomain (GETTEXT_PACKAGE, LOCALEDIR);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
	gtk_window_set_default_icon_name ("text-editor");
	_tmp0_ = simple_text_new ();
	app = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp2_ = g_application_run ((GApplication*) app, _tmp1__length1, _tmp1_);
	result = _tmp2_;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return simple_text_main (argv, argc);
}


static void simple_text_class_init (SimpleTextClass * klass) {
	simple_text_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SimpleTextPrivate));
	((GApplicationClass *) klass)->startup = simple_text_real_startup;
	((GApplicationClass *) klass)->activate = simple_text_real_activate;
	((GApplicationClass *) klass)->open = simple_text_real_open;
	((GApplicationClass *) klass)->shutdown = simple_text_real_shutdown;
	G_OBJECT_CLASS (klass)->finalize = simple_text_finalize;
}


static void simple_text_instance_init (SimpleText * self) {
	self->priv = SIMPLE_TEXT_GET_PRIVATE (self);
}


static void simple_text_finalize (GObject* obj) {
	SimpleText * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SIMPLE_TEXT, SimpleText);
	_g_object_unref0 (self->priv->settings);
	_g_object_unref0 (self->priv->preferences_dialog);
	_g_object_unref0 (self->priv->window);
	G_OBJECT_CLASS (simple_text_parent_class)->finalize (obj);
}


GType simple_text_get_type (void) {
	static volatile gsize simple_text_type_id__volatile = 0;
	if (g_once_init_enter (&simple_text_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SimpleTextClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) simple_text_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SimpleText), 0, (GInstanceInitFunc) simple_text_instance_init, NULL };
		GType simple_text_type_id;
		simple_text_type_id = g_type_register_static (gtk_application_get_type (), "SimpleText", &g_define_type_info, 0);
		g_once_init_leave (&simple_text_type_id__volatile, simple_text_type_id);
	}
	return simple_text_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



