/* simple-tab.c generated by valac 0.28.0, the Vala compiler
 * generated from simple-tab.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gtksourceview/gtksource.h>
#include <glib/gi18n-lib.h>
#include <glib/gstdio.h>
#include <stdio.h>
#include <gdk/gdk.h>


#define TYPE_SIMPLE_TAB (simple_tab_get_type ())
#define SIMPLE_TAB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SIMPLE_TAB, SimpleTab))
#define SIMPLE_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SIMPLE_TAB, SimpleTabClass))
#define IS_SIMPLE_TAB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SIMPLE_TAB))
#define IS_SIMPLE_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SIMPLE_TAB))
#define SIMPLE_TAB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SIMPLE_TAB, SimpleTabClass))

typedef struct _SimpleTab SimpleTab;
typedef struct _SimpleTabClass SimpleTabClass;
typedef struct _SimpleTabPrivate SimpleTabPrivate;

#define TYPE_TEXT_EDITOR (text_editor_get_type ())
#define TEXT_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXT_EDITOR, TextEditor))
#define TEXT_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXT_EDITOR, TextEditorClass))
#define IS_TEXT_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXT_EDITOR))
#define IS_TEXT_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXT_EDITOR))
#define TEXT_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXT_EDITOR, TextEditorClass))

typedef struct _TextEditor TextEditor;
typedef struct _TextEditorClass TextEditorClass;

#define TYPE_SIMPLE_SOURCE_VIEW (simple_source_view_get_type ())
#define SIMPLE_SOURCE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SIMPLE_SOURCE_VIEW, SimpleSourceView))
#define SIMPLE_SOURCE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SIMPLE_SOURCE_VIEW, SimpleSourceViewClass))
#define IS_SIMPLE_SOURCE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SIMPLE_SOURCE_VIEW))
#define IS_SIMPLE_SOURCE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SIMPLE_SOURCE_VIEW))
#define SIMPLE_SOURCE_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SIMPLE_SOURCE_VIEW, SimpleSourceViewClass))

typedef struct _SimpleSourceView SimpleSourceView;
typedef struct _SimpleSourceViewClass SimpleSourceViewClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_PROGRAMMING_LANGUAGES (programming_languages_get_type ())
#define PROGRAMMING_LANGUAGES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PROGRAMMING_LANGUAGES, ProgrammingLanguages))
#define PROGRAMMING_LANGUAGES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PROGRAMMING_LANGUAGES, ProgrammingLanguagesClass))
#define IS_PROGRAMMING_LANGUAGES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PROGRAMMING_LANGUAGES))
#define IS_PROGRAMMING_LANGUAGES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PROGRAMMING_LANGUAGES))
#define PROGRAMMING_LANGUAGES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PROGRAMMING_LANGUAGES, ProgrammingLanguagesClass))

typedef struct _ProgrammingLanguages ProgrammingLanguages;
typedef struct _ProgrammingLanguagesClass ProgrammingLanguagesClass;
#define _programming_languages_unref0(var) ((var == NULL) ? NULL : (var = (programming_languages_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _SimpleTab {
	GtkBox parent_instance;
	SimpleTabPrivate * priv;
};

struct _SimpleTabClass {
	GtkBoxClass parent_class;
};

struct _SimpleTabPrivate {
	TextEditor* editor;
	gchar* untitled;
	GtkSourceCompletion* _completion;
	SimpleSourceView* _text_view;
	GtkEventBox* evt_box;
	GtkLabel* title_label;
	GtkEventBox* close_button;
	GtkSeparator* separator;
	GtkScrolledWindow* _tab_widget;
	gchar* _tab_title;
};


static gpointer simple_tab_parent_class = NULL;

GType simple_tab_get_type (void) G_GNUC_CONST;
GType text_editor_get_type (void) G_GNUC_CONST;
GType simple_source_view_get_type (void) G_GNUC_CONST;
#define SIMPLE_TAB_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SIMPLE_TAB, SimpleTabPrivate))
enum  {
	SIMPLE_TAB_DUMMY_PROPERTY,
	SIMPLE_TAB_COMPLETION,
	SIMPLE_TAB_TEXT_VIEW,
	SIMPLE_TAB_TAB_WIDGET,
	SIMPLE_TAB_TAB_TITLE
};
SimpleTab* simple_tab_new (TextEditor* editor);
SimpleTab* simple_tab_construct (GType object_type, TextEditor* editor);
void simple_tab_set_tab_title (SimpleTab* self, const gchar* value);
static void simple_tab_create_widgets (SimpleTab* self, const gchar* language, const gchar* display_text);
SimpleTab* simple_tab_new_from_file (TextEditor* editor, const gchar* base_name, const gchar* file_path);
SimpleTab* simple_tab_construct_from_file (GType object_type, TextEditor* editor, const gchar* base_name, const gchar* file_path);
gpointer programming_languages_ref (gpointer instance);
void programming_languages_unref (gpointer instance);
GParamSpec* param_spec_programming_languages (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_programming_languages (GValue* value, gpointer v_object);
void value_take_programming_languages (GValue* value, gpointer v_object);
gpointer value_get_programming_languages (const GValue* value);
GType programming_languages_get_type (void) G_GNUC_CONST;
ProgrammingLanguages* programming_languages_new (void);
ProgrammingLanguages* programming_languages_construct (GType object_type);
gchar* programming_languages_get_lang_id (ProgrammingLanguages* self, const gchar* filename);
const gchar* simple_tab_get_tab_title (SimpleTab* self);
static gboolean simple_tab_button_clicked (SimpleTab* self, GdkEventButton* evt);
static gboolean _simple_tab_button_clicked_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean simple_tab_tab_clicked_action (SimpleTab* self, GdkEventButton* evt);
static gboolean _simple_tab_tab_clicked_action_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
SimpleSourceView* simple_source_view_new_with_language (TextEditor* editor, const gchar* language, const gchar* display_text);
SimpleSourceView* simple_source_view_construct_with_language (GType object_type, TextEditor* editor, const gchar* language, const gchar* display_text);
SimpleSourceView* simple_source_view_new_with_text (TextEditor* editor, const gchar* display_text);
SimpleSourceView* simple_source_view_construct_with_text (GType object_type, TextEditor* editor, const gchar* display_text);
SimpleSourceView* simple_source_view_new (TextEditor* editor);
SimpleSourceView* simple_source_view_construct (GType object_type, TextEditor* editor);
static void simple_tab_on_drag_n_drop (SimpleTab* self, const gchar* file_name);
static void _simple_tab_on_drag_n_drop_simple_source_view_drag_n_drop (SimpleSourceView* _sender, const gchar* file_name, gpointer self);
SimpleSourceView* simple_tab_get_text_view (SimpleTab* self);
GtkSourceCompletion* simple_tab_get_completion (SimpleTab* self);
GtkScrolledWindow* simple_tab_get_tab_widget (SimpleTab* self);
void simple_tab_refresh_title (SimpleTab* self);
void simple_tab_mark_title (SimpleTab* self);
void simple_tab_change_language (SimpleTab* self, const gchar* language);
void simple_source_view_change_language (SimpleSourceView* self, const gchar* language);
void simple_tab_set_tab_widget (SimpleTab* self, GtkScrolledWindow* value);
static void simple_tab_finalize (GObject* obj);
static void _vala_simple_tab_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_simple_tab_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


SimpleTab* simple_tab_construct (GType object_type, TextEditor* editor) {
	SimpleTab * self = NULL;
	TextEditor* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	g_return_val_if_fail (editor != NULL, NULL);
	self = (SimpleTab*) g_object_new (object_type, NULL);
	_tmp0_ = editor;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->editor);
	self->priv->editor = _tmp1_;
	_tmp2_ = self->priv->untitled;
	simple_tab_set_tab_title (self, _tmp2_);
	simple_tab_create_widgets (self, NULL, NULL);
	return self;
}


SimpleTab* simple_tab_new (TextEditor* editor) {
	return simple_tab_construct (TYPE_SIMPLE_TAB, editor);
}


SimpleTab* simple_tab_construct_from_file (GType object_type, TextEditor* editor, const gchar* base_name, const gchar* file_path) {
	SimpleTab * self = NULL;
	TextEditor* _tmp0_ = NULL;
	TextEditor* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (editor != NULL, NULL);
	g_return_val_if_fail (base_name != NULL, NULL);
	g_return_val_if_fail (file_path != NULL, NULL);
	self = (SimpleTab*) g_object_new (object_type, NULL);
	_tmp0_ = editor;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->editor);
	self->priv->editor = _tmp1_;
	_tmp2_ = base_name;
	simple_tab_set_tab_title (self, _tmp2_);
	{
		gchar* text = NULL;
		const gchar* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		ProgrammingLanguages* plangs = NULL;
		ProgrammingLanguages* _tmp5_ = NULL;
		ProgrammingLanguages* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		_tmp3_ = file_path;
		g_file_get_contents (_tmp3_, &_tmp4_, NULL, &_inner_error_);
		_g_free0 (text);
		text = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_free0 (text);
			goto __catch6_g_error;
		}
		_tmp5_ = programming_languages_new ();
		plangs = _tmp5_;
		_tmp6_ = plangs;
		_tmp7_ = base_name;
		_tmp8_ = programming_languages_get_lang_id (_tmp6_, _tmp7_);
		_tmp9_ = _tmp8_;
		simple_tab_create_widgets (self, _tmp9_, text);
		_g_free0 (_tmp9_);
		_programming_languages_unref0 (plangs);
		_g_free0 (text);
	}
	goto __finally6;
	__catch6_g_error:
	{
		GError* e = NULL;
		FILE* _tmp10_ = NULL;
		GError* _tmp11_ = NULL;
		const gchar* _tmp12_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp10_ = stderr;
		_tmp11_ = e;
		_tmp12_ = _tmp11_->message;
		fprintf (_tmp10_, "Error: %s\n", _tmp12_);
		_g_error_free0 (e);
	}
	__finally6:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	return self;
}


SimpleTab* simple_tab_new_from_file (TextEditor* editor, const gchar* base_name, const gchar* file_path) {
	return simple_tab_construct_from_file (TYPE_SIMPLE_TAB, editor, base_name, file_path);
}


static gboolean _simple_tab_button_clicked_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = simple_tab_button_clicked ((SimpleTab*) self, event);
	return result;
}


static gboolean _simple_tab_tab_clicked_action_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = simple_tab_tab_clicked_action ((SimpleTab*) self, event);
	return result;
}


static void _simple_tab_on_drag_n_drop_simple_source_view_drag_n_drop (SimpleSourceView* _sender, const gchar* file_name, gpointer self) {
	simple_tab_on_drag_n_drop ((SimpleTab*) self, file_name);
}


static void simple_tab_create_widgets (SimpleTab* self, const gchar* language, const gchar* display_text) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkSeparator* _tmp3_ = NULL;
	GtkImage* close_img = NULL;
	GtkImage* _tmp4_ = NULL;
	GtkEventBox* _tmp5_ = NULL;
	GtkEventBox* _tmp6_ = NULL;
	GtkImage* _tmp7_ = NULL;
	GtkEventBox* _tmp8_ = NULL;
	GtkEventBox* _tmp9_ = NULL;
	GtkEventBox* _tmp10_ = NULL;
	GtkEventBox* _tmp11_ = NULL;
	GtkLabel* _tmp12_ = NULL;
	GtkEventBox* _tmp13_ = NULL;
	GtkEventBox* _tmp14_ = NULL;
	GtkEventBox* _tmp15_ = NULL;
	GtkEventBox* _tmp16_ = NULL;
	GtkSeparator* _tmp17_ = NULL;
	const gchar* _tmp18_ = NULL;
	SimpleSourceView* _tmp29_ = NULL;
	SimpleSourceView* _tmp30_ = NULL;
	SimpleSourceView* _tmp31_ = NULL;
	SimpleSourceView* _tmp32_ = NULL;
	SimpleSourceView* _tmp33_ = NULL;
	GtkSourceCompletion* _tmp34_ = NULL;
	GtkSourceCompletion* _tmp35_ = NULL;
	GtkSourceCompletion* _tmp36_ = NULL;
	GtkSourceCompletion* _tmp37_ = NULL;
	GtkSourceCompletion* _tmp38_ = NULL;
	GtkSourceCompletion* _tmp39_ = NULL;
	GtkSourceCompletion* _tmp40_ = NULL;
	GtkSourceCompletion* _tmp41_ = NULL;
	GtkScrolledWindow* _tmp42_ = NULL;
	GtkScrolledWindow* _tmp43_ = NULL;
	GtkScrolledWindow* _tmp44_ = NULL;
	GtkScrolledWindow* _tmp45_ = NULL;
	GtkScrolledWindow* _tmp46_ = NULL;
	SimpleSourceView* _tmp47_ = NULL;
	SimpleSourceView* _tmp48_ = NULL;
	GtkScrolledWindow* _tmp49_ = NULL;
	GtkScrolledWindow* _tmp50_ = NULL;
	g_return_if_fail (self != NULL);
	gtk_orientable_set_orientation ((GtkOrientable*) self, GTK_ORIENTATION_HORIZONTAL);
	gtk_box_set_spacing ((GtkBox*) self, 0);
	_tmp0_ = simple_tab_get_tab_title (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = (GtkLabel*) gtk_label_new (_tmp1_);
	g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->priv->title_label);
	self->priv->title_label = _tmp2_;
	_tmp3_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_VERTICAL);
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->priv->separator);
	self->priv->separator = _tmp3_;
	_tmp4_ = (GtkImage*) gtk_image_new_from_icon_name ("window-close-symbolic", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp4_);
	close_img = _tmp4_;
	_tmp5_ = (GtkEventBox*) gtk_event_box_new ();
	g_object_ref_sink (_tmp5_);
	_g_object_unref0 (self->priv->close_button);
	self->priv->close_button = _tmp5_;
	_tmp6_ = self->priv->close_button;
	_tmp7_ = close_img;
	g_object_set ((GtkContainer*) _tmp6_, "child", (GtkWidget*) _tmp7_, NULL);
	_tmp8_ = self->priv->close_button;
	gtk_event_box_set_above_child (_tmp8_, TRUE);
	_tmp9_ = self->priv->close_button;
	g_signal_connect_object ((GtkWidget*) _tmp9_, "button-press-event", (GCallback) _simple_tab_button_clicked_gtk_widget_button_press_event, self, 0);
	_tmp10_ = (GtkEventBox*) gtk_event_box_new ();
	g_object_ref_sink (_tmp10_);
	_g_object_unref0 (self->priv->evt_box);
	self->priv->evt_box = _tmp10_;
	_tmp11_ = self->priv->evt_box;
	_tmp12_ = self->priv->title_label;
	g_object_set ((GtkContainer*) _tmp11_, "child", (GtkWidget*) _tmp12_, NULL);
	_tmp13_ = self->priv->evt_box;
	gtk_event_box_set_above_child (_tmp13_, TRUE);
	_tmp14_ = self->priv->evt_box;
	g_signal_connect_object ((GtkWidget*) _tmp14_, "button-press-event", (GCallback) _simple_tab_tab_clicked_action_gtk_widget_button_press_event, self, 0);
	_tmp15_ = self->priv->evt_box;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp15_, TRUE, TRUE, (guint) 0);
	_tmp16_ = self->priv->close_button;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp16_, FALSE, TRUE, (guint) 5);
	_tmp17_ = self->priv->separator;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp17_, FALSE, TRUE, (guint) 0);
	_tmp18_ = display_text;
	if (_tmp18_ != NULL) {
		const gchar* _tmp19_ = NULL;
		_tmp19_ = language;
		if (_tmp19_ != NULL) {
			TextEditor* _tmp20_ = NULL;
			const gchar* _tmp21_ = NULL;
			const gchar* _tmp22_ = NULL;
			SimpleSourceView* _tmp23_ = NULL;
			_tmp20_ = self->priv->editor;
			_tmp21_ = language;
			_tmp22_ = display_text;
			_tmp23_ = simple_source_view_new_with_language (_tmp20_, _tmp21_, _tmp22_);
			g_object_ref_sink (_tmp23_);
			_g_object_unref0 (self->priv->_text_view);
			self->priv->_text_view = _tmp23_;
		} else {
			TextEditor* _tmp24_ = NULL;
			const gchar* _tmp25_ = NULL;
			SimpleSourceView* _tmp26_ = NULL;
			_tmp24_ = self->priv->editor;
			_tmp25_ = display_text;
			_tmp26_ = simple_source_view_new_with_text (_tmp24_, _tmp25_);
			g_object_ref_sink (_tmp26_);
			_g_object_unref0 (self->priv->_text_view);
			self->priv->_text_view = _tmp26_;
		}
	} else {
		TextEditor* _tmp27_ = NULL;
		SimpleSourceView* _tmp28_ = NULL;
		_tmp27_ = self->priv->editor;
		_tmp28_ = simple_source_view_new (_tmp27_);
		g_object_ref_sink (_tmp28_);
		_g_object_unref0 (self->priv->_text_view);
		self->priv->_text_view = _tmp28_;
	}
	_tmp29_ = self->priv->_text_view;
	g_signal_connect_object (_tmp29_, "drag-n-drop", (GCallback) _simple_tab_on_drag_n_drop_simple_source_view_drag_n_drop, self, 0);
	_tmp30_ = simple_tab_get_text_view (self);
	_tmp31_ = _tmp30_;
	gtk_widget_show ((GtkWidget*) _tmp31_);
	_tmp32_ = simple_tab_get_text_view (self);
	_tmp33_ = _tmp32_;
	_tmp34_ = gtk_source_view_get_completion ((GtkSourceView*) _tmp33_);
	_tmp35_ = _g_object_ref0 (_tmp34_);
	_g_object_unref0 (self->priv->_completion);
	self->priv->_completion = _tmp35_;
	_tmp36_ = simple_tab_get_completion (self);
	_tmp37_ = _tmp36_;
	g_object_set (_tmp37_, "select-on-show", TRUE, NULL);
	_tmp38_ = simple_tab_get_completion (self);
	_tmp39_ = _tmp38_;
	g_object_set (_tmp39_, "show-headers", TRUE, NULL);
	_tmp40_ = simple_tab_get_completion (self);
	_tmp41_ = _tmp40_;
	g_object_set (_tmp41_, "show-icons", TRUE, NULL);
	_tmp42_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp42_);
	_g_object_unref0 (self->priv->_tab_widget);
	self->priv->_tab_widget = _tmp42_;
	_tmp43_ = simple_tab_get_tab_widget (self);
	_tmp44_ = _tmp43_;
	gtk_scrolled_window_set_policy (_tmp44_, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
	_tmp45_ = simple_tab_get_tab_widget (self);
	_tmp46_ = _tmp45_;
	_tmp47_ = simple_tab_get_text_view (self);
	_tmp48_ = _tmp47_;
	gtk_container_add ((GtkContainer*) _tmp46_, (GtkWidget*) _tmp48_);
	_tmp49_ = simple_tab_get_tab_widget (self);
	_tmp50_ = _tmp49_;
	gtk_widget_show ((GtkWidget*) _tmp50_);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (close_img);
}


static void simple_tab_on_drag_n_drop (SimpleTab* self, const gchar* file_name) {
	const gchar* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (file_name != NULL);
	_tmp0_ = file_name;
	g_signal_emit_by_name (self, "view-drag-n-drop", _tmp0_);
}


void simple_tab_refresh_title (SimpleTab* self) {
	GtkLabel* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->title_label;
	if (_tmp0_ != NULL) {
		GtkLabel* _tmp1_ = NULL;
		GtkLabel* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		_tmp1_ = self->priv->title_label;
		gtk_label_set_use_markup (_tmp1_, FALSE);
		_tmp2_ = self->priv->title_label;
		_tmp3_ = simple_tab_get_tab_title (self);
		_tmp4_ = _tmp3_;
		gtk_label_set_label (_tmp2_, _tmp4_);
	}
}


static gboolean simple_tab_button_clicked (SimpleTab* self, GdkEventButton* evt) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (evt != NULL, FALSE);
	g_signal_emit_by_name (self, "close-clicked", self);
	result = TRUE;
	return result;
}


static gboolean simple_tab_tab_clicked_action (SimpleTab* self, GdkEventButton* evt) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (evt != NULL, FALSE);
	g_signal_emit_by_name (self, "tab-clicked", self);
	simple_tab_mark_title (self);
	result = TRUE;
	return result;
}


void simple_tab_mark_title (SimpleTab* self) {
	GtkLabel* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->title_label;
	gtk_label_set_use_markup (_tmp0_, TRUE);
	_tmp1_ = self->priv->title_label;
	_tmp2_ = simple_tab_get_tab_title (self);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strconcat ("<b>", _tmp3_, NULL);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strconcat (_tmp5_, "</b>", NULL);
	_tmp7_ = _tmp6_;
	gtk_label_set_label (_tmp1_, _tmp7_);
	_g_free0 (_tmp7_);
	_g_free0 (_tmp5_);
}


void simple_tab_change_language (SimpleTab* self, const gchar* language) {
	SimpleSourceView* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (language != NULL);
	_tmp0_ = self->priv->_text_view;
	_tmp1_ = language;
	simple_source_view_change_language (_tmp0_, _tmp1_);
}


GtkSourceCompletion* simple_tab_get_completion (SimpleTab* self) {
	GtkSourceCompletion* result;
	GtkSourceCompletion* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_completion;
	result = _tmp0_;
	return result;
}


SimpleSourceView* simple_tab_get_text_view (SimpleTab* self) {
	SimpleSourceView* result;
	SimpleSourceView* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_text_view;
	result = _tmp0_;
	return result;
}


GtkScrolledWindow* simple_tab_get_tab_widget (SimpleTab* self) {
	GtkScrolledWindow* result;
	GtkScrolledWindow* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_tab_widget;
	result = _tmp0_;
	return result;
}


void simple_tab_set_tab_widget (SimpleTab* self, GtkScrolledWindow* value) {
	GtkScrolledWindow* _tmp0_ = NULL;
	GtkScrolledWindow* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_tab_widget);
	self->priv->_tab_widget = _tmp1_;
	g_object_notify ((GObject *) self, "tab-widget");
}


const gchar* simple_tab_get_tab_title (SimpleTab* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_tab_title;
	result = _tmp0_;
	return result;
}


void simple_tab_set_tab_title (SimpleTab* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_tab_title;
	_tmp1_ = value;
	if (g_strcmp0 (_tmp0_, _tmp1_) == 0) {
		return;
	}
	_tmp2_ = value;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (self->priv->_tab_title);
	self->priv->_tab_title = _tmp3_;
	simple_tab_refresh_title (self);
	g_object_notify ((GObject *) self, "tab-title");
}


static void simple_tab_class_init (SimpleTabClass * klass) {
	simple_tab_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SimpleTabPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_simple_tab_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_simple_tab_set_property;
	G_OBJECT_CLASS (klass)->finalize = simple_tab_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SIMPLE_TAB_COMPLETION, g_param_spec_object ("completion", "completion", "completion", gtk_source_completion_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SIMPLE_TAB_TEXT_VIEW, g_param_spec_object ("text-view", "text-view", "text-view", TYPE_SIMPLE_SOURCE_VIEW, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SIMPLE_TAB_TAB_WIDGET, g_param_spec_object ("tab-widget", "tab-widget", "tab-widget", gtk_scrolled_window_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SIMPLE_TAB_TAB_TITLE, g_param_spec_string ("tab-title", "tab-title", "tab-title", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_signal_new ("view_drag_n_drop", TYPE_SIMPLE_TAB, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
	g_signal_new ("close_clicked", TYPE_SIMPLE_TAB, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, TYPE_SIMPLE_TAB);
	g_signal_new ("tab_clicked", TYPE_SIMPLE_TAB, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, TYPE_SIMPLE_TAB);
	g_signal_new ("tab_focused", TYPE_SIMPLE_TAB, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, TYPE_SIMPLE_TAB);
}


static void simple_tab_instance_init (SimpleTab * self) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	self->priv = SIMPLE_TAB_GET_PRIVATE (self);
	_tmp0_ = _ ("Untitled file");
	_tmp1_ = g_strdup (_tmp0_);
	self->priv->untitled = _tmp1_;
}


static void simple_tab_finalize (GObject* obj) {
	SimpleTab * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SIMPLE_TAB, SimpleTab);
	_g_object_unref0 (self->priv->editor);
	_g_free0 (self->priv->untitled);
	_g_object_unref0 (self->priv->_completion);
	_g_object_unref0 (self->priv->_text_view);
	_g_object_unref0 (self->priv->evt_box);
	_g_object_unref0 (self->priv->title_label);
	_g_object_unref0 (self->priv->close_button);
	_g_object_unref0 (self->priv->separator);
	_g_object_unref0 (self->priv->_tab_widget);
	_g_free0 (self->priv->_tab_title);
	G_OBJECT_CLASS (simple_tab_parent_class)->finalize (obj);
}


GType simple_tab_get_type (void) {
	static volatile gsize simple_tab_type_id__volatile = 0;
	if (g_once_init_enter (&simple_tab_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SimpleTabClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) simple_tab_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SimpleTab), 0, (GInstanceInitFunc) simple_tab_instance_init, NULL };
		GType simple_tab_type_id;
		simple_tab_type_id = g_type_register_static (gtk_box_get_type (), "SimpleTab", &g_define_type_info, 0);
		g_once_init_leave (&simple_tab_type_id__volatile, simple_tab_type_id);
	}
	return simple_tab_type_id__volatile;
}


static void _vala_simple_tab_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SimpleTab * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_SIMPLE_TAB, SimpleTab);
	switch (property_id) {
		case SIMPLE_TAB_COMPLETION:
		g_value_set_object (value, simple_tab_get_completion (self));
		break;
		case SIMPLE_TAB_TEXT_VIEW:
		g_value_set_object (value, simple_tab_get_text_view (self));
		break;
		case SIMPLE_TAB_TAB_WIDGET:
		g_value_set_object (value, simple_tab_get_tab_widget (self));
		break;
		case SIMPLE_TAB_TAB_TITLE:
		g_value_set_string (value, simple_tab_get_tab_title (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_simple_tab_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SimpleTab * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_SIMPLE_TAB, SimpleTab);
	switch (property_id) {
		case SIMPLE_TAB_TAB_WIDGET:
		simple_tab_set_tab_widget (self, g_value_get_object (value));
		break;
		case SIMPLE_TAB_TAB_TITLE:
		simple_tab_set_tab_title (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



