/* st-source-view.c generated by valac 0.28.0, the Vala compiler
 * generated from st-source-view.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtksourceview/gtksource.h>
#include <gtksourceview/completion-providers/words/gtksourcecompletionwords.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>
#include <stdio.h>
#include <pango/pango.h>
#include <gdk/gdk.h>


#define TYPE_ST_SOURCE_VIEW (st_source_view_get_type ())
#define ST_SOURCE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ST_SOURCE_VIEW, StSourceView))
#define ST_SOURCE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ST_SOURCE_VIEW, StSourceViewClass))
#define IS_ST_SOURCE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ST_SOURCE_VIEW))
#define IS_ST_SOURCE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ST_SOURCE_VIEW))
#define ST_SOURCE_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ST_SOURCE_VIEW, StSourceViewClass))

typedef struct _StSourceView StSourceView;
typedef struct _StSourceViewClass StSourceViewClass;
typedef struct _StSourceViewPrivate StSourceViewPrivate;

#define TYPE_ST_TEXT_EDITOR (st_text_editor_get_type ())
#define ST_TEXT_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ST_TEXT_EDITOR, StTextEditor))
#define ST_TEXT_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ST_TEXT_EDITOR, StTextEditorClass))
#define IS_ST_TEXT_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ST_TEXT_EDITOR))
#define IS_ST_TEXT_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ST_TEXT_EDITOR))
#define ST_TEXT_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ST_TEXT_EDITOR, StTextEditorClass))

typedef struct _StTextEditor StTextEditor;
typedef struct _StTextEditorClass StTextEditorClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define __vala_PangoFontDescription_free0(var) ((var == NULL) ? NULL : (var = (_vala_PangoFontDescription_free (var), NULL)))

struct _StSourceView {
	GtkSourceView parent_instance;
	StSourceViewPrivate * priv;
};

struct _StSourceViewClass {
	GtkSourceViewClass parent_class;
};

struct _StSourceViewPrivate {
	gboolean insert_matching_braces;
	GtkSourceSearchSettings* _search_settings;
	GtkSourceCompletionWords* word_completion;
	GtkSourceFile* _source_file;
	GtkSourceFileSaver* file_saver;
	GtkSourceFileLoader* file_loader;
	StTextEditor* editor;
};


static gpointer st_source_view_parent_class = NULL;

GType st_source_view_get_type (void) G_GNUC_CONST;
GType st_text_editor_get_type (void) G_GNUC_CONST;
#define ST_SOURCE_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_ST_SOURCE_VIEW, StSourceViewPrivate))
enum  {
	ST_SOURCE_VIEW_DUMMY_PROPERTY,
	ST_SOURCE_VIEW_SEARCH_SETTINGS,
	ST_SOURCE_VIEW_SOURCE_FILE
};
#define ST_SOURCE_VIEW_TARGET_TYPE_URI_LIST 80
StSourceView* st_source_view_new (StTextEditor* editor, const gchar* filename);
StSourceView* st_source_view_construct (GType object_type, StTextEditor* editor, const gchar* filename);
GtkSourceFile* st_source_view_get_source_file (StSourceView* self);
static void st_source_view_load_view_format (StSourceView* self);
static void st_source_view_connect_signals (StSourceView* self);
static void st_source_view_set_properties (StSourceView* self);
const gchar* st_text_editor_get_color_scheme (StTextEditor* self);
static void st_source_view_load_file (StSourceView* self);
void st_source_view_save_file (StSourceView* self, GFile* target);
gboolean st_text_editor_get_show_line_numbers (StTextEditor* self);
gboolean st_text_editor_get_show_right_margin (StTextEditor* self);
gint st_text_editor_get_right_margin_at (StTextEditor* self);
gboolean st_text_editor_get_highlight_current_line (StTextEditor* self);
gboolean st_text_editor_get_highlight_brackets (StTextEditor* self);
gboolean st_text_editor_get_insert_braces (StTextEditor* self);
gint st_text_editor_get_tab_width (StTextEditor* self);
gboolean st_text_editor_get_insert_spaces (StTextEditor* self);
gboolean st_text_editor_get_auto_indent (StTextEditor* self);
const gchar* st_text_editor_get_editor_font (StTextEditor* self);
static void _vala_PangoFontDescription_free (PangoFontDescription* self);
gboolean st_text_editor_get_show_grid_pattern (StTextEditor* self);
static void st_source_view_on_drag_data_received (StSourceView* self, GtkWidget* widget, GdkDragContext* context, gint x, gint y, GtkSelectionData* selection_data, guint target_type, guint time);
static void _st_source_view_on_drag_data_received_gtk_widget_drag_data_received (GtkWidget* _sender, GdkDragContext* context, gint x, gint y, GtkSelectionData* selection_data, guint info, guint time_, gpointer self);
static void st_source_view_brace_insert (StSourceView* self, GtkTextIter* location, const gchar* text, gint len);
static void _st_source_view_brace_insert_gtk_text_buffer_insert_text (GtkTextBuffer* _sender, GtkTextIter* pos, const gchar* new_text, gint new_text_length, gpointer self);
void st_source_view_change_language (StSourceView* self, const gchar* language);
static void __lambda4_ (StSourceView* self, GParamSpec* pspec);
static void ___lambda4__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda5_ (StSourceView* self, GParamSpec* pspec);
static void ___lambda5__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda6_ (StSourceView* self, GParamSpec* pspec);
static void ___lambda6__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda7_ (StSourceView* self, GParamSpec* pspec);
static void ___lambda7__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda8_ (StSourceView* self, GParamSpec* pspec);
static void ___lambda8__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda9_ (StSourceView* self, GParamSpec* pspec);
static void ___lambda9__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda10_ (StSourceView* self, GParamSpec* pspec);
static void ___lambda10__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda11_ (StSourceView* self, GParamSpec* pspec);
static void ___lambda11__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda12_ (StSourceView* self, GParamSpec* pspec);
static void ___lambda12__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda13_ (StSourceView* self, GParamSpec* pspec);
gboolean st_text_editor_get_use_default_typo (StTextEditor* self);
static void ___lambda13__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda14_ (StSourceView* self, GParamSpec* pspec);
static void ___lambda14__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda15_ (StSourceView* self, GParamSpec* pspec);
static void ___lambda15__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda16_ (StSourceView* self, GParamSpec* pspec);
static void ___lambda16__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void st_source_view_on_buffer_changes (StSourceView* self);
static void _st_source_view_on_buffer_changes_gtk_text_buffer_modified_changed (GtkTextBuffer* _sender, gpointer self);
static gchar* st_source_view_get_file_path_from_uri (StSourceView* self, const gchar* uri);
gchar* st_source_view_get_language_name (StSourceView* self);
GtkSourceBuffer* st_source_view_get_source_buffer (StSourceView* self);
GtkSourceSearchSettings* st_source_view_get_search_settings (StSourceView* self);
static void st_source_view_finalize (GObject* obj);
static void _vala_st_source_view_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);

static const GtkTargetEntry ST_SOURCE_VIEW_target_list[1] = {{"text/uri-list", (guint) 0, (guint) ST_SOURCE_VIEW_TARGET_TYPE_URI_LIST}};

static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


StSourceView* st_source_view_construct (GType object_type, StTextEditor* editor, const gchar* filename) {
	StSourceView * self = NULL;
	StTextEditor* _tmp0_ = NULL;
	StTextEditor* _tmp1_ = NULL;
	GtkSourceFile* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (editor != NULL, NULL);
	self = (StSourceView*) g_object_new (object_type, NULL);
	_tmp0_ = editor;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->editor);
	self->priv->editor = _tmp1_;
	_tmp2_ = gtk_source_file_new ();
	_g_object_unref0 (self->priv->_source_file);
	self->priv->_source_file = _tmp2_;
	_tmp3_ = filename;
	if (_tmp3_ != NULL) {
		GtkSourceFile* _tmp4_ = NULL;
		GtkSourceFile* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		GFile* _tmp7_ = NULL;
		GFile* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		GtkSourceCompletionWords* _tmp10_ = NULL;
		GtkSourceCompletionWords* _tmp11_ = NULL;
		GtkSourceCompletionWords* _tmp12_ = NULL;
		_tmp4_ = st_source_view_get_source_file (self);
		_tmp5_ = _tmp4_;
		_tmp6_ = filename;
		_tmp7_ = g_file_new_for_path (_tmp6_);
		_tmp8_ = _tmp7_;
		gtk_source_file_set_location (_tmp5_, _tmp8_);
		_g_object_unref0 (_tmp8_);
		_tmp9_ = _ ("Document words");
		_tmp10_ = gtk_source_completion_words_new (_tmp9_, NULL);
		_g_object_unref0 (self->priv->word_completion);
		self->priv->word_completion = _tmp10_;
		_tmp11_ = self->priv->word_completion;
		g_object_set (_tmp11_, "activation", GTK_SOURCE_COMPLETION_ACTIVATION_USER_REQUESTED | GTK_SOURCE_COMPLETION_ACTIVATION_INTERACTIVE, NULL);
		_tmp12_ = self->priv->word_completion;
		g_object_set (_tmp12_, "interactive-delay", 25, NULL);
		{
			GtkSourceCompletion* _tmp13_ = NULL;
			GtkSourceCompletion* _tmp14_ = NULL;
			GtkSourceCompletionWords* _tmp15_ = NULL;
			GtkSourceCompletion* _tmp16_ = NULL;
			GtkSourceCompletion* _tmp17_ = NULL;
			GtkSourceCompletion* _tmp18_ = NULL;
			GtkSourceCompletion* _tmp19_ = NULL;
			GtkSourceCompletion* _tmp20_ = NULL;
			GtkSourceCompletion* _tmp21_ = NULL;
			_tmp13_ = gtk_source_view_get_completion ((GtkSourceView*) self);
			_tmp14_ = _tmp13_;
			_tmp15_ = self->priv->word_completion;
			gtk_source_completion_add_provider (_tmp14_, (GtkSourceCompletionProvider*) _tmp15_, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch6_g_error;
			}
			_tmp16_ = gtk_source_view_get_completion ((GtkSourceView*) self);
			_tmp17_ = _tmp16_;
			g_object_set (_tmp17_, "auto-complete-delay", (guint) 200, NULL);
			_tmp18_ = gtk_source_view_get_completion ((GtkSourceView*) self);
			_tmp19_ = _tmp18_;
			g_object_set (_tmp19_, "show-headers", FALSE, NULL);
			_tmp20_ = gtk_source_view_get_completion ((GtkSourceView*) self);
			_tmp21_ = _tmp20_;
			g_object_set (_tmp21_, "show-icons", FALSE, NULL);
		}
		goto __finally6;
		__catch6_g_error:
		{
			GError* e = NULL;
			FILE* _tmp22_ = NULL;
			GError* _tmp23_ = NULL;
			const gchar* _tmp24_ = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp22_ = stderr;
			_tmp23_ = e;
			_tmp24_ = _tmp23_->message;
			fprintf (_tmp22_, "%s\n", _tmp24_);
			_g_error_free0 (e);
		}
		__finally6:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	st_source_view_load_view_format (self);
	st_source_view_connect_signals (self);
	st_source_view_set_properties (self);
	return self;
}


StSourceView* st_source_view_new (StTextEditor* editor, const gchar* filename) {
	return st_source_view_construct (TYPE_ST_SOURCE_VIEW, editor, filename);
}


static void st_source_view_load_view_format (StSourceView* self) {
	GtkTextBuffer* _tmp0_ = NULL;
	GtkTextBuffer* _tmp1_ = NULL;
	GtkSourceFile* _tmp2_ = NULL;
	GtkSourceFile* _tmp3_ = NULL;
	GtkSourceFileLoader* _tmp4_ = NULL;
	GtkTextBuffer* _tmp5_ = NULL;
	GtkTextBuffer* _tmp6_ = NULL;
	GtkSourceFile* _tmp7_ = NULL;
	GtkSourceFile* _tmp8_ = NULL;
	GtkSourceFileSaver* _tmp9_ = NULL;
	GtkSourceStyleSchemeManager* scheme_manager = NULL;
	GtkSourceStyleSchemeManager* _tmp10_ = NULL;
	GtkSourceStyleSchemeManager* _tmp11_ = NULL;
	GtkSourceStyleScheme* source_scheme = NULL;
	StTextEditor* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	const gchar* _tmp14_ = NULL;
	GtkSourceStyleScheme* _tmp15_ = NULL;
	GtkSourceStyleScheme* _tmp16_ = NULL;
	GtkTextBuffer* _tmp17_ = NULL;
	GtkTextBuffer* _tmp18_ = NULL;
	GtkTextBuffer* _tmp19_ = NULL;
	GtkTextBuffer* _tmp20_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = st_source_view_get_source_file (self);
	_tmp3_ = _tmp2_;
	_tmp4_ = gtk_source_file_loader_new (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp1_) : NULL, _tmp3_);
	_g_object_unref0 (self->priv->file_loader);
	self->priv->file_loader = _tmp4_;
	_tmp5_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp6_ = _tmp5_;
	_tmp7_ = st_source_view_get_source_file (self);
	_tmp8_ = _tmp7_;
	_tmp9_ = gtk_source_file_saver_new (G_TYPE_CHECK_INSTANCE_TYPE (_tmp6_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp6_) : NULL, _tmp8_);
	_g_object_unref0 (self->priv->file_saver);
	self->priv->file_saver = _tmp9_;
	_tmp10_ = gtk_source_style_scheme_manager_get_default ();
	_tmp11_ = _g_object_ref0 (_tmp10_);
	scheme_manager = _tmp11_;
	_tmp12_ = self->priv->editor;
	_tmp13_ = st_text_editor_get_color_scheme (_tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = gtk_source_style_scheme_manager_get_scheme (scheme_manager, _tmp14_);
	_tmp16_ = _g_object_ref0 (_tmp15_);
	source_scheme = _tmp16_;
	_tmp17_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp18_ = _tmp17_;
	gtk_source_buffer_set_style_scheme (G_TYPE_CHECK_INSTANCE_TYPE (_tmp18_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp18_) : NULL, source_scheme);
	_tmp19_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp20_ = _tmp19_;
	gtk_source_buffer_set_highlight_syntax (G_TYPE_CHECK_INSTANCE_TYPE (_tmp20_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp20_) : NULL, TRUE);
	st_source_view_load_file (self);
	_g_object_unref0 (source_scheme);
	_g_object_unref0 (scheme_manager);
}


static guint8* string_get_data (const gchar* self, int* result_length1) {
	guint8* result;
	guint8* res = NULL;
	gint res_length1 = 0;
	gint _res_size_ = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	guint8* _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	guint8* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = res_length1;
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	res_length1 = (gint) _tmp1_;
	_tmp2_ = res_length1;
	_tmp3_ = res;
	_tmp3__length1 = res_length1;
	_tmp4_ = _tmp3_;
	_tmp4__length1 = _tmp3__length1;
	if (result_length1) {
		*result_length1 = _tmp4__length1;
	}
	result = _tmp4_;
	return result;
}


static void st_source_view_load_file (StSourceView* self) {
	GtkSourceFile* _tmp0_ = NULL;
	GtkSourceFile* _tmp1_ = NULL;
	GFile* _tmp2_ = NULL;
	GFile* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = st_source_view_get_source_file (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = gtk_source_file_get_location (_tmp1_);
	_tmp3_ = _tmp2_;
	if (_tmp3_ != NULL) {
		GtkSourceFileLoader* _tmp4_ = NULL;
		gboolean result_uncertain = FALSE;
		gchar* content_type = NULL;
		GtkSourceFile* _tmp5_ = NULL;
		GtkSourceFile* _tmp6_ = NULL;
		GFile* _tmp7_ = NULL;
		GFile* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		GtkTextBuffer* _tmp11_ = NULL;
		GtkTextBuffer* _tmp12_ = NULL;
		gchar* _tmp13_ = NULL;
		gchar* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		guint8* _tmp16_ = NULL;
		gint _tmp16__length1 = 0;
		guint8* _tmp17_ = NULL;
		gint _tmp17__length1 = 0;
		gboolean _tmp18_ = FALSE;
		gchar* _tmp19_ = NULL;
		gchar* _tmp20_ = NULL;
		gboolean _tmp21_ = FALSE;
		GtkSourceLanguageManager* lang_manager = NULL;
		GtkSourceLanguageManager* _tmp22_ = NULL;
		GtkSourceLanguageManager* _tmp23_ = NULL;
		GtkSourceLanguage* source_lang = NULL;
		GtkSourceLanguageManager* _tmp24_ = NULL;
		GtkSourceFile* _tmp25_ = NULL;
		GtkSourceFile* _tmp26_ = NULL;
		GFile* _tmp27_ = NULL;
		GFile* _tmp28_ = NULL;
		gchar* _tmp29_ = NULL;
		gchar* _tmp30_ = NULL;
		const gchar* _tmp31_ = NULL;
		GtkSourceLanguage* _tmp32_ = NULL;
		GtkSourceLanguage* _tmp33_ = NULL;
		GtkSourceLanguage* _tmp34_ = NULL;
		GtkTextBuffer* _tmp35_ = NULL;
		GtkTextBuffer* _tmp36_ = NULL;
		GtkSourceLanguage* _tmp37_ = NULL;
		GtkTextBuffer* _tmp38_ = NULL;
		GtkTextBuffer* _tmp39_ = NULL;
		_tmp4_ = self->priv->file_loader;
		gtk_source_file_loader_load_async (_tmp4_, G_PRIORITY_HIGH, NULL, NULL, NULL, NULL, NULL, NULL);
		_tmp5_ = st_source_view_get_source_file (self);
		_tmp6_ = _tmp5_;
		_tmp7_ = gtk_source_file_get_location (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = g_file_get_path (_tmp8_);
		_tmp10_ = _tmp9_;
		_tmp11_ = gtk_text_view_get_buffer ((GtkTextView*) self);
		_tmp12_ = _tmp11_;
		g_object_get (_tmp12_, "text", &_tmp13_, NULL);
		_tmp14_ = _tmp13_;
		_tmp15_ = _tmp14_;
		_tmp16_ = string_get_data (_tmp15_, &_tmp16__length1);
		_tmp17_ = _tmp16_;
		_tmp17__length1 = _tmp16__length1;
		_tmp19_ = g_content_type_guess (_tmp10_, _tmp17_, (gsize) _tmp17__length1, &_tmp18_);
		result_uncertain = _tmp18_;
		_tmp20_ = _tmp19_;
		_g_free0 (_tmp15_);
		_g_free0 (_tmp10_);
		content_type = _tmp20_;
		_tmp21_ = result_uncertain;
		if (_tmp21_) {
			_g_free0 (content_type);
			content_type = NULL;
		}
		_tmp22_ = gtk_source_language_manager_get_default ();
		_tmp23_ = _g_object_ref0 (_tmp22_);
		lang_manager = _tmp23_;
		_tmp24_ = lang_manager;
		_tmp25_ = st_source_view_get_source_file (self);
		_tmp26_ = _tmp25_;
		_tmp27_ = gtk_source_file_get_location (_tmp26_);
		_tmp28_ = _tmp27_;
		_tmp29_ = g_file_get_path (_tmp28_);
		_tmp30_ = _tmp29_;
		_tmp31_ = content_type;
		_tmp32_ = gtk_source_language_manager_guess_language (_tmp24_, _tmp30_, _tmp31_);
		_tmp33_ = _g_object_ref0 (_tmp32_);
		_tmp34_ = _tmp33_;
		_g_free0 (_tmp30_);
		source_lang = _tmp34_;
		_tmp35_ = gtk_text_view_get_buffer ((GtkTextView*) self);
		_tmp36_ = _tmp35_;
		_tmp37_ = source_lang;
		gtk_source_buffer_set_language (G_TYPE_CHECK_INSTANCE_TYPE (_tmp36_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp36_) : NULL, _tmp37_);
		_tmp38_ = gtk_text_view_get_buffer ((GtkTextView*) self);
		_tmp39_ = _tmp38_;
		gtk_text_buffer_set_modified (_tmp39_, FALSE);
		g_signal_emit_by_name (self, "file-loaded");
		_g_object_unref0 (source_lang);
		_g_object_unref0 (lang_manager);
		_g_free0 (content_type);
	}
}


void st_source_view_save_file (StSourceView* self, GFile* target) {
	GFile* _tmp0_ = NULL;
	GtkSourceFileSaver* _tmp36_ = NULL;
	GtkTextBuffer* _tmp37_ = NULL;
	GtkTextBuffer* _tmp38_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = target;
	if (_tmp0_ != NULL) {
		GtkSourceFile* _tmp1_ = NULL;
		GFile* _tmp2_ = NULL;
		gboolean result_uncertain = FALSE;
		gchar* content_type = NULL;
		GtkSourceFile* _tmp3_ = NULL;
		GtkSourceFile* _tmp4_ = NULL;
		GFile* _tmp5_ = NULL;
		GFile* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		GtkTextBuffer* _tmp9_ = NULL;
		GtkTextBuffer* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_ = NULL;
		guint8* _tmp14_ = NULL;
		gint _tmp14__length1 = 0;
		guint8* _tmp15_ = NULL;
		gint _tmp15__length1 = 0;
		gboolean _tmp16_ = FALSE;
		gchar* _tmp17_ = NULL;
		gchar* _tmp18_ = NULL;
		gboolean _tmp19_ = FALSE;
		GtkSourceLanguageManager* lang_manager = NULL;
		GtkSourceLanguageManager* _tmp20_ = NULL;
		GtkSourceLanguageManager* _tmp21_ = NULL;
		GtkSourceLanguage* source_lang = NULL;
		GtkSourceLanguageManager* _tmp22_ = NULL;
		GtkSourceFile* _tmp23_ = NULL;
		GtkSourceFile* _tmp24_ = NULL;
		GFile* _tmp25_ = NULL;
		GFile* _tmp26_ = NULL;
		gchar* _tmp27_ = NULL;
		gchar* _tmp28_ = NULL;
		const gchar* _tmp29_ = NULL;
		GtkSourceLanguage* _tmp30_ = NULL;
		GtkSourceLanguage* _tmp31_ = NULL;
		GtkSourceLanguage* _tmp32_ = NULL;
		GtkTextBuffer* _tmp33_ = NULL;
		GtkTextBuffer* _tmp34_ = NULL;
		GtkSourceLanguage* _tmp35_ = NULL;
		_tmp1_ = self->priv->_source_file;
		_tmp2_ = target;
		gtk_source_file_set_location (_tmp1_, _tmp2_);
		_tmp3_ = st_source_view_get_source_file (self);
		_tmp4_ = _tmp3_;
		_tmp5_ = gtk_source_file_get_location (_tmp4_);
		_tmp6_ = _tmp5_;
		_tmp7_ = g_file_get_path (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = gtk_text_view_get_buffer ((GtkTextView*) self);
		_tmp10_ = _tmp9_;
		g_object_get (_tmp10_, "text", &_tmp11_, NULL);
		_tmp12_ = _tmp11_;
		_tmp13_ = _tmp12_;
		_tmp14_ = string_get_data (_tmp13_, &_tmp14__length1);
		_tmp15_ = _tmp14_;
		_tmp15__length1 = _tmp14__length1;
		_tmp17_ = g_content_type_guess (_tmp8_, _tmp15_, (gsize) _tmp15__length1, &_tmp16_);
		result_uncertain = _tmp16_;
		_tmp18_ = _tmp17_;
		_g_free0 (_tmp13_);
		_g_free0 (_tmp8_);
		content_type = _tmp18_;
		_tmp19_ = result_uncertain;
		if (_tmp19_) {
			_g_free0 (content_type);
			content_type = NULL;
		}
		_tmp20_ = gtk_source_language_manager_get_default ();
		_tmp21_ = _g_object_ref0 (_tmp20_);
		lang_manager = _tmp21_;
		_tmp22_ = lang_manager;
		_tmp23_ = st_source_view_get_source_file (self);
		_tmp24_ = _tmp23_;
		_tmp25_ = gtk_source_file_get_location (_tmp24_);
		_tmp26_ = _tmp25_;
		_tmp27_ = g_file_get_path (_tmp26_);
		_tmp28_ = _tmp27_;
		_tmp29_ = content_type;
		_tmp30_ = gtk_source_language_manager_guess_language (_tmp22_, _tmp28_, _tmp29_);
		_tmp31_ = _g_object_ref0 (_tmp30_);
		_tmp32_ = _tmp31_;
		_g_free0 (_tmp28_);
		source_lang = _tmp32_;
		_tmp33_ = gtk_text_view_get_buffer ((GtkTextView*) self);
		_tmp34_ = _tmp33_;
		_tmp35_ = source_lang;
		gtk_source_buffer_set_language (G_TYPE_CHECK_INSTANCE_TYPE (_tmp34_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp34_) : NULL, _tmp35_);
		_g_object_unref0 (source_lang);
		_g_object_unref0 (lang_manager);
		_g_free0 (content_type);
	}
	_tmp36_ = self->priv->file_saver;
	gtk_source_file_saver_save_async (_tmp36_, G_PRIORITY_HIGH, NULL, NULL, NULL, NULL, NULL, NULL);
	_tmp37_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp38_ = _tmp37_;
	gtk_text_buffer_set_modified (_tmp38_, FALSE);
	g_signal_emit_by_name (self, "file-saved");
}


static void _vala_PangoFontDescription_free (PangoFontDescription* self) {
	g_boxed_free (pango_font_description_get_type (), self);
}


static void _st_source_view_on_drag_data_received_gtk_widget_drag_data_received (GtkWidget* _sender, GdkDragContext* context, gint x, gint y, GtkSelectionData* selection_data, guint info, guint time_, gpointer self) {
	st_source_view_on_drag_data_received ((StSourceView*) self, _sender, context, x, y, selection_data, info, time_);
}


static void _st_source_view_brace_insert_gtk_text_buffer_insert_text (GtkTextBuffer* _sender, GtkTextIter* pos, const gchar* new_text, gint new_text_length, gpointer self) {
	st_source_view_brace_insert ((StSourceView*) self, pos, new_text, new_text_length);
}


static void st_source_view_set_properties (StSourceView* self) {
	StTextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	StTextEditor* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	gboolean _tmp5_ = FALSE;
	StTextEditor* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	StTextEditor* _tmp9_ = NULL;
	gboolean _tmp10_ = FALSE;
	gboolean _tmp11_ = FALSE;
	GtkTextBuffer* _tmp12_ = NULL;
	GtkTextBuffer* _tmp13_ = NULL;
	StTextEditor* _tmp14_ = NULL;
	gboolean _tmp15_ = FALSE;
	gboolean _tmp16_ = FALSE;
	StTextEditor* _tmp17_ = NULL;
	gboolean _tmp18_ = FALSE;
	gboolean _tmp19_ = FALSE;
	StTextEditor* _tmp20_ = NULL;
	gint _tmp21_ = 0;
	gint _tmp22_ = 0;
	StTextEditor* _tmp23_ = NULL;
	gboolean _tmp24_ = FALSE;
	gboolean _tmp25_ = FALSE;
	StTextEditor* _tmp26_ = NULL;
	gboolean _tmp27_ = FALSE;
	gboolean _tmp28_ = FALSE;
	StTextEditor* _tmp29_ = NULL;
	const gchar* _tmp30_ = NULL;
	const gchar* _tmp31_ = NULL;
	PangoFontDescription* _tmp32_ = NULL;
	PangoFontDescription* _tmp33_ = NULL;
	StTextEditor* _tmp34_ = NULL;
	gboolean _tmp35_ = FALSE;
	gboolean _tmp36_ = FALSE;
	GtkSourceSearchSettings* _tmp37_ = NULL;
	GtkSourceSearchSettings* _tmp38_ = NULL;
	GtkSourceSearchSettings* _tmp39_ = NULL;
	GtkSourceSearchSettings* _tmp40_ = NULL;
	GtkSourceSearchSettings* _tmp41_ = NULL;
	GtkSourceSearchSettings* _tmp42_ = NULL;
	GtkTextBuffer* _tmp43_ = NULL;
	GtkTextBuffer* _tmp44_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = st_text_editor_get_show_line_numbers (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_show_line_numbers ((GtkSourceView*) self, _tmp2_);
	_tmp3_ = self->priv->editor;
	_tmp4_ = st_text_editor_get_show_right_margin (_tmp3_);
	_tmp5_ = _tmp4_;
	gtk_source_view_set_show_right_margin ((GtkSourceView*) self, _tmp5_);
	_tmp6_ = self->priv->editor;
	_tmp7_ = st_text_editor_get_right_margin_at (_tmp6_);
	_tmp8_ = _tmp7_;
	gtk_source_view_set_right_margin_position ((GtkSourceView*) self, (guint) _tmp8_);
	_tmp9_ = self->priv->editor;
	_tmp10_ = st_text_editor_get_highlight_current_line (_tmp9_);
	_tmp11_ = _tmp10_;
	gtk_source_view_set_highlight_current_line ((GtkSourceView*) self, _tmp11_);
	_tmp12_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp13_ = _tmp12_;
	_tmp14_ = self->priv->editor;
	_tmp15_ = st_text_editor_get_highlight_brackets (_tmp14_);
	_tmp16_ = _tmp15_;
	gtk_source_buffer_set_highlight_matching_brackets (G_TYPE_CHECK_INSTANCE_TYPE (_tmp13_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp13_) : NULL, _tmp16_);
	_tmp17_ = self->priv->editor;
	_tmp18_ = st_text_editor_get_insert_braces (_tmp17_);
	_tmp19_ = _tmp18_;
	self->priv->insert_matching_braces = _tmp19_;
	_tmp20_ = self->priv->editor;
	_tmp21_ = st_text_editor_get_tab_width (_tmp20_);
	_tmp22_ = _tmp21_;
	gtk_source_view_set_tab_width ((GtkSourceView*) self, (guint) _tmp22_);
	_tmp23_ = self->priv->editor;
	_tmp24_ = st_text_editor_get_insert_spaces (_tmp23_);
	_tmp25_ = _tmp24_;
	gtk_source_view_set_insert_spaces_instead_of_tabs ((GtkSourceView*) self, _tmp25_);
	_tmp26_ = self->priv->editor;
	_tmp27_ = st_text_editor_get_auto_indent (_tmp26_);
	_tmp28_ = _tmp27_;
	gtk_source_view_set_auto_indent ((GtkSourceView*) self, _tmp28_);
	_tmp29_ = self->priv->editor;
	_tmp30_ = st_text_editor_get_editor_font (_tmp29_);
	_tmp31_ = _tmp30_;
	_tmp32_ = pango_font_description_from_string (_tmp31_);
	_tmp33_ = _tmp32_;
	gtk_widget_override_font ((GtkWidget*) self, _tmp33_);
	__vala_PangoFontDescription_free0 (_tmp33_);
	_tmp34_ = self->priv->editor;
	_tmp35_ = st_text_editor_get_show_grid_pattern (_tmp34_);
	_tmp36_ = _tmp35_;
	if (_tmp36_) {
		gtk_source_view_set_background_pattern ((GtkSourceView*) self, GTK_SOURCE_BACKGROUND_PATTERN_TYPE_GRID);
	} else {
		gtk_source_view_set_background_pattern ((GtkSourceView*) self, GTK_SOURCE_BACKGROUND_PATTERN_TYPE_NONE);
	}
	gtk_source_view_set_smart_home_end ((GtkSourceView*) self, GTK_SOURCE_SMART_HOME_END_BEFORE);
	gtk_text_view_set_wrap_mode ((GtkTextView*) self, GTK_WRAP_NONE);
	gtk_drag_dest_set ((GtkWidget*) self, (GTK_DEST_DEFAULT_MOTION | GTK_DEST_DEFAULT_HIGHLIGHT) | GTK_DEST_DEFAULT_DROP, ST_SOURCE_VIEW_target_list, G_N_ELEMENTS (ST_SOURCE_VIEW_target_list), GDK_ACTION_COPY);
	_tmp37_ = gtk_source_search_settings_new ();
	_g_object_unref0 (self->priv->_search_settings);
	self->priv->_search_settings = _tmp37_;
	_tmp38_ = self->priv->_search_settings;
	gtk_source_search_settings_set_at_word_boundaries (_tmp38_, FALSE);
	_tmp39_ = self->priv->_search_settings;
	gtk_source_search_settings_set_case_sensitive (_tmp39_, FALSE);
	_tmp40_ = self->priv->_search_settings;
	gtk_source_search_settings_set_regex_enabled (_tmp40_, FALSE);
	_tmp41_ = self->priv->_search_settings;
	gtk_source_search_settings_set_search_text (_tmp41_, NULL);
	_tmp42_ = self->priv->_search_settings;
	gtk_source_search_settings_set_wrap_around (_tmp42_, TRUE);
	g_signal_connect_object ((GtkWidget*) self, "drag-data-received", (GCallback) _st_source_view_on_drag_data_received_gtk_widget_drag_data_received, self, 0);
	_tmp43_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp44_ = _tmp43_;
	g_signal_connect_object (_tmp44_, "insert-text", (GCallback) _st_source_view_brace_insert_gtk_text_buffer_insert_text, self, G_CONNECT_AFTER);
}


void st_source_view_change_language (StSourceView* self, const gchar* language) {
	GtkSourceLanguageManager* lang_manager = NULL;
	GtkSourceLanguageManager* _tmp0_ = NULL;
	GtkSourceLanguageManager* _tmp1_ = NULL;
	GtkSourceLanguage* source_lang = NULL;
	const gchar* _tmp2_ = NULL;
	GtkSourceLanguage* _tmp3_ = NULL;
	GtkSourceLanguage* _tmp4_ = NULL;
	GtkTextBuffer* _tmp5_ = NULL;
	GtkTextBuffer* _tmp6_ = NULL;
	GtkTextBuffer* _tmp7_ = NULL;
	GtkTextBuffer* _tmp8_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (language != NULL);
	_tmp0_ = gtk_source_language_manager_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	lang_manager = _tmp1_;
	_tmp2_ = language;
	_tmp3_ = gtk_source_language_manager_get_language (lang_manager, _tmp2_);
	_tmp4_ = _g_object_ref0 (_tmp3_);
	source_lang = _tmp4_;
	_tmp5_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp6_ = _tmp5_;
	gtk_source_buffer_set_language (G_TYPE_CHECK_INSTANCE_TYPE (_tmp6_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp6_) : NULL, source_lang);
	_tmp7_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp8_ = _tmp7_;
	gtk_text_buffer_set_modified (_tmp8_, FALSE);
	_g_object_unref0 (source_lang);
	_g_object_unref0 (lang_manager);
}


static void __lambda4_ (StSourceView* self, GParamSpec* pspec) {
	StTextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = st_text_editor_get_show_line_numbers (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_show_line_numbers ((GtkSourceView*) self, _tmp2_);
}


static void ___lambda4__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda4_ ((StSourceView*) self, pspec);
}


static void __lambda5_ (StSourceView* self, GParamSpec* pspec) {
	StTextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = st_text_editor_get_show_right_margin (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_show_right_margin ((GtkSourceView*) self, _tmp2_);
}


static void ___lambda5__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda5_ ((StSourceView*) self, pspec);
}


static void __lambda6_ (StSourceView* self, GParamSpec* pspec) {
	StTextEditor* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = st_text_editor_get_right_margin_at (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_right_margin_position ((GtkSourceView*) self, (guint) _tmp2_);
}


static void ___lambda6__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda6_ ((StSourceView*) self, pspec);
}


static void __lambda7_ (StSourceView* self, GParamSpec* pspec) {
	StTextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = st_text_editor_get_highlight_current_line (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_highlight_current_line ((GtkSourceView*) self, _tmp2_);
}


static void ___lambda7__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda7_ ((StSourceView*) self, pspec);
}


static void __lambda8_ (StSourceView* self, GParamSpec* pspec) {
	GtkTextBuffer* _tmp0_ = NULL;
	GtkTextBuffer* _tmp1_ = NULL;
	StTextEditor* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = self->priv->editor;
	_tmp3_ = st_text_editor_get_highlight_brackets (_tmp2_);
	_tmp4_ = _tmp3_;
	gtk_source_buffer_set_highlight_matching_brackets (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp1_) : NULL, _tmp4_);
}


static void ___lambda8__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda8_ ((StSourceView*) self, pspec);
}


static void __lambda9_ (StSourceView* self, GParamSpec* pspec) {
	StTextEditor* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = st_text_editor_get_tab_width (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_tab_width ((GtkSourceView*) self, (guint) _tmp2_);
}


static void ___lambda9__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda9_ ((StSourceView*) self, pspec);
}


static void __lambda10_ (StSourceView* self, GParamSpec* pspec) {
	StTextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = st_text_editor_get_insert_spaces (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_insert_spaces_instead_of_tabs ((GtkSourceView*) self, _tmp2_);
}


static void ___lambda10__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda10_ ((StSourceView*) self, pspec);
}


static void __lambda11_ (StSourceView* self, GParamSpec* pspec) {
	StTextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = st_text_editor_get_auto_indent (_tmp0_);
	_tmp2_ = _tmp1_;
	gtk_source_view_set_auto_indent ((GtkSourceView*) self, _tmp2_);
}


static void ___lambda11__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda11_ ((StSourceView*) self, pspec);
}


static void __lambda12_ (StSourceView* self, GParamSpec* pspec) {
	StTextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = st_text_editor_get_show_grid_pattern (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		gtk_source_view_set_background_pattern ((GtkSourceView*) self, GTK_SOURCE_BACKGROUND_PATTERN_TYPE_GRID);
	} else {
		gtk_source_view_set_background_pattern ((GtkSourceView*) self, GTK_SOURCE_BACKGROUND_PATTERN_TYPE_NONE);
	}
}


static void ___lambda12__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda12_ ((StSourceView*) self, pspec);
}


static void __lambda13_ (StSourceView* self, GParamSpec* pspec) {
	StTextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = st_text_editor_get_use_default_typo (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		PangoFontDescription* _tmp3_ = NULL;
		PangoFontDescription* _tmp4_ = NULL;
		_tmp3_ = pango_font_description_from_string ("Monospace 10");
		_tmp4_ = _tmp3_;
		gtk_widget_override_font ((GtkWidget*) self, _tmp4_);
		__vala_PangoFontDescription_free0 (_tmp4_);
	} else {
		StTextEditor* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		PangoFontDescription* _tmp8_ = NULL;
		PangoFontDescription* _tmp9_ = NULL;
		_tmp5_ = self->priv->editor;
		_tmp6_ = st_text_editor_get_editor_font (_tmp5_);
		_tmp7_ = _tmp6_;
		_tmp8_ = pango_font_description_from_string (_tmp7_);
		_tmp9_ = _tmp8_;
		gtk_widget_override_font ((GtkWidget*) self, _tmp9_);
		__vala_PangoFontDescription_free0 (_tmp9_);
	}
}


static void ___lambda13__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda13_ ((StSourceView*) self, pspec);
}


static void __lambda14_ (StSourceView* self, GParamSpec* pspec) {
	StTextEditor* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	PangoFontDescription* _tmp3_ = NULL;
	PangoFontDescription* _tmp4_ = NULL;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = st_text_editor_get_editor_font (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = pango_font_description_from_string (_tmp2_);
	_tmp4_ = _tmp3_;
	gtk_widget_override_font ((GtkWidget*) self, _tmp4_);
	__vala_PangoFontDescription_free0 (_tmp4_);
}


static void ___lambda14__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda14_ ((StSourceView*) self, pspec);
}


static void __lambda15_ (StSourceView* self, GParamSpec* pspec) {
	GtkSourceStyleSchemeManager* scheme_manager = NULL;
	GtkSourceStyleSchemeManager* _tmp0_ = NULL;
	GtkSourceStyleSchemeManager* _tmp1_ = NULL;
	GtkSourceStyleScheme* source_scheme = NULL;
	StTextEditor* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	GtkSourceStyleScheme* _tmp5_ = NULL;
	GtkSourceStyleScheme* _tmp6_ = NULL;
	GtkTextBuffer* _tmp7_ = NULL;
	GtkTextBuffer* _tmp8_ = NULL;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = gtk_source_style_scheme_manager_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	scheme_manager = _tmp1_;
	_tmp2_ = self->priv->editor;
	_tmp3_ = st_text_editor_get_color_scheme (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = gtk_source_style_scheme_manager_get_scheme (scheme_manager, _tmp4_);
	_tmp6_ = _g_object_ref0 (_tmp5_);
	source_scheme = _tmp6_;
	_tmp7_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp8_ = _tmp7_;
	gtk_source_buffer_set_style_scheme (G_TYPE_CHECK_INSTANCE_TYPE (_tmp8_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp8_) : NULL, source_scheme);
	_g_object_unref0 (source_scheme);
	_g_object_unref0 (scheme_manager);
}


static void ___lambda15__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda15_ ((StSourceView*) self, pspec);
}


static void __lambda16_ (StSourceView* self, GParamSpec* pspec) {
	StTextEditor* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->editor;
	_tmp1_ = st_text_editor_get_insert_braces (_tmp0_);
	_tmp2_ = _tmp1_;
	self->priv->insert_matching_braces = _tmp2_;
}


static void ___lambda16__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda16_ ((StSourceView*) self, pspec);
}


static void _st_source_view_on_buffer_changes_gtk_text_buffer_modified_changed (GtkTextBuffer* _sender, gpointer self) {
	st_source_view_on_buffer_changes ((StSourceView*) self);
}


static void st_source_view_connect_signals (StSourceView* self) {
	StTextEditor* _tmp0_ = NULL;
	StTextEditor* _tmp1_ = NULL;
	StTextEditor* _tmp2_ = NULL;
	StTextEditor* _tmp3_ = NULL;
	StTextEditor* _tmp4_ = NULL;
	StTextEditor* _tmp5_ = NULL;
	StTextEditor* _tmp6_ = NULL;
	StTextEditor* _tmp7_ = NULL;
	StTextEditor* _tmp8_ = NULL;
	StTextEditor* _tmp9_ = NULL;
	StTextEditor* _tmp10_ = NULL;
	StTextEditor* _tmp11_ = NULL;
	StTextEditor* _tmp12_ = NULL;
	GtkTextBuffer* _tmp13_ = NULL;
	GtkTextBuffer* _tmp14_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp0_, "notify::show-line-numbers", (GCallback) ___lambda4__g_object_notify, self, 0);
	_tmp1_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp1_, "notify::show-right-margin", (GCallback) ___lambda5__g_object_notify, self, 0);
	_tmp2_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp2_, "notify::right-margin-at", (GCallback) ___lambda6__g_object_notify, self, 0);
	_tmp3_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp3_, "notify::highlight-current-line", (GCallback) ___lambda7__g_object_notify, self, 0);
	_tmp4_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp4_, "notify::highlight-brackets", (GCallback) ___lambda8__g_object_notify, self, 0);
	_tmp5_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp5_, "notify::tab-width", (GCallback) ___lambda9__g_object_notify, self, 0);
	_tmp6_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp6_, "notify::insert-spaces", (GCallback) ___lambda10__g_object_notify, self, 0);
	_tmp7_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp7_, "notify::auto-indent", (GCallback) ___lambda11__g_object_notify, self, 0);
	_tmp8_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp8_, "notify::show-grid-pattern", (GCallback) ___lambda12__g_object_notify, self, 0);
	_tmp9_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp9_, "notify::use-default-typo", (GCallback) ___lambda13__g_object_notify, self, 0);
	_tmp10_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp10_, "notify::editor-font", (GCallback) ___lambda14__g_object_notify, self, 0);
	_tmp11_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp11_, "notify::color-scheme", (GCallback) ___lambda15__g_object_notify, self, 0);
	_tmp12_ = self->priv->editor;
	g_signal_connect_object ((GObject*) _tmp12_, "notify::insert-braces", (GCallback) ___lambda16__g_object_notify, self, 0);
	_tmp13_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp14_ = _tmp13_;
	g_signal_connect_object (_tmp14_, "modified-changed", (GCallback) _st_source_view_on_buffer_changes_gtk_text_buffer_modified_changed, self, 0);
}


static void st_source_view_on_buffer_changes (StSourceView* self) {
	GtkSourceCompletionWords* _tmp0_ = NULL;
	GtkTextBuffer* _tmp1_ = NULL;
	GtkTextBuffer* _tmp2_ = NULL;
	GtkTextBuffer* _tmp3_ = NULL;
	GtkTextBuffer* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->word_completion;
	_tmp1_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp2_ = _tmp1_;
	gtk_source_completion_words_register (_tmp0_, _tmp2_);
	_tmp3_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp4_ = _tmp3_;
	_tmp5_ = gtk_text_buffer_get_modified (_tmp4_);
	g_signal_emit_by_name (self, "buffer-modified", _tmp5_);
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}


static void st_source_view_on_drag_data_received (StSourceView* self, GtkWidget* widget, GdkDragContext* context, gint x, gint y, GtkSelectionData* selection_data, guint target_type, guint time) {
	guint _tmp0_ = 0U;
	g_return_if_fail (self != NULL);
	g_return_if_fail (widget != NULL);
	g_return_if_fail (context != NULL);
	g_return_if_fail (selection_data != NULL);
	_tmp0_ = target_type;
	if (_tmp0_ == ((guint) ST_SOURCE_VIEW_TARGET_TYPE_URI_LIST)) {
		gchar* uri_list = NULL;
		GtkSelectionData* _tmp1_ = NULL;
		guchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		gchar** uris = NULL;
		const gchar* _tmp4_ = NULL;
		gchar** _tmp5_ = NULL;
		gchar** _tmp6_ = NULL;
		gint uris_length1 = 0;
		gint _uris_size_ = 0;
		gchar** _tmp7_ = NULL;
		gint _tmp7__length1 = 0;
		_tmp1_ = selection_data;
		_tmp2_ = gtk_selection_data_get_data (_tmp1_);
		_tmp3_ = string_strip ((const gchar*) _tmp2_);
		uri_list = _tmp3_;
		_tmp4_ = uri_list;
		_tmp6_ = _tmp5_ = g_strsplit (_tmp4_, "\n", 0);
		uris = _tmp6_;
		uris_length1 = _vala_array_length (_tmp5_);
		_uris_size_ = uris_length1;
		_tmp7_ = uris;
		_tmp7__length1 = uris_length1;
		{
			gchar** uri_collection = NULL;
			gint uri_collection_length1 = 0;
			gint _uri_collection_size_ = 0;
			gint uri_it = 0;
			uri_collection = _tmp7_;
			uri_collection_length1 = _tmp7__length1;
			for (uri_it = 0; uri_it < _tmp7__length1; uri_it = uri_it + 1) {
				gchar* _tmp8_ = NULL;
				gchar* uri = NULL;
				_tmp8_ = g_strdup (uri_collection[uri_it]);
				uri = _tmp8_;
				{
					gchar* path = NULL;
					const gchar* _tmp9_ = NULL;
					gchar* _tmp10_ = NULL;
					const gchar* _tmp11_ = NULL;
					_tmp9_ = uri;
					_tmp10_ = st_source_view_get_file_path_from_uri (self, _tmp9_);
					path = _tmp10_;
					_tmp11_ = path;
					g_signal_emit_by_name (self, "drag-n-drop", _tmp11_);
					_g_free0 (path);
					_g_free0 (uri);
				}
			}
		}
		uris = (_vala_array_free (uris, uris_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (uri_list);
	}
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


static gchar* st_source_view_get_file_path_from_uri (StSourceView* self, const gchar* uri) {
	gchar* result = NULL;
	gchar* path = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	const gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (uri != NULL, NULL);
	_tmp0_ = g_strdup ("");
	path = _tmp0_;
	_tmp1_ = uri;
	_tmp2_ = g_str_has_prefix (_tmp1_, "file://");
	if (_tmp2_) {
		const gchar* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		gchar* _tmp6_ = NULL;
		_tmp3_ = uri;
		_tmp4_ = strlen ("file://");
		_tmp5_ = _tmp4_;
		_tmp6_ = string_substring (_tmp3_, (glong) _tmp5_, (glong) (-1));
		_g_free0 (path);
		path = _tmp6_;
	} else {
		const gchar* _tmp7_ = NULL;
		gboolean _tmp8_ = FALSE;
		_tmp7_ = uri;
		_tmp8_ = g_str_has_prefix (_tmp7_, "file:");
		if (_tmp8_) {
			const gchar* _tmp9_ = NULL;
			gint _tmp10_ = 0;
			gint _tmp11_ = 0;
			gchar* _tmp12_ = NULL;
			_tmp9_ = uri;
			_tmp10_ = strlen ("file:");
			_tmp11_ = _tmp10_;
			_tmp12_ = string_substring (_tmp9_, (glong) _tmp11_, (glong) (-1));
			_g_free0 (path);
			path = _tmp12_;
		}
	}
	_tmp13_ = path;
	_tmp14_ = string_strip (_tmp13_);
	_g_free0 (path);
	path = _tmp14_;
	result = path;
	return result;
}


gchar* st_source_view_get_language_name (StSourceView* self) {
	gchar* result = NULL;
	gchar* language = NULL;
	GtkTextBuffer* _tmp0_ = NULL;
	GtkTextBuffer* _tmp1_ = NULL;
	GtkSourceLanguage* _tmp2_ = NULL;
	GtkSourceLanguage* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	language = NULL;
	_tmp0_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = gtk_source_buffer_get_language (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp1_) : NULL);
	_tmp3_ = _tmp2_;
	if (_tmp3_ != NULL) {
		GtkTextBuffer* _tmp4_ = NULL;
		GtkTextBuffer* _tmp5_ = NULL;
		GtkSourceLanguage* _tmp6_ = NULL;
		GtkSourceLanguage* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		_tmp4_ = gtk_text_view_get_buffer ((GtkTextView*) self);
		_tmp5_ = _tmp4_;
		_tmp6_ = gtk_source_buffer_get_language (G_TYPE_CHECK_INSTANCE_TYPE (_tmp5_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp5_) : NULL);
		_tmp7_ = _tmp6_;
		_tmp8_ = gtk_source_language_get_name (_tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = g_strdup (_tmp9_);
		_g_free0 (language);
		language = _tmp10_;
	}
	result = language;
	return result;
}


GtkSourceBuffer* st_source_view_get_source_buffer (StSourceView* self) {
	GtkSourceBuffer* result = NULL;
	GtkTextBuffer* _tmp0_ = NULL;
	GtkTextBuffer* _tmp1_ = NULL;
	GtkSourceBuffer* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = gtk_text_view_get_buffer ((GtkTextView*) self);
	_tmp1_ = _tmp0_;
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, gtk_source_buffer_get_type ()) ? ((GtkSourceBuffer*) _tmp1_) : NULL);
	result = _tmp2_;
	return result;
}


static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_ = 0L;
	gchar _tmp1_ = '\0';
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = index;
	_tmp1_ = ((gchar*) self)[_tmp0_];
	result = _tmp1_;
	return result;
}


static void st_source_view_brace_insert (StSourceView* self, GtkTextIter* location, const gchar* text, gint len) {
	gboolean is_open_brace = FALSE;
	gchar* insert = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gchar _tmp3_ = '\0';
	GtkTextIter iter = {0};
	gboolean _tmp7_ = FALSE;
	gboolean _tmp8_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (location != NULL);
	g_return_if_fail (text != NULL);
	is_open_brace = TRUE;
	_tmp0_ = g_strdup ("");
	insert = _tmp0_;
	_tmp1_ = text;
	_tmp2_ = len;
	_tmp3_ = string_get (_tmp1_, (glong) (_tmp2_ - 1));
	switch (_tmp3_) {
		case '{':
		{
			gchar* _tmp4_ = NULL;
			_tmp4_ = g_strdup ("}");
			_g_free0 (insert);
			insert = _tmp4_;
			break;
		}
		case '[':
		{
			gchar* _tmp5_ = NULL;
			_tmp5_ = g_strdup ("]");
			_g_free0 (insert);
			insert = _tmp5_;
			break;
		}
		case '(':
		{
			gchar* _tmp6_ = NULL;
			_tmp6_ = g_strdup (")");
			_g_free0 (insert);
			insert = _tmp6_;
			break;
		}
		default:
		{
			is_open_brace = FALSE;
			break;
		}
	}
	_tmp8_ = is_open_brace;
	if (_tmp8_) {
		gboolean _tmp9_ = FALSE;
		_tmp9_ = self->priv->insert_matching_braces;
		_tmp7_ = _tmp9_;
	} else {
		_tmp7_ = FALSE;
	}
	if (_tmp7_) {
		GtkTextBuffer* _tmp10_ = NULL;
		GtkTextBuffer* _tmp11_ = NULL;
		const gchar* _tmp12_ = NULL;
		const gchar* _tmp13_ = NULL;
		gint _tmp14_ = 0;
		gint _tmp15_ = 0;
		GtkTextBuffer* _tmp16_ = NULL;
		GtkTextBuffer* _tmp17_ = NULL;
		GtkTextBuffer* _tmp18_ = NULL;
		GtkTextBuffer* _tmp19_ = NULL;
		gint _tmp20_ = 0;
		gint _tmp21_ = 0;
		GtkTextIter _tmp22_ = {0};
		GtkTextBuffer* _tmp23_ = NULL;
		GtkTextBuffer* _tmp24_ = NULL;
		GtkTextIter _tmp25_ = {0};
		_tmp10_ = gtk_text_view_get_buffer ((GtkTextView*) self);
		_tmp11_ = _tmp10_;
		_tmp12_ = insert;
		_tmp13_ = insert;
		_tmp14_ = strlen (_tmp13_);
		_tmp15_ = _tmp14_;
		gtk_text_buffer_insert (_tmp11_, location, _tmp12_, _tmp15_);
		_tmp16_ = gtk_text_view_get_buffer ((GtkTextView*) self);
		_tmp17_ = _tmp16_;
		_tmp18_ = gtk_text_view_get_buffer ((GtkTextView*) self);
		_tmp19_ = _tmp18_;
		g_object_get (_tmp19_, "cursor-position", &_tmp20_, NULL);
		_tmp21_ = _tmp20_;
		gtk_text_buffer_get_iter_at_offset (_tmp17_, &_tmp22_, _tmp21_ - 1);
		iter = _tmp22_;
		_tmp23_ = gtk_text_view_get_buffer ((GtkTextView*) self);
		_tmp24_ = _tmp23_;
		_tmp25_ = iter;
		gtk_text_buffer_place_cursor (_tmp24_, &_tmp25_);
	}
	_g_free0 (insert);
}


GtkSourceSearchSettings* st_source_view_get_search_settings (StSourceView* self) {
	GtkSourceSearchSettings* result;
	GtkSourceSearchSettings* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_search_settings;
	result = _tmp0_;
	return result;
}


GtkSourceFile* st_source_view_get_source_file (StSourceView* self) {
	GtkSourceFile* result;
	GtkSourceFile* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_source_file;
	result = _tmp0_;
	return result;
}


static void st_source_view_class_init (StSourceViewClass * klass) {
	st_source_view_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (StSourceViewPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_st_source_view_get_property;
	G_OBJECT_CLASS (klass)->finalize = st_source_view_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), ST_SOURCE_VIEW_SEARCH_SETTINGS, g_param_spec_object ("search-settings", "search-settings", "search-settings", gtk_source_search_settings_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ST_SOURCE_VIEW_SOURCE_FILE, g_param_spec_object ("source-file", "source-file", "source-file", gtk_source_file_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("buffer_modified", TYPE_ST_SOURCE_VIEW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOOLEAN, G_TYPE_NONE, 1, G_TYPE_BOOLEAN);
	g_signal_new ("drag_n_drop", TYPE_ST_SOURCE_VIEW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
	g_signal_new ("file_saved", TYPE_ST_SOURCE_VIEW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("file_loaded", TYPE_ST_SOURCE_VIEW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void st_source_view_instance_init (StSourceView * self) {
	self->priv = ST_SOURCE_VIEW_GET_PRIVATE (self);
}


static void st_source_view_finalize (GObject* obj) {
	StSourceView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_ST_SOURCE_VIEW, StSourceView);
	_g_object_unref0 (self->priv->_search_settings);
	_g_object_unref0 (self->priv->word_completion);
	_g_object_unref0 (self->priv->_source_file);
	_g_object_unref0 (self->priv->file_saver);
	_g_object_unref0 (self->priv->file_loader);
	_g_object_unref0 (self->priv->editor);
	G_OBJECT_CLASS (st_source_view_parent_class)->finalize (obj);
}


GType st_source_view_get_type (void) {
	static volatile gsize st_source_view_type_id__volatile = 0;
	if (g_once_init_enter (&st_source_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (StSourceViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) st_source_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (StSourceView), 0, (GInstanceInitFunc) st_source_view_instance_init, NULL };
		GType st_source_view_type_id;
		st_source_view_type_id = g_type_register_static (gtk_source_view_get_type (), "StSourceView", &g_define_type_info, 0);
		g_once_init_leave (&st_source_view_type_id__volatile, st_source_view_type_id);
	}
	return st_source_view_type_id__volatile;
}


static void _vala_st_source_view_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	StSourceView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_ST_SOURCE_VIEW, StSourceView);
	switch (property_id) {
		case ST_SOURCE_VIEW_SEARCH_SETTINGS:
		g_value_set_object (value, st_source_view_get_search_settings (self));
		break;
		case ST_SOURCE_VIEW_SOURCE_FILE:
		g_value_set_object (value, st_source_view_get_source_file (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



