/* text-editor.c generated by valac 0.28.0, the Vala compiler
 * generated from text-editor.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_TEXT_EDITOR (text_editor_get_type ())
#define TEXT_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXT_EDITOR, TextEditor))
#define TEXT_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXT_EDITOR, TextEditorClass))
#define IS_TEXT_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXT_EDITOR))
#define IS_TEXT_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXT_EDITOR))
#define TEXT_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXT_EDITOR, TextEditorClass))

typedef struct _TextEditor TextEditor;
typedef struct _TextEditorClass TextEditorClass;
typedef struct _TextEditorPrivate TextEditorPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _TextEditor {
	GObject parent_instance;
	TextEditorPrivate * priv;
};

struct _TextEditorClass {
	GObjectClass parent_class;
};

struct _TextEditorPrivate {
	gboolean _show_line_numbers;
	gboolean _show_right_margin;
	gint _right_margin_at;
	gboolean _use_text_wrap;
	gboolean _highlight_current_line;
	gboolean _highlight_brackets;
	gint _tab_width;
	gboolean _insert_spaces;
	gboolean _auto_indent;
	gboolean _show_grid_pattern;
	gboolean _use_default_typo;
	gchar* _editor_font;
	gchar* _color_scheme;
	gboolean _prefer_dark;
};


static gpointer text_editor_parent_class = NULL;

GType text_editor_get_type (void) G_GNUC_CONST;
#define TEXT_EDITOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_TEXT_EDITOR, TextEditorPrivate))
enum  {
	TEXT_EDITOR_DUMMY_PROPERTY,
	TEXT_EDITOR_SHOW_LINE_NUMBERS,
	TEXT_EDITOR_SHOW_RIGHT_MARGIN,
	TEXT_EDITOR_RIGHT_MARGIN_AT,
	TEXT_EDITOR_USE_TEXT_WRAP,
	TEXT_EDITOR_HIGHLIGHT_CURRENT_LINE,
	TEXT_EDITOR_HIGHLIGHT_BRACKETS,
	TEXT_EDITOR_TAB_WIDTH,
	TEXT_EDITOR_INSERT_SPACES,
	TEXT_EDITOR_AUTO_INDENT,
	TEXT_EDITOR_SHOW_GRID_PATTERN,
	TEXT_EDITOR_USE_DEFAULT_TYPO,
	TEXT_EDITOR_EDITOR_FONT,
	TEXT_EDITOR_COLOR_SCHEME,
	TEXT_EDITOR_PREFER_DARK
};
TextEditor* text_editor_new (void);
TextEditor* text_editor_construct (GType object_type);
gboolean text_editor_get_show_line_numbers (TextEditor* self);
void text_editor_set_show_line_numbers (TextEditor* self, gboolean value);
gboolean text_editor_get_show_right_margin (TextEditor* self);
void text_editor_set_show_right_margin (TextEditor* self, gboolean value);
gint text_editor_get_right_margin_at (TextEditor* self);
void text_editor_set_right_margin_at (TextEditor* self, gint value);
gboolean text_editor_get_use_text_wrap (TextEditor* self);
void text_editor_set_use_text_wrap (TextEditor* self, gboolean value);
gboolean text_editor_get_highlight_current_line (TextEditor* self);
void text_editor_set_highlight_current_line (TextEditor* self, gboolean value);
gboolean text_editor_get_highlight_brackets (TextEditor* self);
void text_editor_set_highlight_brackets (TextEditor* self, gboolean value);
gint text_editor_get_tab_width (TextEditor* self);
void text_editor_set_tab_width (TextEditor* self, gint value);
gboolean text_editor_get_insert_spaces (TextEditor* self);
void text_editor_set_insert_spaces (TextEditor* self, gboolean value);
gboolean text_editor_get_auto_indent (TextEditor* self);
void text_editor_set_auto_indent (TextEditor* self, gboolean value);
gboolean text_editor_get_show_grid_pattern (TextEditor* self);
void text_editor_set_show_grid_pattern (TextEditor* self, gboolean value);
gboolean text_editor_get_use_default_typo (TextEditor* self);
void text_editor_set_use_default_typo (TextEditor* self, gboolean value);
const gchar* text_editor_get_editor_font (TextEditor* self);
void text_editor_set_editor_font (TextEditor* self, const gchar* value);
const gchar* text_editor_get_color_scheme (TextEditor* self);
void text_editor_set_color_scheme (TextEditor* self, const gchar* value);
gboolean text_editor_get_prefer_dark (TextEditor* self);
void text_editor_set_prefer_dark (TextEditor* self, gboolean value);
static void text_editor_finalize (GObject* obj);
static void _vala_text_editor_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_text_editor_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


TextEditor* text_editor_construct (GType object_type) {
	TextEditor * self = NULL;
	self = (TextEditor*) g_object_new (object_type, NULL);
	return self;
}


TextEditor* text_editor_new (void) {
	return text_editor_construct (TYPE_TEXT_EDITOR);
}


gboolean text_editor_get_show_line_numbers (TextEditor* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_show_line_numbers;
	result = _tmp0_;
	return result;
}


void text_editor_set_show_line_numbers (TextEditor* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_show_line_numbers;
	_tmp1_ = value;
	if (_tmp0_ != _tmp1_) {
		gboolean _tmp2_ = FALSE;
		_tmp2_ = value;
		self->priv->_show_line_numbers = _tmp2_;
	}
	g_object_notify ((GObject *) self, "show-line-numbers");
}


gboolean text_editor_get_show_right_margin (TextEditor* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_show_right_margin;
	result = _tmp0_;
	return result;
}


void text_editor_set_show_right_margin (TextEditor* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_show_right_margin;
	_tmp1_ = value;
	if (_tmp0_ != _tmp1_) {
		gboolean _tmp2_ = FALSE;
		_tmp2_ = value;
		self->priv->_show_right_margin = _tmp2_;
	}
	g_object_notify ((GObject *) self, "show-right-margin");
}


gint text_editor_get_right_margin_at (TextEditor* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_right_margin_at;
	result = _tmp0_;
	return result;
}


void text_editor_set_right_margin_at (TextEditor* self, gint value) {
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_right_margin_at;
	_tmp1_ = value;
	if (_tmp0_ != _tmp1_) {
		gint _tmp2_ = 0;
		_tmp2_ = value;
		self->priv->_right_margin_at = _tmp2_;
	}
	g_object_notify ((GObject *) self, "right-margin-at");
}


gboolean text_editor_get_use_text_wrap (TextEditor* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_use_text_wrap;
	result = _tmp0_;
	return result;
}


void text_editor_set_use_text_wrap (TextEditor* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_use_text_wrap;
	_tmp1_ = value;
	if (_tmp0_ != _tmp1_) {
		gboolean _tmp2_ = FALSE;
		_tmp2_ = value;
		self->priv->_use_text_wrap = _tmp2_;
	}
	g_object_notify ((GObject *) self, "use-text-wrap");
}


gboolean text_editor_get_highlight_current_line (TextEditor* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_highlight_current_line;
	result = _tmp0_;
	return result;
}


void text_editor_set_highlight_current_line (TextEditor* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_highlight_current_line;
	_tmp1_ = value;
	if (_tmp0_ != _tmp1_) {
		gboolean _tmp2_ = FALSE;
		_tmp2_ = value;
		self->priv->_highlight_current_line = _tmp2_;
	}
	g_object_notify ((GObject *) self, "highlight-current-line");
}


gboolean text_editor_get_highlight_brackets (TextEditor* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_highlight_brackets;
	result = _tmp0_;
	return result;
}


void text_editor_set_highlight_brackets (TextEditor* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_highlight_brackets;
	_tmp1_ = value;
	if (_tmp0_ != _tmp1_) {
		gboolean _tmp2_ = FALSE;
		_tmp2_ = value;
		self->priv->_highlight_brackets = _tmp2_;
	}
	g_object_notify ((GObject *) self, "highlight-brackets");
}


gint text_editor_get_tab_width (TextEditor* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_tab_width;
	result = _tmp0_;
	return result;
}


void text_editor_set_tab_width (TextEditor* self, gint value) {
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_tab_width;
	_tmp1_ = value;
	if (_tmp0_ != _tmp1_) {
		gint _tmp2_ = 0;
		_tmp2_ = value;
		self->priv->_tab_width = _tmp2_;
	}
	g_object_notify ((GObject *) self, "tab-width");
}


gboolean text_editor_get_insert_spaces (TextEditor* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_insert_spaces;
	result = _tmp0_;
	return result;
}


void text_editor_set_insert_spaces (TextEditor* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_insert_spaces;
	_tmp1_ = value;
	if (_tmp0_ != _tmp1_) {
		gboolean _tmp2_ = FALSE;
		_tmp2_ = value;
		self->priv->_insert_spaces = _tmp2_;
	}
	g_object_notify ((GObject *) self, "insert-spaces");
}


gboolean text_editor_get_auto_indent (TextEditor* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_auto_indent;
	result = _tmp0_;
	return result;
}


void text_editor_set_auto_indent (TextEditor* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_auto_indent;
	_tmp1_ = value;
	if (_tmp0_ != _tmp1_) {
		gboolean _tmp2_ = FALSE;
		_tmp2_ = value;
		self->priv->_auto_indent = _tmp2_;
	}
	g_object_notify ((GObject *) self, "auto-indent");
}


gboolean text_editor_get_show_grid_pattern (TextEditor* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_show_grid_pattern;
	result = _tmp0_;
	return result;
}


void text_editor_set_show_grid_pattern (TextEditor* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_show_grid_pattern;
	_tmp1_ = value;
	if (_tmp0_ != _tmp1_) {
		gboolean _tmp2_ = FALSE;
		_tmp2_ = value;
		self->priv->_show_grid_pattern = _tmp2_;
	}
	g_object_notify ((GObject *) self, "show-grid-pattern");
}


gboolean text_editor_get_use_default_typo (TextEditor* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_use_default_typo;
	result = _tmp0_;
	return result;
}


void text_editor_set_use_default_typo (TextEditor* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_use_default_typo;
	_tmp1_ = value;
	if (_tmp0_ != _tmp1_) {
		gboolean _tmp2_ = FALSE;
		_tmp2_ = value;
		self->priv->_use_default_typo = _tmp2_;
	}
	g_object_notify ((GObject *) self, "use-default-typo");
}


const gchar* text_editor_get_editor_font (TextEditor* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_editor_font;
	result = _tmp0_;
	return result;
}


void text_editor_set_editor_font (TextEditor* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_editor_font;
	_tmp1_ = value;
	if (g_strcmp0 (_tmp0_, _tmp1_) != 0) {
		const gchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		_tmp2_ = value;
		_tmp3_ = g_strdup (_tmp2_);
		_g_free0 (self->priv->_editor_font);
		self->priv->_editor_font = _tmp3_;
	}
	g_object_notify ((GObject *) self, "editor-font");
}


const gchar* text_editor_get_color_scheme (TextEditor* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_color_scheme;
	result = _tmp0_;
	return result;
}


void text_editor_set_color_scheme (TextEditor* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_color_scheme;
	_tmp1_ = value;
	if (g_strcmp0 (_tmp0_, _tmp1_) != 0) {
		const gchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		_tmp2_ = value;
		_tmp3_ = g_strdup (_tmp2_);
		_g_free0 (self->priv->_color_scheme);
		self->priv->_color_scheme = _tmp3_;
	}
	g_object_notify ((GObject *) self, "color-scheme");
}


gboolean text_editor_get_prefer_dark (TextEditor* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_prefer_dark;
	result = _tmp0_;
	return result;
}


void text_editor_set_prefer_dark (TextEditor* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_prefer_dark;
	_tmp1_ = value;
	if (_tmp0_ != _tmp1_) {
		gboolean _tmp2_ = FALSE;
		_tmp2_ = value;
		self->priv->_prefer_dark = _tmp2_;
	}
	g_object_notify ((GObject *) self, "prefer-dark");
}


static void text_editor_class_init (TextEditorClass * klass) {
	text_editor_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (TextEditorPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_text_editor_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_text_editor_set_property;
	G_OBJECT_CLASS (klass)->finalize = text_editor_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_SHOW_LINE_NUMBERS, g_param_spec_boolean ("show-line-numbers", "show-line-numbers", "show-line-numbers", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_SHOW_RIGHT_MARGIN, g_param_spec_boolean ("show-right-margin", "show-right-margin", "show-right-margin", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_RIGHT_MARGIN_AT, g_param_spec_int ("right-margin-at", "right-margin-at", "right-margin-at", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_USE_TEXT_WRAP, g_param_spec_boolean ("use-text-wrap", "use-text-wrap", "use-text-wrap", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_HIGHLIGHT_CURRENT_LINE, g_param_spec_boolean ("highlight-current-line", "highlight-current-line", "highlight-current-line", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_HIGHLIGHT_BRACKETS, g_param_spec_boolean ("highlight-brackets", "highlight-brackets", "highlight-brackets", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_TAB_WIDTH, g_param_spec_int ("tab-width", "tab-width", "tab-width", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_INSERT_SPACES, g_param_spec_boolean ("insert-spaces", "insert-spaces", "insert-spaces", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_AUTO_INDENT, g_param_spec_boolean ("auto-indent", "auto-indent", "auto-indent", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_SHOW_GRID_PATTERN, g_param_spec_boolean ("show-grid-pattern", "show-grid-pattern", "show-grid-pattern", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_USE_DEFAULT_TYPO, g_param_spec_boolean ("use-default-typo", "use-default-typo", "use-default-typo", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_EDITOR_FONT, g_param_spec_string ("editor-font", "editor-font", "editor-font", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_COLOR_SCHEME, g_param_spec_string ("color-scheme", "color-scheme", "color-scheme", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), TEXT_EDITOR_PREFER_DARK, g_param_spec_boolean ("prefer-dark", "prefer-dark", "prefer-dark", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void text_editor_instance_init (TextEditor * self) {
	self->priv = TEXT_EDITOR_GET_PRIVATE (self);
}


static void text_editor_finalize (GObject* obj) {
	TextEditor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TEXT_EDITOR, TextEditor);
	_g_free0 (self->priv->_editor_font);
	_g_free0 (self->priv->_color_scheme);
	G_OBJECT_CLASS (text_editor_parent_class)->finalize (obj);
}


GType text_editor_get_type (void) {
	static volatile gsize text_editor_type_id__volatile = 0;
	if (g_once_init_enter (&text_editor_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TextEditorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) text_editor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TextEditor), 0, (GInstanceInitFunc) text_editor_instance_init, NULL };
		GType text_editor_type_id;
		text_editor_type_id = g_type_register_static (G_TYPE_OBJECT, "TextEditor", &g_define_type_info, 0);
		g_once_init_leave (&text_editor_type_id__volatile, text_editor_type_id);
	}
	return text_editor_type_id__volatile;
}


static void _vala_text_editor_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	TextEditor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_TEXT_EDITOR, TextEditor);
	switch (property_id) {
		case TEXT_EDITOR_SHOW_LINE_NUMBERS:
		g_value_set_boolean (value, text_editor_get_show_line_numbers (self));
		break;
		case TEXT_EDITOR_SHOW_RIGHT_MARGIN:
		g_value_set_boolean (value, text_editor_get_show_right_margin (self));
		break;
		case TEXT_EDITOR_RIGHT_MARGIN_AT:
		g_value_set_int (value, text_editor_get_right_margin_at (self));
		break;
		case TEXT_EDITOR_USE_TEXT_WRAP:
		g_value_set_boolean (value, text_editor_get_use_text_wrap (self));
		break;
		case TEXT_EDITOR_HIGHLIGHT_CURRENT_LINE:
		g_value_set_boolean (value, text_editor_get_highlight_current_line (self));
		break;
		case TEXT_EDITOR_HIGHLIGHT_BRACKETS:
		g_value_set_boolean (value, text_editor_get_highlight_brackets (self));
		break;
		case TEXT_EDITOR_TAB_WIDTH:
		g_value_set_int (value, text_editor_get_tab_width (self));
		break;
		case TEXT_EDITOR_INSERT_SPACES:
		g_value_set_boolean (value, text_editor_get_insert_spaces (self));
		break;
		case TEXT_EDITOR_AUTO_INDENT:
		g_value_set_boolean (value, text_editor_get_auto_indent (self));
		break;
		case TEXT_EDITOR_SHOW_GRID_PATTERN:
		g_value_set_boolean (value, text_editor_get_show_grid_pattern (self));
		break;
		case TEXT_EDITOR_USE_DEFAULT_TYPO:
		g_value_set_boolean (value, text_editor_get_use_default_typo (self));
		break;
		case TEXT_EDITOR_EDITOR_FONT:
		g_value_set_string (value, text_editor_get_editor_font (self));
		break;
		case TEXT_EDITOR_COLOR_SCHEME:
		g_value_set_string (value, text_editor_get_color_scheme (self));
		break;
		case TEXT_EDITOR_PREFER_DARK:
		g_value_set_boolean (value, text_editor_get_prefer_dark (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_text_editor_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	TextEditor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_TEXT_EDITOR, TextEditor);
	switch (property_id) {
		case TEXT_EDITOR_SHOW_LINE_NUMBERS:
		text_editor_set_show_line_numbers (self, g_value_get_boolean (value));
		break;
		case TEXT_EDITOR_SHOW_RIGHT_MARGIN:
		text_editor_set_show_right_margin (self, g_value_get_boolean (value));
		break;
		case TEXT_EDITOR_RIGHT_MARGIN_AT:
		text_editor_set_right_margin_at (self, g_value_get_int (value));
		break;
		case TEXT_EDITOR_USE_TEXT_WRAP:
		text_editor_set_use_text_wrap (self, g_value_get_boolean (value));
		break;
		case TEXT_EDITOR_HIGHLIGHT_CURRENT_LINE:
		text_editor_set_highlight_current_line (self, g_value_get_boolean (value));
		break;
		case TEXT_EDITOR_HIGHLIGHT_BRACKETS:
		text_editor_set_highlight_brackets (self, g_value_get_boolean (value));
		break;
		case TEXT_EDITOR_TAB_WIDTH:
		text_editor_set_tab_width (self, g_value_get_int (value));
		break;
		case TEXT_EDITOR_INSERT_SPACES:
		text_editor_set_insert_spaces (self, g_value_get_boolean (value));
		break;
		case TEXT_EDITOR_AUTO_INDENT:
		text_editor_set_auto_indent (self, g_value_get_boolean (value));
		break;
		case TEXT_EDITOR_SHOW_GRID_PATTERN:
		text_editor_set_show_grid_pattern (self, g_value_get_boolean (value));
		break;
		case TEXT_EDITOR_USE_DEFAULT_TYPO:
		text_editor_set_use_default_typo (self, g_value_get_boolean (value));
		break;
		case TEXT_EDITOR_EDITOR_FONT:
		text_editor_set_editor_font (self, g_value_get_string (value));
		break;
		case TEXT_EDITOR_COLOR_SCHEME:
		text_editor_set_color_scheme (self, g_value_get_string (value));
		break;
		case TEXT_EDITOR_PREFER_DARK:
		text_editor_set_prefer_dark (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



